// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/web/v1/web.proto

// web-api contract — DESIGNED FROM SCRATCH (web-platform-plan.md). This is the
// edge the Next.js BFF (Route Handlers / Server Actions) calls server-side over
// gRPC + mTLS; the browser never speaks gRPC. It is SEPARATE from the legacy
// CPSock game login and from dbServer's AccountService (api/db/v1), which
// mirrors the legacy G↔DB messages. web-api reuses the same `account` table and
// argon2id hashing underneath, but exposes its own web-facing surface.
//
// Generate with `make proto` (protoc + protoc-gen-go/-grpc).

package webv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateResult is the outcome of a sign-up. Business outcomes (name taken,
// invalid input) are carried here, not as gRPC error codes — only infra
// failures surface as errors.
type CreateResult int32

const (
	CreateResult_CREATE_RESULT_UNSPECIFIED CreateResult = 0
	CreateResult_CREATE_RESULT_OK          CreateResult = 1 // account created; account_id is set
	CreateResult_CREATE_RESULT_NAME_TAKEN  CreateResult = 2 // canonical name already exists
	CreateResult_CREATE_RESULT_INVALID     CreateResult = 3 // name/password/email failed validation
)

// Enum value maps for CreateResult.
var (
	CreateResult_name = map[int32]string{
		0: "CREATE_RESULT_UNSPECIFIED",
		1: "CREATE_RESULT_OK",
		2: "CREATE_RESULT_NAME_TAKEN",
		3: "CREATE_RESULT_INVALID",
	}
	CreateResult_value = map[string]int32{
		"CREATE_RESULT_UNSPECIFIED": 0,
		"CREATE_RESULT_OK":          1,
		"CREATE_RESULT_NAME_TAKEN":  2,
		"CREATE_RESULT_INVALID":     3,
	}
)

func (x CreateResult) Enum() *CreateResult {
	p := new(CreateResult)
	*p = x
	return p
}

func (x CreateResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateResult) Descriptor() protoreflect.EnumDescriptor {
	return file_api_web_v1_web_proto_enumTypes[0].Descriptor()
}

func (CreateResult) Type() protoreflect.EnumType {
	return &file_api_web_v1_web_proto_enumTypes[0]
}

func (x CreateResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateResult.Descriptor instead.
func (CreateResult) EnumDescriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{0}
}

// AdminResult carries the business outcome of an admin write (authorization,
// validation, missing target) in the body — only infra failures become gRPC errors.
type AdminResult int32

const (
	AdminResult_ADMIN_RESULT_UNSPECIFIED AdminResult = 0
	AdminResult_ADMIN_RESULT_OK          AdminResult = 1
	AdminResult_ADMIN_RESULT_FORBIDDEN   AdminResult = 2 // caller is not a moderator/admin
	AdminResult_ADMIN_RESULT_INVALID     AdminResult = 3 // validation failed (bad slot, unknown target, …)
	AdminResult_ADMIN_RESULT_NOT_FOUND   AdminResult = 4 // target definition does not exist
)

// Enum value maps for AdminResult.
var (
	AdminResult_name = map[int32]string{
		0: "ADMIN_RESULT_UNSPECIFIED",
		1: "ADMIN_RESULT_OK",
		2: "ADMIN_RESULT_FORBIDDEN",
		3: "ADMIN_RESULT_INVALID",
		4: "ADMIN_RESULT_NOT_FOUND",
	}
	AdminResult_value = map[string]int32{
		"ADMIN_RESULT_UNSPECIFIED": 0,
		"ADMIN_RESULT_OK":          1,
		"ADMIN_RESULT_FORBIDDEN":   2,
		"ADMIN_RESULT_INVALID":     3,
		"ADMIN_RESULT_NOT_FOUND":   4,
	}
)

func (x AdminResult) Enum() *AdminResult {
	p := new(AdminResult)
	*p = x
	return p
}

func (x AdminResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminResult) Descriptor() protoreflect.EnumDescriptor {
	return file_api_web_v1_web_proto_enumTypes[1].Descriptor()
}

func (AdminResult) Type() protoreflect.EnumType {
	return &file_api_web_v1_web_proto_enumTypes[1]
}

func (x AdminResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminResult.Descriptor instead.
func (AdminResult) EnumDescriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{1}
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // canonicalized to lowercase server-side
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // plaintext over the mTLS link; hashed before storage
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`       // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        CreateResult           `protobuf:"varint,1,opt,name=result,proto3,enum=web.v1.CreateResult" json:"result,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // set only when result is CREATE_RESULT_OK
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetResult() CreateResult {
	if x != nil {
		return x.Result
	}
	return CreateResult_CREATE_RESULT_UNSPECIFIED
}

func (x *CreateAccountResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type VerifyCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialsRequest) Reset() {
	*x = VerifyCredentialsRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialsRequest) ProtoMessage() {}

func (x *VerifyCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialsRequest.ProtoReflect.Descriptor instead.
func (*VerifyCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCredentialsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerifyCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyCredentialsResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Ok        bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                // name exists and password matches
	AccountId int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // set only when ok
	Blocked   bool                   `protobuf:"varint,3,opt,name=blocked,proto3" json:"blocked,omitempty"`                      // account.is_blocked — caller decides how to surface it
	// role is account.role ('player'/'moderator'/'admin'). The BFF stores it in the
	// session to gate the moderator UI (page visibility only). It is NOT the
	// authorization decision — NpcAdminService re-checks the role server-side on
	// every call, so a tampered session flag still gets ADMIN_RESULT_FORBIDDEN.
	Role          string `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialsResponse) Reset() {
	*x = VerifyCredentialsResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialsResponse) ProtoMessage() {}

func (x *VerifyCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialsResponse.ProtoReflect.Descriptor instead.
func (*VerifyCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCredentialsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyCredentialsResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *VerifyCredentialsResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

func (x *VerifyCredentialsResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AdminAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AdminResult            `protobuf:"varint,1,opt,name=result,proto3,enum=web.v1.AdminResult" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAck) Reset() {
	*x = AdminAck{}
	mi := &file_api_web_v1_web_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAck) ProtoMessage() {}

func (x *AdminAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAck.ProtoReflect.Descriptor instead.
func (*AdminAck) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{4}
}

func (x *AdminAck) GetResult() AdminResult {
	if x != nil {
		return x.Result
	}
	return AdminResult_ADMIN_RESULT_UNSPECIFIED
}

// AdminNpcShopItem mirrors the DB shop slot; price is global, not per-slot.
type AdminNpcShopItem struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Slot      int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	ItemIndex int32                  `protobuf:"varint,2,opt,name=item_index,json=itemIndex,proto3" json:"item_index,omitempty"`
	Eff1      int32                  `protobuf:"varint,3,opt,name=eff1,proto3" json:"eff1,omitempty"`
	Effv1     int32                  `protobuf:"varint,4,opt,name=effv1,proto3" json:"effv1,omitempty"`
	Eff2      int32                  `protobuf:"varint,5,opt,name=eff2,proto3" json:"eff2,omitempty"`
	Effv2     int32                  `protobuf:"varint,6,opt,name=effv2,proto3" json:"effv2,omitempty"`
	Eff3      int32                  `protobuf:"varint,7,opt,name=eff3,proto3" json:"eff3,omitempty"`
	Effv3     int32                  `protobuf:"varint,8,opt,name=effv3,proto3" json:"effv3,omitempty"`
	// quantity is the stack amount sold by this slot. 0 is accepted as 1 for
	// older callers; values >1 are materialized as EF_AMOUNT in the legacy item.
	Quantity      int32 `protobuf:"varint,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminNpcShopItem) Reset() {
	*x = AdminNpcShopItem{}
	mi := &file_api_web_v1_web_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminNpcShopItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminNpcShopItem) ProtoMessage() {}

func (x *AdminNpcShopItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminNpcShopItem.ProtoReflect.Descriptor instead.
func (*AdminNpcShopItem) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{5}
}

func (x *AdminNpcShopItem) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *AdminNpcShopItem) GetItemIndex() int32 {
	if x != nil {
		return x.ItemIndex
	}
	return 0
}

func (x *AdminNpcShopItem) GetEff1() int32 {
	if x != nil {
		return x.Eff1
	}
	return 0
}

func (x *AdminNpcShopItem) GetEffv1() int32 {
	if x != nil {
		return x.Effv1
	}
	return 0
}

func (x *AdminNpcShopItem) GetEff2() int32 {
	if x != nil {
		return x.Eff2
	}
	return 0
}

func (x *AdminNpcShopItem) GetEffv2() int32 {
	if x != nil {
		return x.Effv2
	}
	return 0
}

func (x *AdminNpcShopItem) GetEff3() int32 {
	if x != nil {
		return x.Eff3
	}
	return 0
}

func (x *AdminNpcShopItem) GetEffv3() int32 {
	if x != nil {
		return x.Effv3
	}
	return 0
}

func (x *AdminNpcShopItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type AdminNpc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	TemplateName  string                 `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MapId         int32                  `protobuf:"varint,6,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	PosX          int32                  `protobuf:"varint,7,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          int32                  `protobuf:"varint,8,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	RouteType     int32                  `protobuf:"varint,9,opt,name=route_type,json=routeType,proto3" json:"route_type,omitempty"`
	Merchant      int32                  `protobuf:"varint,10,opt,name=merchant,proto3" json:"merchant,omitempty"`
	Shop          []*AdminNpcShopItem    `protobuf:"bytes,11,rep,name=shop,proto3" json:"shop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminNpc) Reset() {
	*x = AdminNpc{}
	mi := &file_api_web_v1_web_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminNpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminNpc) ProtoMessage() {}

func (x *AdminNpc) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminNpc.ProtoReflect.Descriptor instead.
func (*AdminNpc) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{6}
}

func (x *AdminNpc) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AdminNpc) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *AdminNpc) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *AdminNpc) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AdminNpc) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AdminNpc) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *AdminNpc) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *AdminNpc) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *AdminNpc) GetRouteType() int32 {
	if x != nil {
		return x.RouteType
	}
	return 0
}

func (x *AdminNpc) GetMerchant() int32 {
	if x != nil {
		return x.Merchant
	}
	return 0
}

func (x *AdminNpc) GetShop() []*AdminNpcShopItem {
	if x != nil {
		return x.Shop
	}
	return nil
}

type ListNpcsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId   int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNpcsRequest) Reset() {
	*x = ListNpcsRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNpcsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNpcsRequest) ProtoMessage() {}

func (x *ListNpcsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNpcsRequest.ProtoReflect.Descriptor instead.
func (*ListNpcsRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{7}
}

func (x *ListNpcsRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

type ListNpcsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AdminResult            `protobuf:"varint,1,opt,name=result,proto3,enum=web.v1.AdminResult" json:"result,omitempty"`
	Npcs          []*AdminNpc            `protobuf:"bytes,2,rep,name=npcs,proto3" json:"npcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNpcsResponse) Reset() {
	*x = ListNpcsResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNpcsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNpcsResponse) ProtoMessage() {}

func (x *ListNpcsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNpcsResponse.ProtoReflect.Descriptor instead.
func (*ListNpcsResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{8}
}

func (x *ListNpcsResponse) GetResult() AdminResult {
	if x != nil {
		return x.Result
	}
	return AdminResult_ADMIN_RESULT_UNSPECIFIED
}

func (x *ListNpcsResponse) GetNpcs() []*AdminNpc {
	if x != nil {
		return x.Npcs
	}
	return nil
}

type GetNpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId   int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	NpcId         int64                  `protobuf:"varint,2,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNpcRequest) Reset() {
	*x = GetNpcRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNpcRequest) ProtoMessage() {}

func (x *GetNpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNpcRequest.ProtoReflect.Descriptor instead.
func (*GetNpcRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{9}
}

func (x *GetNpcRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

func (x *GetNpcRequest) GetNpcId() int64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

type GetNpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AdminResult            `protobuf:"varint,1,opt,name=result,proto3,enum=web.v1.AdminResult" json:"result,omitempty"`
	Npc           *AdminNpc              `protobuf:"bytes,2,opt,name=npc,proto3" json:"npc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNpcResponse) Reset() {
	*x = GetNpcResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNpcResponse) ProtoMessage() {}

func (x *GetNpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNpcResponse.ProtoReflect.Descriptor instead.
func (*GetNpcResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{10}
}

func (x *GetNpcResponse) GetResult() AdminResult {
	if x != nil {
		return x.Result
	}
	return AdminResult_ADMIN_RESULT_UNSPECIFIED
}

func (x *GetNpcResponse) GetNpc() *AdminNpc {
	if x != nil {
		return x.Npc
	}
	return nil
}

type UpsertNpcRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	// id is ignored on create; the slug is the stable key. Position/visibility/
	// merchant fields are applied as given.
	Slug          string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	TemplateName  string `protobuf:"bytes,3,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	DisplayName   string `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Enabled       bool   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	MapId         int32  `protobuf:"varint,6,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	PosX          int32  `protobuf:"varint,7,opt,name=pos_x,json=posX,proto3" json:"pos_x,omitempty"`
	PosY          int32  `protobuf:"varint,8,opt,name=pos_y,json=posY,proto3" json:"pos_y,omitempty"`
	RouteType     int32  `protobuf:"varint,9,opt,name=route_type,json=routeType,proto3" json:"route_type,omitempty"`
	Merchant      int32  `protobuf:"varint,10,opt,name=merchant,proto3" json:"merchant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertNpcRequest) Reset() {
	*x = UpsertNpcRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertNpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertNpcRequest) ProtoMessage() {}

func (x *UpsertNpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertNpcRequest.ProtoReflect.Descriptor instead.
func (*UpsertNpcRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{11}
}

func (x *UpsertNpcRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

func (x *UpsertNpcRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *UpsertNpcRequest) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *UpsertNpcRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpsertNpcRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UpsertNpcRequest) GetMapId() int32 {
	if x != nil {
		return x.MapId
	}
	return 0
}

func (x *UpsertNpcRequest) GetPosX() int32 {
	if x != nil {
		return x.PosX
	}
	return 0
}

func (x *UpsertNpcRequest) GetPosY() int32 {
	if x != nil {
		return x.PosY
	}
	return 0
}

func (x *UpsertNpcRequest) GetRouteType() int32 {
	if x != nil {
		return x.RouteType
	}
	return 0
}

func (x *UpsertNpcRequest) GetMerchant() int32 {
	if x != nil {
		return x.Merchant
	}
	return 0
}

type UpsertNpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AdminResult            `protobuf:"varint,1,opt,name=result,proto3,enum=web.v1.AdminResult" json:"result,omitempty"`
	NpcId         int64                  `protobuf:"varint,2,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertNpcResponse) Reset() {
	*x = UpsertNpcResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertNpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertNpcResponse) ProtoMessage() {}

func (x *UpsertNpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertNpcResponse.ProtoReflect.Descriptor instead.
func (*UpsertNpcResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{12}
}

func (x *UpsertNpcResponse) GetResult() AdminResult {
	if x != nil {
		return x.Result
	}
	return AdminResult_ADMIN_RESULT_UNSPECIFIED
}

func (x *UpsertNpcResponse) GetNpcId() int64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

type SetNpcVisibilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId   int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	NpcId         int64                  `protobuf:"varint,2,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNpcVisibilityRequest) Reset() {
	*x = SetNpcVisibilityRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNpcVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNpcVisibilityRequest) ProtoMessage() {}

func (x *SetNpcVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNpcVisibilityRequest.ProtoReflect.Descriptor instead.
func (*SetNpcVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{13}
}

func (x *SetNpcVisibilityRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

func (x *SetNpcVisibilityRequest) GetNpcId() int64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *SetNpcVisibilityRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type SetNpcShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId   int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	NpcId         int64                  `protobuf:"varint,2,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	Items         []*AdminNpcShopItem    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetNpcShopRequest) Reset() {
	*x = SetNpcShopRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetNpcShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetNpcShopRequest) ProtoMessage() {}

func (x *SetNpcShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetNpcShopRequest.ProtoReflect.Descriptor instead.
func (*SetNpcShopRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{14}
}

func (x *SetNpcShopRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

func (x *SetNpcShopRequest) GetNpcId() int64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

func (x *SetNpcShopRequest) GetItems() []*AdminNpcShopItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SetItemPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId   int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	ItemIndex     int32                  `protobuf:"varint,2,opt,name=item_index,json=itemIndex,proto3" json:"item_index,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"` // < 0 clears the override
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetItemPriceRequest) Reset() {
	*x = SetItemPriceRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetItemPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItemPriceRequest) ProtoMessage() {}

func (x *SetItemPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItemPriceRequest.ProtoReflect.Descriptor instead.
func (*SetItemPriceRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{15}
}

func (x *SetItemPriceRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

func (x *SetItemPriceRequest) GetItemIndex() int32 {
	if x != nil {
		return x.ItemIndex
	}
	return 0
}

func (x *SetItemPriceRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type DeleteNpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId   int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	NpcId         int64                  `protobuf:"varint,2,opt,name=npc_id,json=npcId,proto3" json:"npc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNpcRequest) Reset() {
	*x = DeleteNpcRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNpcRequest) ProtoMessage() {}

func (x *DeleteNpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNpcRequest.ProtoReflect.Descriptor instead.
func (*DeleteNpcRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteNpcRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

func (x *DeleteNpcRequest) GetNpcId() int64 {
	if x != nil {
		return x.NpcId
	}
	return 0
}

// MerchantTemplate is one merchant-type STRUCT_MOB template found under
// Release/TMsrv/run/npc/.
type MerchantTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateName  string                 `protobuf:"bytes,1,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"` // exact value for UpsertNpc.template_name (no .txt)
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`    // the template's mob.Name, for the picker UI
	Merchant      int32                  `protobuf:"varint,3,opt,name=merchant,proto3" json:"merchant,omitempty"`                            // CurrentScore.Merchant (1, 2, 19, 100, …)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantTemplate) Reset() {
	*x = MerchantTemplate{}
	mi := &file_api_web_v1_web_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantTemplate) ProtoMessage() {}

func (x *MerchantTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantTemplate.ProtoReflect.Descriptor instead.
func (*MerchantTemplate) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{17}
}

func (x *MerchantTemplate) GetTemplateName() string {
	if x != nil {
		return x.TemplateName
	}
	return ""
}

func (x *MerchantTemplate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MerchantTemplate) GetMerchant() int32 {
	if x != nil {
		return x.Merchant
	}
	return 0
}

type ListMerchantTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId   int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantTemplatesRequest) Reset() {
	*x = ListMerchantTemplatesRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantTemplatesRequest) ProtoMessage() {}

func (x *ListMerchantTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListMerchantTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{18}
}

func (x *ListMerchantTemplatesRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

type ListMerchantTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AdminResult            `protobuf:"varint,1,opt,name=result,proto3,enum=web.v1.AdminResult" json:"result,omitempty"`
	Templates     []*MerchantTemplate    `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMerchantTemplatesResponse) Reset() {
	*x = ListMerchantTemplatesResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMerchantTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMerchantTemplatesResponse) ProtoMessage() {}

func (x *ListMerchantTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMerchantTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListMerchantTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{19}
}

func (x *ListMerchantTemplatesResponse) GetResult() AdminResult {
	if x != nil {
		return x.Result
	}
	return AdminResult_ADMIN_RESULT_UNSPECIFIED
}

func (x *ListMerchantTemplatesResponse) GetTemplates() []*MerchantTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

// ItemCatalogEntry is one row of Release/Common/ItemList.csv, trimmed to what
// the shop-item picker needs (the full row also carries price/effects, not
// relevant here — see tmserver/internal/content.ItemEntry for that).
type ItemCatalogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIndex     int32                  `protobuf:"varint,1,opt,name=item_index,json=itemIndex,proto3" json:"item_index,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemCatalogEntry) Reset() {
	*x = ItemCatalogEntry{}
	mi := &file_api_web_v1_web_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemCatalogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemCatalogEntry) ProtoMessage() {}

func (x *ItemCatalogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemCatalogEntry.ProtoReflect.Descriptor instead.
func (*ItemCatalogEntry) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{20}
}

func (x *ItemCatalogEntry) GetItemIndex() int32 {
	if x != nil {
		return x.ItemIndex
	}
	return 0
}

func (x *ItemCatalogEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListItemCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId   int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemCatalogRequest) Reset() {
	*x = ListItemCatalogRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemCatalogRequest) ProtoMessage() {}

func (x *ListItemCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemCatalogRequest.ProtoReflect.Descriptor instead.
func (*ListItemCatalogRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{21}
}

func (x *ListItemCatalogRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

type ListItemCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AdminResult            `protobuf:"varint,1,opt,name=result,proto3,enum=web.v1.AdminResult" json:"result,omitempty"`
	Items         []*ItemCatalogEntry    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemCatalogResponse) Reset() {
	*x = ListItemCatalogResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemCatalogResponse) ProtoMessage() {}

func (x *ListItemCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemCatalogResponse.ProtoReflect.Descriptor instead.
func (*ListItemCatalogResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{22}
}

func (x *ListItemCatalogResponse) GetResult() AdminResult {
	if x != nil {
		return x.Result
	}
	return AdminResult_ADMIN_RESULT_UNSPECIFIED
}

func (x *ListItemCatalogResponse) GetItems() []*ItemCatalogEntry {
	if x != nil {
		return x.Items
	}
	return nil
}

// MapZone is one of the fixed city zones (tmserver/internal/world/city.go's
// cities table). Label only, for the map_id picker — the world runs a single
// grid, so map_id itself has no gameplay effect today.
type MapZone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapZone) Reset() {
	*x = MapZone{}
	mi := &file_api_web_v1_web_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapZone) ProtoMessage() {}

func (x *MapZone) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapZone.ProtoReflect.Descriptor instead.
func (*MapZone) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{23}
}

func (x *MapZone) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MapZone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListMapZonesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModeratorId   int64                  `protobuf:"varint,1,opt,name=moderator_id,json=moderatorId,proto3" json:"moderator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMapZonesRequest) Reset() {
	*x = ListMapZonesRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMapZonesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMapZonesRequest) ProtoMessage() {}

func (x *ListMapZonesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMapZonesRequest.ProtoReflect.Descriptor instead.
func (*ListMapZonesRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{24}
}

func (x *ListMapZonesRequest) GetModeratorId() int64 {
	if x != nil {
		return x.ModeratorId
	}
	return 0
}

type ListMapZonesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        AdminResult            `protobuf:"varint,1,opt,name=result,proto3,enum=web.v1.AdminResult" json:"result,omitempty"`
	Zones         []*MapZone             `protobuf:"bytes,2,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMapZonesResponse) Reset() {
	*x = ListMapZonesResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMapZonesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMapZonesResponse) ProtoMessage() {}

func (x *ListMapZonesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMapZonesResponse.ProtoReflect.Descriptor instead.
func (*ListMapZonesResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{25}
}

func (x *ListMapZonesResponse) GetResult() AdminResult {
	if x != nil {
		return x.Result
	}
	return AdminResult_ADMIN_RESULT_UNSPECIFIED
}

func (x *ListMapZonesResponse) GetZones() []*MapZone {
	if x != nil {
		return x.Zones
	}
	return nil
}

var File_api_web_v1_web_proto protoreflect.FileDescriptor

const file_api_web_v1_web_proto_rawDesc = "" +
	"\n" +
	"\x14api/web/v1/web.proto\x12\x06web.v1\"\\\n" +
	"\x14CreateAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"d\n" +
	"\x15CreateAccountResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\x0e2\x14.web.v1.CreateResultR\x06result\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"J\n" +
	"\x18VerifyCredentialsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"x\n" +
	"\x19VerifyCredentialsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x18\n" +
	"\ablocked\x18\x03 \x01(\bR\ablocked\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"7\n" +
	"\bAdminAck\x12+\n" +
	"\x06result\x18\x01 \x01(\x0e2\x13.web.v1.AdminResultR\x06result\"\xdf\x01\n" +
	"\x10AdminNpcShopItem\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x1d\n" +
	"\n" +
	"item_index\x18\x02 \x01(\x05R\titemIndex\x12\x12\n" +
	"\x04eff1\x18\x03 \x01(\x05R\x04eff1\x12\x14\n" +
	"\x05effv1\x18\x04 \x01(\x05R\x05effv1\x12\x12\n" +
	"\x04eff2\x18\x05 \x01(\x05R\x04eff2\x12\x14\n" +
	"\x05effv2\x18\x06 \x01(\x05R\x05effv2\x12\x12\n" +
	"\x04eff3\x18\a \x01(\x05R\x04eff3\x12\x14\n" +
	"\x05effv3\x18\b \x01(\x05R\x05effv3\x12\x1a\n" +
	"\bquantity\x18\t \x01(\x05R\bquantity\"\xba\x02\n" +
	"\bAdminNpc\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x15\n" +
	"\x06map_id\x18\x06 \x01(\x05R\x05mapId\x12\x13\n" +
	"\x05pos_x\x18\a \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\b \x01(\x05R\x04posY\x12\x1d\n" +
	"\n" +
	"route_type\x18\t \x01(\x05R\trouteType\x12\x1a\n" +
	"\bmerchant\x18\n" +
	" \x01(\x05R\bmerchant\x12,\n" +
	"\x04shop\x18\v \x03(\v2\x18.web.v1.AdminNpcShopItemR\x04shop\"4\n" +
	"\x0fListNpcsRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\"e\n" +
	"\x10ListNpcsResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\x0e2\x13.web.v1.AdminResultR\x06result\x12$\n" +
	"\x04npcs\x18\x02 \x03(\v2\x10.web.v1.AdminNpcR\x04npcs\"I\n" +
	"\rGetNpcRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\x12\x15\n" +
	"\x06npc_id\x18\x02 \x01(\x03R\x05npcId\"a\n" +
	"\x0eGetNpcResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\x0e2\x13.web.v1.AdminResultR\x06result\x12\"\n" +
	"\x03npc\x18\x02 \x01(\v2\x10.web.v1.AdminNpcR\x03npc\"\xa7\x02\n" +
	"\x10UpsertNpcRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12#\n" +
	"\rtemplate_name\x18\x03 \x01(\tR\ftemplateName\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x15\n" +
	"\x06map_id\x18\x06 \x01(\x05R\x05mapId\x12\x13\n" +
	"\x05pos_x\x18\a \x01(\x05R\x04posX\x12\x13\n" +
	"\x05pos_y\x18\b \x01(\x05R\x04posY\x12\x1d\n" +
	"\n" +
	"route_type\x18\t \x01(\x05R\trouteType\x12\x1a\n" +
	"\bmerchant\x18\n" +
	" \x01(\x05R\bmerchant\"W\n" +
	"\x11UpsertNpcResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\x0e2\x13.web.v1.AdminResultR\x06result\x12\x15\n" +
	"\x06npc_id\x18\x02 \x01(\x03R\x05npcId\"m\n" +
	"\x17SetNpcVisibilityRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\x12\x15\n" +
	"\x06npc_id\x18\x02 \x01(\x03R\x05npcId\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"}\n" +
	"\x11SetNpcShopRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\x12\x15\n" +
	"\x06npc_id\x18\x02 \x01(\x03R\x05npcId\x12.\n" +
	"\x05items\x18\x03 \x03(\v2\x18.web.v1.AdminNpcShopItemR\x05items\"m\n" +
	"\x13SetItemPriceRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\x12\x1d\n" +
	"\n" +
	"item_index\x18\x02 \x01(\x05R\titemIndex\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"L\n" +
	"\x10DeleteNpcRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\x12\x15\n" +
	"\x06npc_id\x18\x02 \x01(\x03R\x05npcId\"v\n" +
	"\x10MerchantTemplate\x12#\n" +
	"\rtemplate_name\x18\x01 \x01(\tR\ftemplateName\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bmerchant\x18\x03 \x01(\x05R\bmerchant\"A\n" +
	"\x1cListMerchantTemplatesRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\"\x84\x01\n" +
	"\x1dListMerchantTemplatesResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\x0e2\x13.web.v1.AdminResultR\x06result\x126\n" +
	"\ttemplates\x18\x02 \x03(\v2\x18.web.v1.MerchantTemplateR\ttemplates\"E\n" +
	"\x10ItemCatalogEntry\x12\x1d\n" +
	"\n" +
	"item_index\x18\x01 \x01(\x05R\titemIndex\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\";\n" +
	"\x16ListItemCatalogRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\"v\n" +
	"\x17ListItemCatalogResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\x0e2\x13.web.v1.AdminResultR\x06result\x12.\n" +
	"\x05items\x18\x02 \x03(\v2\x18.web.v1.ItemCatalogEntryR\x05items\"-\n" +
	"\aMapZone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"8\n" +
	"\x13ListMapZonesRequest\x12!\n" +
	"\fmoderator_id\x18\x01 \x01(\x03R\vmoderatorId\"j\n" +
	"\x14ListMapZonesResponse\x12+\n" +
	"\x06result\x18\x01 \x01(\x0e2\x13.web.v1.AdminResultR\x06result\x12%\n" +
	"\x05zones\x18\x02 \x03(\v2\x0f.web.v1.MapZoneR\x05zones*|\n" +
	"\fCreateResult\x12\x1d\n" +
	"\x19CREATE_RESULT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CREATE_RESULT_OK\x10\x01\x12\x1c\n" +
	"\x18CREATE_RESULT_NAME_TAKEN\x10\x02\x12\x19\n" +
	"\x15CREATE_RESULT_INVALID\x10\x03*\x92\x01\n" +
	"\vAdminResult\x12\x1c\n" +
	"\x18ADMIN_RESULT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fADMIN_RESULT_OK\x10\x01\x12\x1a\n" +
	"\x16ADMIN_RESULT_FORBIDDEN\x10\x02\x12\x18\n" +
	"\x14ADMIN_RESULT_INVALID\x10\x03\x12\x1a\n" +
	"\x16ADMIN_RESULT_NOT_FOUND\x10\x042\xbb\x01\n" +
	"\x11AccountWebService\x12L\n" +
	"\rCreateAccount\x12\x1c.web.v1.CreateAccountRequest\x1a\x1d.web.v1.CreateAccountResponse\x12X\n" +
	"\x11VerifyCredentials\x12 .web.v1.VerifyCredentialsRequest\x1a!.web.v1.VerifyCredentialsResponse2\xca\x05\n" +
	"\x0fNpcAdminService\x12=\n" +
	"\bListNpcs\x12\x17.web.v1.ListNpcsRequest\x1a\x18.web.v1.ListNpcsResponse\x127\n" +
	"\x06GetNpc\x12\x15.web.v1.GetNpcRequest\x1a\x16.web.v1.GetNpcResponse\x12@\n" +
	"\tUpsertNpc\x12\x18.web.v1.UpsertNpcRequest\x1a\x19.web.v1.UpsertNpcResponse\x12E\n" +
	"\x10SetNpcVisibility\x12\x1f.web.v1.SetNpcVisibilityRequest\x1a\x10.web.v1.AdminAck\x129\n" +
	"\n" +
	"SetNpcShop\x12\x19.web.v1.SetNpcShopRequest\x1a\x10.web.v1.AdminAck\x12=\n" +
	"\fSetItemPrice\x12\x1b.web.v1.SetItemPriceRequest\x1a\x10.web.v1.AdminAck\x127\n" +
	"\tDeleteNpc\x12\x18.web.v1.DeleteNpcRequest\x1a\x10.web.v1.AdminAck\x12d\n" +
	"\x15ListMerchantTemplates\x12$.web.v1.ListMerchantTemplatesRequest\x1a%.web.v1.ListMerchantTemplatesResponse\x12R\n" +
	"\x0fListItemCatalog\x12\x1e.web.v1.ListItemCatalogRequest\x1a\x1f.web.v1.ListItemCatalogResponse\x12I\n" +
	"\fListMapZones\x12\x1b.web.v1.ListMapZonesRequest\x1a\x1c.web.v1.ListMapZonesResponseB3Z1github.com/jeanluca/w2pp-openwyd/api/web/v1;webv1b\x06proto3"

var (
	file_api_web_v1_web_proto_rawDescOnce sync.Once
	file_api_web_v1_web_proto_rawDescData []byte
)

func file_api_web_v1_web_proto_rawDescGZIP() []byte {
	file_api_web_v1_web_proto_rawDescOnce.Do(func() {
		file_api_web_v1_web_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_web_v1_web_proto_rawDesc), len(file_api_web_v1_web_proto_rawDesc)))
	})
	return file_api_web_v1_web_proto_rawDescData
}

var file_api_web_v1_web_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_web_v1_web_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_web_v1_web_proto_goTypes = []any{
	(CreateResult)(0),                     // 0: web.v1.CreateResult
	(AdminResult)(0),                      // 1: web.v1.AdminResult
	(*CreateAccountRequest)(nil),          // 2: web.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),         // 3: web.v1.CreateAccountResponse
	(*VerifyCredentialsRequest)(nil),      // 4: web.v1.VerifyCredentialsRequest
	(*VerifyCredentialsResponse)(nil),     // 5: web.v1.VerifyCredentialsResponse
	(*AdminAck)(nil),                      // 6: web.v1.AdminAck
	(*AdminNpcShopItem)(nil),              // 7: web.v1.AdminNpcShopItem
	(*AdminNpc)(nil),                      // 8: web.v1.AdminNpc
	(*ListNpcsRequest)(nil),               // 9: web.v1.ListNpcsRequest
	(*ListNpcsResponse)(nil),              // 10: web.v1.ListNpcsResponse
	(*GetNpcRequest)(nil),                 // 11: web.v1.GetNpcRequest
	(*GetNpcResponse)(nil),                // 12: web.v1.GetNpcResponse
	(*UpsertNpcRequest)(nil),              // 13: web.v1.UpsertNpcRequest
	(*UpsertNpcResponse)(nil),             // 14: web.v1.UpsertNpcResponse
	(*SetNpcVisibilityRequest)(nil),       // 15: web.v1.SetNpcVisibilityRequest
	(*SetNpcShopRequest)(nil),             // 16: web.v1.SetNpcShopRequest
	(*SetItemPriceRequest)(nil),           // 17: web.v1.SetItemPriceRequest
	(*DeleteNpcRequest)(nil),              // 18: web.v1.DeleteNpcRequest
	(*MerchantTemplate)(nil),              // 19: web.v1.MerchantTemplate
	(*ListMerchantTemplatesRequest)(nil),  // 20: web.v1.ListMerchantTemplatesRequest
	(*ListMerchantTemplatesResponse)(nil), // 21: web.v1.ListMerchantTemplatesResponse
	(*ItemCatalogEntry)(nil),              // 22: web.v1.ItemCatalogEntry
	(*ListItemCatalogRequest)(nil),        // 23: web.v1.ListItemCatalogRequest
	(*ListItemCatalogResponse)(nil),       // 24: web.v1.ListItemCatalogResponse
	(*MapZone)(nil),                       // 25: web.v1.MapZone
	(*ListMapZonesRequest)(nil),           // 26: web.v1.ListMapZonesRequest
	(*ListMapZonesResponse)(nil),          // 27: web.v1.ListMapZonesResponse
}
var file_api_web_v1_web_proto_depIdxs = []int32{
	0,  // 0: web.v1.CreateAccountResponse.result:type_name -> web.v1.CreateResult
	1,  // 1: web.v1.AdminAck.result:type_name -> web.v1.AdminResult
	7,  // 2: web.v1.AdminNpc.shop:type_name -> web.v1.AdminNpcShopItem
	1,  // 3: web.v1.ListNpcsResponse.result:type_name -> web.v1.AdminResult
	8,  // 4: web.v1.ListNpcsResponse.npcs:type_name -> web.v1.AdminNpc
	1,  // 5: web.v1.GetNpcResponse.result:type_name -> web.v1.AdminResult
	8,  // 6: web.v1.GetNpcResponse.npc:type_name -> web.v1.AdminNpc
	1,  // 7: web.v1.UpsertNpcResponse.result:type_name -> web.v1.AdminResult
	7,  // 8: web.v1.SetNpcShopRequest.items:type_name -> web.v1.AdminNpcShopItem
	1,  // 9: web.v1.ListMerchantTemplatesResponse.result:type_name -> web.v1.AdminResult
	19, // 10: web.v1.ListMerchantTemplatesResponse.templates:type_name -> web.v1.MerchantTemplate
	1,  // 11: web.v1.ListItemCatalogResponse.result:type_name -> web.v1.AdminResult
	22, // 12: web.v1.ListItemCatalogResponse.items:type_name -> web.v1.ItemCatalogEntry
	1,  // 13: web.v1.ListMapZonesResponse.result:type_name -> web.v1.AdminResult
	25, // 14: web.v1.ListMapZonesResponse.zones:type_name -> web.v1.MapZone
	2,  // 15: web.v1.AccountWebService.CreateAccount:input_type -> web.v1.CreateAccountRequest
	4,  // 16: web.v1.AccountWebService.VerifyCredentials:input_type -> web.v1.VerifyCredentialsRequest
	9,  // 17: web.v1.NpcAdminService.ListNpcs:input_type -> web.v1.ListNpcsRequest
	11, // 18: web.v1.NpcAdminService.GetNpc:input_type -> web.v1.GetNpcRequest
	13, // 19: web.v1.NpcAdminService.UpsertNpc:input_type -> web.v1.UpsertNpcRequest
	15, // 20: web.v1.NpcAdminService.SetNpcVisibility:input_type -> web.v1.SetNpcVisibilityRequest
	16, // 21: web.v1.NpcAdminService.SetNpcShop:input_type -> web.v1.SetNpcShopRequest
	17, // 22: web.v1.NpcAdminService.SetItemPrice:input_type -> web.v1.SetItemPriceRequest
	18, // 23: web.v1.NpcAdminService.DeleteNpc:input_type -> web.v1.DeleteNpcRequest
	20, // 24: web.v1.NpcAdminService.ListMerchantTemplates:input_type -> web.v1.ListMerchantTemplatesRequest
	23, // 25: web.v1.NpcAdminService.ListItemCatalog:input_type -> web.v1.ListItemCatalogRequest
	26, // 26: web.v1.NpcAdminService.ListMapZones:input_type -> web.v1.ListMapZonesRequest
	3,  // 27: web.v1.AccountWebService.CreateAccount:output_type -> web.v1.CreateAccountResponse
	5,  // 28: web.v1.AccountWebService.VerifyCredentials:output_type -> web.v1.VerifyCredentialsResponse
	10, // 29: web.v1.NpcAdminService.ListNpcs:output_type -> web.v1.ListNpcsResponse
	12, // 30: web.v1.NpcAdminService.GetNpc:output_type -> web.v1.GetNpcResponse
	14, // 31: web.v1.NpcAdminService.UpsertNpc:output_type -> web.v1.UpsertNpcResponse
	6,  // 32: web.v1.NpcAdminService.SetNpcVisibility:output_type -> web.v1.AdminAck
	6,  // 33: web.v1.NpcAdminService.SetNpcShop:output_type -> web.v1.AdminAck
	6,  // 34: web.v1.NpcAdminService.SetItemPrice:output_type -> web.v1.AdminAck
	6,  // 35: web.v1.NpcAdminService.DeleteNpc:output_type -> web.v1.AdminAck
	21, // 36: web.v1.NpcAdminService.ListMerchantTemplates:output_type -> web.v1.ListMerchantTemplatesResponse
	24, // 37: web.v1.NpcAdminService.ListItemCatalog:output_type -> web.v1.ListItemCatalogResponse
	27, // 38: web.v1.NpcAdminService.ListMapZones:output_type -> web.v1.ListMapZonesResponse
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_api_web_v1_web_proto_init() }
func file_api_web_v1_web_proto_init() {
	if File_api_web_v1_web_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_web_v1_web_proto_rawDesc), len(file_api_web_v1_web_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_web_v1_web_proto_goTypes,
		DependencyIndexes: file_api_web_v1_web_proto_depIdxs,
		EnumInfos:         file_api_web_v1_web_proto_enumTypes,
		MessageInfos:      file_api_web_v1_web_proto_msgTypes,
	}.Build()
	File_api_web_v1_web_proto = out.File
	file_api_web_v1_web_proto_goTypes = nil
	file_api_web_v1_web_proto_depIdxs = nil
}
