// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/web/v1/web.proto

// web-api contract — DESIGNED FROM SCRATCH (web-platform-plan.md). This is the
// edge the Next.js BFF (Route Handlers / Server Actions) calls server-side over
// gRPC + mTLS; the browser never speaks gRPC. It is SEPARATE from the legacy
// CPSock game login and from dbServer's AccountService (api/db/v1), which
// mirrors the legacy G↔DB messages. web-api reuses the same `account` table and
// argon2id hashing underneath, but exposes its own web-facing surface.
//
// Generate with `make proto` (protoc + protoc-gen-go/-grpc).

package webv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateResult is the outcome of a sign-up. Business outcomes (name taken,
// invalid input) are carried here, not as gRPC error codes — only infra
// failures surface as errors.
type CreateResult int32

const (
	CreateResult_CREATE_RESULT_UNSPECIFIED CreateResult = 0
	CreateResult_CREATE_RESULT_OK          CreateResult = 1 // account created; account_id is set
	CreateResult_CREATE_RESULT_NAME_TAKEN  CreateResult = 2 // canonical name already exists
	CreateResult_CREATE_RESULT_INVALID     CreateResult = 3 // name/password/email failed validation
)

// Enum value maps for CreateResult.
var (
	CreateResult_name = map[int32]string{
		0: "CREATE_RESULT_UNSPECIFIED",
		1: "CREATE_RESULT_OK",
		2: "CREATE_RESULT_NAME_TAKEN",
		3: "CREATE_RESULT_INVALID",
	}
	CreateResult_value = map[string]int32{
		"CREATE_RESULT_UNSPECIFIED": 0,
		"CREATE_RESULT_OK":          1,
		"CREATE_RESULT_NAME_TAKEN":  2,
		"CREATE_RESULT_INVALID":     3,
	}
)

func (x CreateResult) Enum() *CreateResult {
	p := new(CreateResult)
	*p = x
	return p
}

func (x CreateResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateResult) Descriptor() protoreflect.EnumDescriptor {
	return file_api_web_v1_web_proto_enumTypes[0].Descriptor()
}

func (CreateResult) Type() protoreflect.EnumType {
	return &file_api_web_v1_web_proto_enumTypes[0]
}

func (x CreateResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateResult.Descriptor instead.
func (CreateResult) EnumDescriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{0}
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // canonicalized to lowercase server-side
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // plaintext over the mTLS link; hashed before storage
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`       // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        CreateResult           `protobuf:"varint,1,opt,name=result,proto3,enum=web.v1.CreateResult" json:"result,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // set only when result is CREATE_RESULT_OK
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetResult() CreateResult {
	if x != nil {
		return x.Result
	}
	return CreateResult_CREATE_RESULT_UNSPECIFIED
}

func (x *CreateAccountResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type VerifyCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialsRequest) Reset() {
	*x = VerifyCredentialsRequest{}
	mi := &file_api_web_v1_web_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialsRequest) ProtoMessage() {}

func (x *VerifyCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialsRequest.ProtoReflect.Descriptor instead.
func (*VerifyCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCredentialsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VerifyCredentialsRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                // name exists and password matches
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"` // set only when ok
	Blocked       bool                   `protobuf:"varint,3,opt,name=blocked,proto3" json:"blocked,omitempty"`                      // account.is_blocked — caller decides how to surface it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialsResponse) Reset() {
	*x = VerifyCredentialsResponse{}
	mi := &file_api_web_v1_web_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialsResponse) ProtoMessage() {}

func (x *VerifyCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_web_v1_web_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialsResponse.ProtoReflect.Descriptor instead.
func (*VerifyCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_api_web_v1_web_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCredentialsResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *VerifyCredentialsResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *VerifyCredentialsResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

var File_api_web_v1_web_proto protoreflect.FileDescriptor

const file_api_web_v1_web_proto_rawDesc = "" +
	"\n" +
	"\x14api/web/v1/web.proto\x12\x06web.v1\"\\\n" +
	"\x14CreateAccountRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"d\n" +
	"\x15CreateAccountResponse\x12,\n" +
	"\x06result\x18\x01 \x01(\x0e2\x14.web.v1.CreateResultR\x06result\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"J\n" +
	"\x18VerifyCredentialsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"d\n" +
	"\x19VerifyCredentialsResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\x12\x18\n" +
	"\ablocked\x18\x03 \x01(\bR\ablocked*|\n" +
	"\fCreateResult\x12\x1d\n" +
	"\x19CREATE_RESULT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10CREATE_RESULT_OK\x10\x01\x12\x1c\n" +
	"\x18CREATE_RESULT_NAME_TAKEN\x10\x02\x12\x19\n" +
	"\x15CREATE_RESULT_INVALID\x10\x032\xbb\x01\n" +
	"\x11AccountWebService\x12L\n" +
	"\rCreateAccount\x12\x1c.web.v1.CreateAccountRequest\x1a\x1d.web.v1.CreateAccountResponse\x12X\n" +
	"\x11VerifyCredentials\x12 .web.v1.VerifyCredentialsRequest\x1a!.web.v1.VerifyCredentialsResponseB3Z1github.com/jeanluca/w2pp-openwyd/api/web/v1;webv1b\x06proto3"

var (
	file_api_web_v1_web_proto_rawDescOnce sync.Once
	file_api_web_v1_web_proto_rawDescData []byte
)

func file_api_web_v1_web_proto_rawDescGZIP() []byte {
	file_api_web_v1_web_proto_rawDescOnce.Do(func() {
		file_api_web_v1_web_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_web_v1_web_proto_rawDesc), len(file_api_web_v1_web_proto_rawDesc)))
	})
	return file_api_web_v1_web_proto_rawDescData
}

var file_api_web_v1_web_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_web_v1_web_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_web_v1_web_proto_goTypes = []any{
	(CreateResult)(0),                 // 0: web.v1.CreateResult
	(*CreateAccountRequest)(nil),      // 1: web.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),     // 2: web.v1.CreateAccountResponse
	(*VerifyCredentialsRequest)(nil),  // 3: web.v1.VerifyCredentialsRequest
	(*VerifyCredentialsResponse)(nil), // 4: web.v1.VerifyCredentialsResponse
}
var file_api_web_v1_web_proto_depIdxs = []int32{
	0, // 0: web.v1.CreateAccountResponse.result:type_name -> web.v1.CreateResult
	1, // 1: web.v1.AccountWebService.CreateAccount:input_type -> web.v1.CreateAccountRequest
	3, // 2: web.v1.AccountWebService.VerifyCredentials:input_type -> web.v1.VerifyCredentialsRequest
	2, // 3: web.v1.AccountWebService.CreateAccount:output_type -> web.v1.CreateAccountResponse
	4, // 4: web.v1.AccountWebService.VerifyCredentials:output_type -> web.v1.VerifyCredentialsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_web_v1_web_proto_init() }
func file_api_web_v1_web_proto_init() {
	if File_api_web_v1_web_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_web_v1_web_proto_rawDesc), len(file_api_web_v1_web_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_web_v1_web_proto_goTypes,
		DependencyIndexes: file_api_web_v1_web_proto_depIdxs,
		EnumInfos:         file_api_web_v1_web_proto_enumTypes,
		MessageInfos:      file_api_web_v1_web_proto_msgTypes,
	}.Build()
	File_api_web_v1_web_proto = out.File
	file_api_web_v1_web_proto_goTypes = nil
	file_api_web_v1_web_proto_depIdxs = nil
}
