// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/web/v1/web.proto

// web-api contract — DESIGNED FROM SCRATCH (web-platform-plan.md). This is the
// edge the Next.js BFF (Route Handlers / Server Actions) calls server-side over
// gRPC + mTLS; the browser never speaks gRPC. It is SEPARATE from the legacy
// CPSock game login and from dbServer's AccountService (api/db/v1), which
// mirrors the legacy G↔DB messages. web-api reuses the same `account` table and
// argon2id hashing underneath, but exposes its own web-facing surface.
//
// Generate with `make proto` (protoc + protoc-gen-go/-grpc).

package webv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountWebService_CreateAccount_FullMethodName     = "/web.v1.AccountWebService/CreateAccount"
	AccountWebService_VerifyCredentials_FullMethodName = "/web.v1.AccountWebService/VerifyCredentials"
)

// AccountWebServiceClient is the client API for AccountWebService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountWebService owns the web platform's account flows (sign-up, credential
// check for the BFF session cookie). Game state is never written here — that
// stays in tmServer's single-owner loop (web-platform-plan.md).
type AccountWebServiceClient interface {
	// CreateAccount registers a new web/game account (argon2id-hashed password).
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// VerifyCredentials validates name + password so the BFF can mint a session
	// cookie. It is the web login path, independent of the CPSock game login.
	VerifyCredentials(ctx context.Context, in *VerifyCredentialsRequest, opts ...grpc.CallOption) (*VerifyCredentialsResponse, error)
}

type accountWebServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountWebServiceClient(cc grpc.ClientConnInterface) AccountWebServiceClient {
	return &accountWebServiceClient{cc}
}

func (c *accountWebServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, AccountWebService_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountWebServiceClient) VerifyCredentials(ctx context.Context, in *VerifyCredentialsRequest, opts ...grpc.CallOption) (*VerifyCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCredentialsResponse)
	err := c.cc.Invoke(ctx, AccountWebService_VerifyCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountWebServiceServer is the server API for AccountWebService service.
// All implementations must embed UnimplementedAccountWebServiceServer
// for forward compatibility.
//
// AccountWebService owns the web platform's account flows (sign-up, credential
// check for the BFF session cookie). Game state is never written here — that
// stays in tmServer's single-owner loop (web-platform-plan.md).
type AccountWebServiceServer interface {
	// CreateAccount registers a new web/game account (argon2id-hashed password).
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// VerifyCredentials validates name + password so the BFF can mint a session
	// cookie. It is the web login path, independent of the CPSock game login.
	VerifyCredentials(context.Context, *VerifyCredentialsRequest) (*VerifyCredentialsResponse, error)
	mustEmbedUnimplementedAccountWebServiceServer()
}

// UnimplementedAccountWebServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountWebServiceServer struct{}

func (UnimplementedAccountWebServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedAccountWebServiceServer) VerifyCredentials(context.Context, *VerifyCredentialsRequest) (*VerifyCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCredentials not implemented")
}
func (UnimplementedAccountWebServiceServer) mustEmbedUnimplementedAccountWebServiceServer() {}
func (UnimplementedAccountWebServiceServer) testEmbeddedByValue()                           {}

// UnsafeAccountWebServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountWebServiceServer will
// result in compilation errors.
type UnsafeAccountWebServiceServer interface {
	mustEmbedUnimplementedAccountWebServiceServer()
}

func RegisterAccountWebServiceServer(s grpc.ServiceRegistrar, srv AccountWebServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountWebServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountWebService_ServiceDesc, srv)
}

func _AccountWebService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountWebServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountWebService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountWebServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountWebService_VerifyCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountWebServiceServer).VerifyCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountWebService_VerifyCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountWebServiceServer).VerifyCredentials(ctx, req.(*VerifyCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountWebService_ServiceDesc is the grpc.ServiceDesc for AccountWebService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountWebService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.AccountWebService",
	HandlerType: (*AccountWebServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountWebService_CreateAccount_Handler,
		},
		{
			MethodName: "VerifyCredentials",
			Handler:    _AccountWebService_VerifyCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}

const (
	NpcAdminService_ListNpcs_FullMethodName              = "/web.v1.NpcAdminService/ListNpcs"
	NpcAdminService_GetNpc_FullMethodName                = "/web.v1.NpcAdminService/GetNpc"
	NpcAdminService_UpsertNpc_FullMethodName             = "/web.v1.NpcAdminService/UpsertNpc"
	NpcAdminService_SetNpcVisibility_FullMethodName      = "/web.v1.NpcAdminService/SetNpcVisibility"
	NpcAdminService_SetNpcShop_FullMethodName            = "/web.v1.NpcAdminService/SetNpcShop"
	NpcAdminService_SetItemPrice_FullMethodName          = "/web.v1.NpcAdminService/SetItemPrice"
	NpcAdminService_DeleteNpc_FullMethodName             = "/web.v1.NpcAdminService/DeleteNpc"
	NpcAdminService_ListMerchantTemplates_FullMethodName = "/web.v1.NpcAdminService/ListMerchantTemplates"
	NpcAdminService_ListItemCatalog_FullMethodName       = "/web.v1.NpcAdminService/ListItemCatalog"
	NpcAdminService_ListMapZones_FullMethodName          = "/web.v1.NpcAdminService/ListMapZones"
)

// NpcAdminServiceClient is the client API for NpcAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NpcAdminService is the moderator-facing NPC editing surface (npc-editing-plan.md).
// The Next.js BFF calls it server-side after establishing a moderator session;
// every request carries the moderator's account_id, which the web-api authorizes
// against account.role ('moderator'/'admin') and records in the audit trail. All
// writes are cold config in Postgres — never live game state, which stays in
// tmServer's single-owner loop.
type NpcAdminServiceClient interface {
	// ListNpcs returns every NPC definition (moderation table).
	ListNpcs(ctx context.Context, in *ListNpcsRequest, opts ...grpc.CallOption) (*ListNpcsResponse, error)
	// GetNpc returns one definition with its shop stock.
	GetNpc(ctx context.Context, in *GetNpcRequest, opts ...grpc.CallOption) (*GetNpcResponse, error)
	// UpsertNpc creates or updates a definition (position, visibility, merchant type).
	UpsertNpc(ctx context.Context, in *UpsertNpcRequest, opts ...grpc.CallOption) (*UpsertNpcResponse, error)
	// SetNpcVisibility toggles whether the NPC appears ("aparece ou não").
	SetNpcVisibility(ctx context.Context, in *SetNpcVisibilityRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// SetNpcShop replaces a merchant NPC's shop stock.
	SetNpcShop(ctx context.Context, in *SetNpcShopRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// SetItemPrice sets (price>=0) or clears (price<0) the GLOBAL price of an item.
	SetItemPrice(ctx context.Context, in *SetItemPriceRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// DeleteNpc removes a definition.
	DeleteNpc(ctx context.Context, in *DeleteNpcRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// ListMerchantTemplates returns the merchant NPC templates found in the
	// content tree (Release/TMsrv/run/npc/, CurrentScore.Merchant != 0), so the
	// moderator UI can offer a searchable picker instead of a free-text
	// template_name field. Scanned once at web-api boot from -content/W2PP_CONTENT;
	// empty when that flag is unset.
	ListMerchantTemplates(ctx context.Context, in *ListMerchantTemplatesRequest, opts ...grpc.CallOption) (*ListMerchantTemplatesResponse, error)
	// ListItemCatalog returns the item catalog (Release/Common/ItemList.csv:
	// item_index, name), so the shop-item editor (SetNpcShop/SetItemPrice) can
	// offer a searchable picker instead of a raw item_index typed by hand.
	// Scanned once at web-api boot from -content/W2PP_CONTENT; empty when unset.
	ListItemCatalog(ctx context.Context, in *ListItemCatalogRequest, opts ...grpc.CallOption) (*ListItemCatalogResponse, error)
	// ListMapZones returns the fixed city-zone table (label only: the world runs
	// a single grid, so map_id has no gameplay effect today) for the NPC form's
	// map picker instead of a raw map_id typed by hand.
	ListMapZones(ctx context.Context, in *ListMapZonesRequest, opts ...grpc.CallOption) (*ListMapZonesResponse, error)
}

type npcAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNpcAdminServiceClient(cc grpc.ClientConnInterface) NpcAdminServiceClient {
	return &npcAdminServiceClient{cc}
}

func (c *npcAdminServiceClient) ListNpcs(ctx context.Context, in *ListNpcsRequest, opts ...grpc.CallOption) (*ListNpcsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNpcsResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_ListNpcs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) GetNpc(ctx context.Context, in *GetNpcRequest, opts ...grpc.CallOption) (*GetNpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNpcResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_GetNpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) UpsertNpc(ctx context.Context, in *UpsertNpcRequest, opts ...grpc.CallOption) (*UpsertNpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertNpcResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_UpsertNpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) SetNpcVisibility(ctx context.Context, in *SetNpcVisibilityRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, NpcAdminService_SetNpcVisibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) SetNpcShop(ctx context.Context, in *SetNpcShopRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, NpcAdminService_SetNpcShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) SetItemPrice(ctx context.Context, in *SetItemPriceRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, NpcAdminService_SetItemPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) DeleteNpc(ctx context.Context, in *DeleteNpcRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, NpcAdminService_DeleteNpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) ListMerchantTemplates(ctx context.Context, in *ListMerchantTemplatesRequest, opts ...grpc.CallOption) (*ListMerchantTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantTemplatesResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_ListMerchantTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) ListItemCatalog(ctx context.Context, in *ListItemCatalogRequest, opts ...grpc.CallOption) (*ListItemCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemCatalogResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_ListItemCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) ListMapZones(ctx context.Context, in *ListMapZonesRequest, opts ...grpc.CallOption) (*ListMapZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMapZonesResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_ListMapZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NpcAdminServiceServer is the server API for NpcAdminService service.
// All implementations must embed UnimplementedNpcAdminServiceServer
// for forward compatibility.
//
// NpcAdminService is the moderator-facing NPC editing surface (npc-editing-plan.md).
// The Next.js BFF calls it server-side after establishing a moderator session;
// every request carries the moderator's account_id, which the web-api authorizes
// against account.role ('moderator'/'admin') and records in the audit trail. All
// writes are cold config in Postgres — never live game state, which stays in
// tmServer's single-owner loop.
type NpcAdminServiceServer interface {
	// ListNpcs returns every NPC definition (moderation table).
	ListNpcs(context.Context, *ListNpcsRequest) (*ListNpcsResponse, error)
	// GetNpc returns one definition with its shop stock.
	GetNpc(context.Context, *GetNpcRequest) (*GetNpcResponse, error)
	// UpsertNpc creates or updates a definition (position, visibility, merchant type).
	UpsertNpc(context.Context, *UpsertNpcRequest) (*UpsertNpcResponse, error)
	// SetNpcVisibility toggles whether the NPC appears ("aparece ou não").
	SetNpcVisibility(context.Context, *SetNpcVisibilityRequest) (*AdminAck, error)
	// SetNpcShop replaces a merchant NPC's shop stock.
	SetNpcShop(context.Context, *SetNpcShopRequest) (*AdminAck, error)
	// SetItemPrice sets (price>=0) or clears (price<0) the GLOBAL price of an item.
	SetItemPrice(context.Context, *SetItemPriceRequest) (*AdminAck, error)
	// DeleteNpc removes a definition.
	DeleteNpc(context.Context, *DeleteNpcRequest) (*AdminAck, error)
	// ListMerchantTemplates returns the merchant NPC templates found in the
	// content tree (Release/TMsrv/run/npc/, CurrentScore.Merchant != 0), so the
	// moderator UI can offer a searchable picker instead of a free-text
	// template_name field. Scanned once at web-api boot from -content/W2PP_CONTENT;
	// empty when that flag is unset.
	ListMerchantTemplates(context.Context, *ListMerchantTemplatesRequest) (*ListMerchantTemplatesResponse, error)
	// ListItemCatalog returns the item catalog (Release/Common/ItemList.csv:
	// item_index, name), so the shop-item editor (SetNpcShop/SetItemPrice) can
	// offer a searchable picker instead of a raw item_index typed by hand.
	// Scanned once at web-api boot from -content/W2PP_CONTENT; empty when unset.
	ListItemCatalog(context.Context, *ListItemCatalogRequest) (*ListItemCatalogResponse, error)
	// ListMapZones returns the fixed city-zone table (label only: the world runs
	// a single grid, so map_id has no gameplay effect today) for the NPC form's
	// map picker instead of a raw map_id typed by hand.
	ListMapZones(context.Context, *ListMapZonesRequest) (*ListMapZonesResponse, error)
	mustEmbedUnimplementedNpcAdminServiceServer()
}

// UnimplementedNpcAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNpcAdminServiceServer struct{}

func (UnimplementedNpcAdminServiceServer) ListNpcs(context.Context, *ListNpcsRequest) (*ListNpcsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNpcs not implemented")
}
func (UnimplementedNpcAdminServiceServer) GetNpc(context.Context, *GetNpcRequest) (*GetNpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNpc not implemented")
}
func (UnimplementedNpcAdminServiceServer) UpsertNpc(context.Context, *UpsertNpcRequest) (*UpsertNpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertNpc not implemented")
}
func (UnimplementedNpcAdminServiceServer) SetNpcVisibility(context.Context, *SetNpcVisibilityRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNpcVisibility not implemented")
}
func (UnimplementedNpcAdminServiceServer) SetNpcShop(context.Context, *SetNpcShopRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNpcShop not implemented")
}
func (UnimplementedNpcAdminServiceServer) SetItemPrice(context.Context, *SetItemPriceRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetItemPrice not implemented")
}
func (UnimplementedNpcAdminServiceServer) DeleteNpc(context.Context, *DeleteNpcRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNpc not implemented")
}
func (UnimplementedNpcAdminServiceServer) ListMerchantTemplates(context.Context, *ListMerchantTemplatesRequest) (*ListMerchantTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMerchantTemplates not implemented")
}
func (UnimplementedNpcAdminServiceServer) ListItemCatalog(context.Context, *ListItemCatalogRequest) (*ListItemCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItemCatalog not implemented")
}
func (UnimplementedNpcAdminServiceServer) ListMapZones(context.Context, *ListMapZonesRequest) (*ListMapZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMapZones not implemented")
}
func (UnimplementedNpcAdminServiceServer) mustEmbedUnimplementedNpcAdminServiceServer() {}
func (UnimplementedNpcAdminServiceServer) testEmbeddedByValue()                         {}

// UnsafeNpcAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NpcAdminServiceServer will
// result in compilation errors.
type UnsafeNpcAdminServiceServer interface {
	mustEmbedUnimplementedNpcAdminServiceServer()
}

func RegisterNpcAdminServiceServer(s grpc.ServiceRegistrar, srv NpcAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedNpcAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NpcAdminService_ServiceDesc, srv)
}

func _NpcAdminService_ListNpcs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNpcsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).ListNpcs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_ListNpcs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).ListNpcs(ctx, req.(*ListNpcsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_GetNpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).GetNpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_GetNpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).GetNpc(ctx, req.(*GetNpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_UpsertNpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertNpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).UpsertNpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_UpsertNpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).UpsertNpc(ctx, req.(*UpsertNpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_SetNpcVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNpcVisibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).SetNpcVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_SetNpcVisibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).SetNpcVisibility(ctx, req.(*SetNpcVisibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_SetNpcShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNpcShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).SetNpcShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_SetNpcShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).SetNpcShop(ctx, req.(*SetNpcShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_SetItemPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).SetItemPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_SetItemPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).SetItemPrice(ctx, req.(*SetItemPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_DeleteNpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).DeleteNpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_DeleteNpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).DeleteNpc(ctx, req.(*DeleteNpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_ListMerchantTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).ListMerchantTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_ListMerchantTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).ListMerchantTemplates(ctx, req.(*ListMerchantTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_ListItemCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).ListItemCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_ListItemCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).ListItemCatalog(ctx, req.(*ListItemCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_ListMapZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMapZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).ListMapZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_ListMapZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).ListMapZones(ctx, req.(*ListMapZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NpcAdminService_ServiceDesc is the grpc.ServiceDesc for NpcAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NpcAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.NpcAdminService",
	HandlerType: (*NpcAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNpcs",
			Handler:    _NpcAdminService_ListNpcs_Handler,
		},
		{
			MethodName: "GetNpc",
			Handler:    _NpcAdminService_GetNpc_Handler,
		},
		{
			MethodName: "UpsertNpc",
			Handler:    _NpcAdminService_UpsertNpc_Handler,
		},
		{
			MethodName: "SetNpcVisibility",
			Handler:    _NpcAdminService_SetNpcVisibility_Handler,
		},
		{
			MethodName: "SetNpcShop",
			Handler:    _NpcAdminService_SetNpcShop_Handler,
		},
		{
			MethodName: "SetItemPrice",
			Handler:    _NpcAdminService_SetItemPrice_Handler,
		},
		{
			MethodName: "DeleteNpc",
			Handler:    _NpcAdminService_DeleteNpc_Handler,
		},
		{
			MethodName: "ListMerchantTemplates",
			Handler:    _NpcAdminService_ListMerchantTemplates_Handler,
		},
		{
			MethodName: "ListItemCatalog",
			Handler:    _NpcAdminService_ListItemCatalog_Handler,
		},
		{
			MethodName: "ListMapZones",
			Handler:    _NpcAdminService_ListMapZones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}
