// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/web/v1/web.proto

// web-api contract — DESIGNED FROM SCRATCH (web-platform-plan.md). This is the
// edge the Next.js BFF (Route Handlers / Server Actions) calls server-side over
// gRPC + mTLS; the browser never speaks gRPC. It is SEPARATE from the legacy
// CPSock game login and from dbServer's AccountService (api/db/v1), which
// mirrors the legacy G↔DB messages. web-api reuses the same `account` table and
// argon2id hashing underneath, but exposes its own web-facing surface.
//
// Generate with `make proto` (protoc + protoc-gen-go/-grpc).

package webv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountWebService_CreateAccount_FullMethodName     = "/web.v1.AccountWebService/CreateAccount"
	AccountWebService_VerifyCredentials_FullMethodName = "/web.v1.AccountWebService/VerifyCredentials"
)

// AccountWebServiceClient is the client API for AccountWebService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountWebService owns the web platform's account flows (sign-up, credential
// check for the BFF session cookie). Game state is never written here — that
// stays in tmServer's single-owner loop (web-platform-plan.md).
type AccountWebServiceClient interface {
	// CreateAccount registers a new web/game account (argon2id-hashed password).
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// VerifyCredentials validates name + password so the BFF can mint a session
	// cookie. It is the web login path, independent of the CPSock game login.
	VerifyCredentials(ctx context.Context, in *VerifyCredentialsRequest, opts ...grpc.CallOption) (*VerifyCredentialsResponse, error)
}

type accountWebServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountWebServiceClient(cc grpc.ClientConnInterface) AccountWebServiceClient {
	return &accountWebServiceClient{cc}
}

func (c *accountWebServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, AccountWebService_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountWebServiceClient) VerifyCredentials(ctx context.Context, in *VerifyCredentialsRequest, opts ...grpc.CallOption) (*VerifyCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCredentialsResponse)
	err := c.cc.Invoke(ctx, AccountWebService_VerifyCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountWebServiceServer is the server API for AccountWebService service.
// All implementations must embed UnimplementedAccountWebServiceServer
// for forward compatibility.
//
// AccountWebService owns the web platform's account flows (sign-up, credential
// check for the BFF session cookie). Game state is never written here — that
// stays in tmServer's single-owner loop (web-platform-plan.md).
type AccountWebServiceServer interface {
	// CreateAccount registers a new web/game account (argon2id-hashed password).
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// VerifyCredentials validates name + password so the BFF can mint a session
	// cookie. It is the web login path, independent of the CPSock game login.
	VerifyCredentials(context.Context, *VerifyCredentialsRequest) (*VerifyCredentialsResponse, error)
	mustEmbedUnimplementedAccountWebServiceServer()
}

// UnimplementedAccountWebServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountWebServiceServer struct{}

func (UnimplementedAccountWebServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedAccountWebServiceServer) VerifyCredentials(context.Context, *VerifyCredentialsRequest) (*VerifyCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCredentials not implemented")
}
func (UnimplementedAccountWebServiceServer) mustEmbedUnimplementedAccountWebServiceServer() {}
func (UnimplementedAccountWebServiceServer) testEmbeddedByValue()                           {}

// UnsafeAccountWebServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountWebServiceServer will
// result in compilation errors.
type UnsafeAccountWebServiceServer interface {
	mustEmbedUnimplementedAccountWebServiceServer()
}

func RegisterAccountWebServiceServer(s grpc.ServiceRegistrar, srv AccountWebServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountWebServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountWebService_ServiceDesc, srv)
}

func _AccountWebService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountWebServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountWebService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountWebServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountWebService_VerifyCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountWebServiceServer).VerifyCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountWebService_VerifyCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountWebServiceServer).VerifyCredentials(ctx, req.(*VerifyCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountWebService_ServiceDesc is the grpc.ServiceDesc for AccountWebService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountWebService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.AccountWebService",
	HandlerType: (*AccountWebServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountWebService_CreateAccount_Handler,
		},
		{
			MethodName: "VerifyCredentials",
			Handler:    _AccountWebService_VerifyCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}
