// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/web/v1/web.proto

// web-api contract — DESIGNED FROM SCRATCH (web-platform-plan.md). This is the
// edge the Next.js BFF (Route Handlers / Server Actions) calls server-side over
// gRPC + mTLS; the browser never speaks gRPC. It is SEPARATE from the legacy
// CPSock game login and from dbServer's AccountService (api/db/v1), which
// mirrors the legacy G↔DB messages. web-api reuses the same `account` table and
// argon2id hashing underneath, but exposes its own web-facing surface.
//
// Generate with `make proto` (protoc + protoc-gen-go/-grpc).

package webv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountWebService_CreateAccount_FullMethodName     = "/web.v1.AccountWebService/CreateAccount"
	AccountWebService_VerifyCredentials_FullMethodName = "/web.v1.AccountWebService/VerifyCredentials"
)

// AccountWebServiceClient is the client API for AccountWebService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountWebService owns the web platform's account flows (sign-up, credential
// check for the BFF session cookie). Game state is never written here — that
// stays in tmServer's single-owner loop (web-platform-plan.md).
type AccountWebServiceClient interface {
	// CreateAccount registers a new web/game account (argon2id-hashed password).
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// VerifyCredentials validates name + password so the BFF can mint a session
	// cookie. It is the web login path, independent of the CPSock game login.
	VerifyCredentials(ctx context.Context, in *VerifyCredentialsRequest, opts ...grpc.CallOption) (*VerifyCredentialsResponse, error)
}

type accountWebServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountWebServiceClient(cc grpc.ClientConnInterface) AccountWebServiceClient {
	return &accountWebServiceClient{cc}
}

func (c *accountWebServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, AccountWebService_CreateAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountWebServiceClient) VerifyCredentials(ctx context.Context, in *VerifyCredentialsRequest, opts ...grpc.CallOption) (*VerifyCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCredentialsResponse)
	err := c.cc.Invoke(ctx, AccountWebService_VerifyCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountWebServiceServer is the server API for AccountWebService service.
// All implementations must embed UnimplementedAccountWebServiceServer
// for forward compatibility.
//
// AccountWebService owns the web platform's account flows (sign-up, credential
// check for the BFF session cookie). Game state is never written here — that
// stays in tmServer's single-owner loop (web-platform-plan.md).
type AccountWebServiceServer interface {
	// CreateAccount registers a new web/game account (argon2id-hashed password).
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// VerifyCredentials validates name + password so the BFF can mint a session
	// cookie. It is the web login path, independent of the CPSock game login.
	VerifyCredentials(context.Context, *VerifyCredentialsRequest) (*VerifyCredentialsResponse, error)
	mustEmbedUnimplementedAccountWebServiceServer()
}

// UnimplementedAccountWebServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountWebServiceServer struct{}

func (UnimplementedAccountWebServiceServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedAccountWebServiceServer) VerifyCredentials(context.Context, *VerifyCredentialsRequest) (*VerifyCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCredentials not implemented")
}
func (UnimplementedAccountWebServiceServer) mustEmbedUnimplementedAccountWebServiceServer() {}
func (UnimplementedAccountWebServiceServer) testEmbeddedByValue()                           {}

// UnsafeAccountWebServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountWebServiceServer will
// result in compilation errors.
type UnsafeAccountWebServiceServer interface {
	mustEmbedUnimplementedAccountWebServiceServer()
}

func RegisterAccountWebServiceServer(s grpc.ServiceRegistrar, srv AccountWebServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountWebServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountWebService_ServiceDesc, srv)
}

func _AccountWebService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountWebServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountWebService_CreateAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountWebServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountWebService_VerifyCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountWebServiceServer).VerifyCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountWebService_VerifyCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountWebServiceServer).VerifyCredentials(ctx, req.(*VerifyCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountWebService_ServiceDesc is the grpc.ServiceDesc for AccountWebService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountWebService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.AccountWebService",
	HandlerType: (*AccountWebServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountWebService_CreateAccount_Handler,
		},
		{
			MethodName: "VerifyCredentials",
			Handler:    _AccountWebService_VerifyCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}

const (
	RankingWebService_ListExpRanking_FullMethodName = "/web.v1.RankingWebService/ListExpRanking"
)

// RankingWebServiceClient is the client API for RankingWebService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RankingWebService exposes public ranking projections for the web front-end.
// It reads persisted character state from Postgres; the browser calls the
// Next.js BFF, and the BFF calls this service over gRPC + mTLS.
type RankingWebServiceClient interface {
	// ListExpRanking returns the Top EXP character ranking.
	ListExpRanking(ctx context.Context, in *ListExpRankingRequest, opts ...grpc.CallOption) (*ListExpRankingResponse, error)
}

type rankingWebServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRankingWebServiceClient(cc grpc.ClientConnInterface) RankingWebServiceClient {
	return &rankingWebServiceClient{cc}
}

func (c *rankingWebServiceClient) ListExpRanking(ctx context.Context, in *ListExpRankingRequest, opts ...grpc.CallOption) (*ListExpRankingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExpRankingResponse)
	err := c.cc.Invoke(ctx, RankingWebService_ListExpRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RankingWebServiceServer is the server API for RankingWebService service.
// All implementations must embed UnimplementedRankingWebServiceServer
// for forward compatibility.
//
// RankingWebService exposes public ranking projections for the web front-end.
// It reads persisted character state from Postgres; the browser calls the
// Next.js BFF, and the BFF calls this service over gRPC + mTLS.
type RankingWebServiceServer interface {
	// ListExpRanking returns the Top EXP character ranking.
	ListExpRanking(context.Context, *ListExpRankingRequest) (*ListExpRankingResponse, error)
	mustEmbedUnimplementedRankingWebServiceServer()
}

// UnimplementedRankingWebServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRankingWebServiceServer struct{}

func (UnimplementedRankingWebServiceServer) ListExpRanking(context.Context, *ListExpRankingRequest) (*ListExpRankingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExpRanking not implemented")
}
func (UnimplementedRankingWebServiceServer) mustEmbedUnimplementedRankingWebServiceServer() {}
func (UnimplementedRankingWebServiceServer) testEmbeddedByValue()                           {}

// UnsafeRankingWebServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RankingWebServiceServer will
// result in compilation errors.
type UnsafeRankingWebServiceServer interface {
	mustEmbedUnimplementedRankingWebServiceServer()
}

func RegisterRankingWebServiceServer(s grpc.ServiceRegistrar, srv RankingWebServiceServer) {
	// If the following call panics, it indicates UnimplementedRankingWebServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RankingWebService_ServiceDesc, srv)
}

func _RankingWebService_ListExpRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExpRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RankingWebServiceServer).ListExpRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RankingWebService_ListExpRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RankingWebServiceServer).ListExpRanking(ctx, req.(*ListExpRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RankingWebService_ServiceDesc is the grpc.ServiceDesc for RankingWebService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RankingWebService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.RankingWebService",
	HandlerType: (*RankingWebServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListExpRanking",
			Handler:    _RankingWebService_ListExpRanking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}

const (
	CharacterWebService_ListMyCharacters_FullMethodName = "/web.v1.CharacterWebService/ListMyCharacters"
)

// CharacterWebServiceClient is the client API for CharacterWebService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CharacterWebService exposes player-facing, read-only character summaries for
// the Next.js BFF. The BFF must pass the account_id from its httpOnly session;
// the browser must never provide account_id directly.
type CharacterWebServiceClient interface {
	// ListMyCharacters returns the character-selection projection for the logged
	// account. It is cold-storage data and can be slightly stale while a character
	// is online; live state remains owned by tmServer's single goroutine.
	ListMyCharacters(ctx context.Context, in *ListMyCharactersRequest, opts ...grpc.CallOption) (*ListMyCharactersResponse, error)
}

type characterWebServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCharacterWebServiceClient(cc grpc.ClientConnInterface) CharacterWebServiceClient {
	return &characterWebServiceClient{cc}
}

func (c *characterWebServiceClient) ListMyCharacters(ctx context.Context, in *ListMyCharactersRequest, opts ...grpc.CallOption) (*ListMyCharactersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyCharactersResponse)
	err := c.cc.Invoke(ctx, CharacterWebService_ListMyCharacters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CharacterWebServiceServer is the server API for CharacterWebService service.
// All implementations must embed UnimplementedCharacterWebServiceServer
// for forward compatibility.
//
// CharacterWebService exposes player-facing, read-only character summaries for
// the Next.js BFF. The BFF must pass the account_id from its httpOnly session;
// the browser must never provide account_id directly.
type CharacterWebServiceServer interface {
	// ListMyCharacters returns the character-selection projection for the logged
	// account. It is cold-storage data and can be slightly stale while a character
	// is online; live state remains owned by tmServer's single goroutine.
	ListMyCharacters(context.Context, *ListMyCharactersRequest) (*ListMyCharactersResponse, error)
	mustEmbedUnimplementedCharacterWebServiceServer()
}

// UnimplementedCharacterWebServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCharacterWebServiceServer struct{}

func (UnimplementedCharacterWebServiceServer) ListMyCharacters(context.Context, *ListMyCharactersRequest) (*ListMyCharactersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyCharacters not implemented")
}
func (UnimplementedCharacterWebServiceServer) mustEmbedUnimplementedCharacterWebServiceServer() {}
func (UnimplementedCharacterWebServiceServer) testEmbeddedByValue()                             {}

// UnsafeCharacterWebServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CharacterWebServiceServer will
// result in compilation errors.
type UnsafeCharacterWebServiceServer interface {
	mustEmbedUnimplementedCharacterWebServiceServer()
}

func RegisterCharacterWebServiceServer(s grpc.ServiceRegistrar, srv CharacterWebServiceServer) {
	// If the following call panics, it indicates UnimplementedCharacterWebServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CharacterWebService_ServiceDesc, srv)
}

func _CharacterWebService_ListMyCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyCharactersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CharacterWebServiceServer).ListMyCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CharacterWebService_ListMyCharacters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CharacterWebServiceServer).ListMyCharacters(ctx, req.(*ListMyCharactersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CharacterWebService_ServiceDesc is the grpc.ServiceDesc for CharacterWebService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CharacterWebService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.CharacterWebService",
	HandlerType: (*CharacterWebServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMyCharacters",
			Handler:    _CharacterWebService_ListMyCharacters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}

const (
	NpcAdminService_ListNpcs_FullMethodName              = "/web.v1.NpcAdminService/ListNpcs"
	NpcAdminService_GetNpc_FullMethodName                = "/web.v1.NpcAdminService/GetNpc"
	NpcAdminService_UpsertNpc_FullMethodName             = "/web.v1.NpcAdminService/UpsertNpc"
	NpcAdminService_SetNpcVisibility_FullMethodName      = "/web.v1.NpcAdminService/SetNpcVisibility"
	NpcAdminService_SetNpcShop_FullMethodName            = "/web.v1.NpcAdminService/SetNpcShop"
	NpcAdminService_SetItemPrice_FullMethodName          = "/web.v1.NpcAdminService/SetItemPrice"
	NpcAdminService_DeleteNpc_FullMethodName             = "/web.v1.NpcAdminService/DeleteNpc"
	NpcAdminService_ListMerchantTemplates_FullMethodName = "/web.v1.NpcAdminService/ListMerchantTemplates"
	NpcAdminService_ListItemCatalog_FullMethodName       = "/web.v1.NpcAdminService/ListItemCatalog"
	NpcAdminService_ListItemPrices_FullMethodName        = "/web.v1.NpcAdminService/ListItemPrices"
	NpcAdminService_ListMapZones_FullMethodName          = "/web.v1.NpcAdminService/ListMapZones"
)

// NpcAdminServiceClient is the client API for NpcAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NpcAdminService is the moderator-facing NPC editing surface (npc-editing-plan.md).
// The Next.js BFF calls it server-side after establishing a moderator session;
// every request carries the moderator's account_id, which the web-api authorizes
// against account.role ('moderator'/'admin') and records in the audit trail. All
// writes are cold config in Postgres — never live game state, which stays in
// tmServer's single-owner loop.
type NpcAdminServiceClient interface {
	// ListNpcs returns every NPC definition (moderation table).
	ListNpcs(ctx context.Context, in *ListNpcsRequest, opts ...grpc.CallOption) (*ListNpcsResponse, error)
	// GetNpc returns one definition with its shop stock.
	GetNpc(ctx context.Context, in *GetNpcRequest, opts ...grpc.CallOption) (*GetNpcResponse, error)
	// UpsertNpc creates or updates a definition (position, visibility, merchant type).
	UpsertNpc(ctx context.Context, in *UpsertNpcRequest, opts ...grpc.CallOption) (*UpsertNpcResponse, error)
	// SetNpcVisibility toggles whether the NPC appears ("aparece ou não").
	SetNpcVisibility(ctx context.Context, in *SetNpcVisibilityRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// SetNpcShop replaces a merchant NPC's shop stock.
	SetNpcShop(ctx context.Context, in *SetNpcShopRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// SetItemPrice sets (price>=0) or clears (price<0) the GLOBAL price of an item.
	SetItemPrice(ctx context.Context, in *SetItemPriceRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// DeleteNpc removes a definition.
	DeleteNpc(ctx context.Context, in *DeleteNpcRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// ListMerchantTemplates returns the merchant NPC templates found in the
	// content tree (Release/TMsrv/run/npc/, CurrentScore.Merchant != 0), so the
	// moderator UI can offer a searchable picker instead of a free-text
	// template_name field. Scanned once at web-api boot from -content/W2PP_CONTENT;
	// empty when that flag is unset.
	ListMerchantTemplates(ctx context.Context, in *ListMerchantTemplatesRequest, opts ...grpc.CallOption) (*ListMerchantTemplatesResponse, error)
	// ListItemCatalog returns the item catalog (Release/Common/ItemList.csv:
	// item_index, name), so the shop-item editor (SetNpcShop/SetItemPrice) can
	// offer a searchable picker instead of a raw item_index typed by hand.
	// Scanned once at web-api boot from -content/W2PP_CONTENT; empty when unset.
	ListItemCatalog(ctx context.Context, in *ListItemCatalogRequest, opts ...grpc.CallOption) (*ListItemCatalogResponse, error)
	// ListItemPrices returns every global item price override currently set
	// (item_price table). An item absent from the list has no override — it
	// uses the content catalog's base price.
	ListItemPrices(ctx context.Context, in *ListItemPricesRequest, opts ...grpc.CallOption) (*ListItemPricesResponse, error)
	// ListMapZones returns the fixed city-zone table (label only: the world runs
	// a single grid, so map_id has no gameplay effect today) for the NPC form's
	// map picker instead of a raw map_id typed by hand.
	ListMapZones(ctx context.Context, in *ListMapZonesRequest, opts ...grpc.CallOption) (*ListMapZonesResponse, error)
}

type npcAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNpcAdminServiceClient(cc grpc.ClientConnInterface) NpcAdminServiceClient {
	return &npcAdminServiceClient{cc}
}

func (c *npcAdminServiceClient) ListNpcs(ctx context.Context, in *ListNpcsRequest, opts ...grpc.CallOption) (*ListNpcsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNpcsResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_ListNpcs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) GetNpc(ctx context.Context, in *GetNpcRequest, opts ...grpc.CallOption) (*GetNpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNpcResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_GetNpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) UpsertNpc(ctx context.Context, in *UpsertNpcRequest, opts ...grpc.CallOption) (*UpsertNpcResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertNpcResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_UpsertNpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) SetNpcVisibility(ctx context.Context, in *SetNpcVisibilityRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, NpcAdminService_SetNpcVisibility_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) SetNpcShop(ctx context.Context, in *SetNpcShopRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, NpcAdminService_SetNpcShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) SetItemPrice(ctx context.Context, in *SetItemPriceRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, NpcAdminService_SetItemPrice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) DeleteNpc(ctx context.Context, in *DeleteNpcRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, NpcAdminService_DeleteNpc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) ListMerchantTemplates(ctx context.Context, in *ListMerchantTemplatesRequest, opts ...grpc.CallOption) (*ListMerchantTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMerchantTemplatesResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_ListMerchantTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) ListItemCatalog(ctx context.Context, in *ListItemCatalogRequest, opts ...grpc.CallOption) (*ListItemCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemCatalogResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_ListItemCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) ListItemPrices(ctx context.Context, in *ListItemPricesRequest, opts ...grpc.CallOption) (*ListItemPricesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemPricesResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_ListItemPrices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcAdminServiceClient) ListMapZones(ctx context.Context, in *ListMapZonesRequest, opts ...grpc.CallOption) (*ListMapZonesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMapZonesResponse)
	err := c.cc.Invoke(ctx, NpcAdminService_ListMapZones_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NpcAdminServiceServer is the server API for NpcAdminService service.
// All implementations must embed UnimplementedNpcAdminServiceServer
// for forward compatibility.
//
// NpcAdminService is the moderator-facing NPC editing surface (npc-editing-plan.md).
// The Next.js BFF calls it server-side after establishing a moderator session;
// every request carries the moderator's account_id, which the web-api authorizes
// against account.role ('moderator'/'admin') and records in the audit trail. All
// writes are cold config in Postgres — never live game state, which stays in
// tmServer's single-owner loop.
type NpcAdminServiceServer interface {
	// ListNpcs returns every NPC definition (moderation table).
	ListNpcs(context.Context, *ListNpcsRequest) (*ListNpcsResponse, error)
	// GetNpc returns one definition with its shop stock.
	GetNpc(context.Context, *GetNpcRequest) (*GetNpcResponse, error)
	// UpsertNpc creates or updates a definition (position, visibility, merchant type).
	UpsertNpc(context.Context, *UpsertNpcRequest) (*UpsertNpcResponse, error)
	// SetNpcVisibility toggles whether the NPC appears ("aparece ou não").
	SetNpcVisibility(context.Context, *SetNpcVisibilityRequest) (*AdminAck, error)
	// SetNpcShop replaces a merchant NPC's shop stock.
	SetNpcShop(context.Context, *SetNpcShopRequest) (*AdminAck, error)
	// SetItemPrice sets (price>=0) or clears (price<0) the GLOBAL price of an item.
	SetItemPrice(context.Context, *SetItemPriceRequest) (*AdminAck, error)
	// DeleteNpc removes a definition.
	DeleteNpc(context.Context, *DeleteNpcRequest) (*AdminAck, error)
	// ListMerchantTemplates returns the merchant NPC templates found in the
	// content tree (Release/TMsrv/run/npc/, CurrentScore.Merchant != 0), so the
	// moderator UI can offer a searchable picker instead of a free-text
	// template_name field. Scanned once at web-api boot from -content/W2PP_CONTENT;
	// empty when that flag is unset.
	ListMerchantTemplates(context.Context, *ListMerchantTemplatesRequest) (*ListMerchantTemplatesResponse, error)
	// ListItemCatalog returns the item catalog (Release/Common/ItemList.csv:
	// item_index, name), so the shop-item editor (SetNpcShop/SetItemPrice) can
	// offer a searchable picker instead of a raw item_index typed by hand.
	// Scanned once at web-api boot from -content/W2PP_CONTENT; empty when unset.
	ListItemCatalog(context.Context, *ListItemCatalogRequest) (*ListItemCatalogResponse, error)
	// ListItemPrices returns every global item price override currently set
	// (item_price table). An item absent from the list has no override — it
	// uses the content catalog's base price.
	ListItemPrices(context.Context, *ListItemPricesRequest) (*ListItemPricesResponse, error)
	// ListMapZones returns the fixed city-zone table (label only: the world runs
	// a single grid, so map_id has no gameplay effect today) for the NPC form's
	// map picker instead of a raw map_id typed by hand.
	ListMapZones(context.Context, *ListMapZonesRequest) (*ListMapZonesResponse, error)
	mustEmbedUnimplementedNpcAdminServiceServer()
}

// UnimplementedNpcAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNpcAdminServiceServer struct{}

func (UnimplementedNpcAdminServiceServer) ListNpcs(context.Context, *ListNpcsRequest) (*ListNpcsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNpcs not implemented")
}
func (UnimplementedNpcAdminServiceServer) GetNpc(context.Context, *GetNpcRequest) (*GetNpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNpc not implemented")
}
func (UnimplementedNpcAdminServiceServer) UpsertNpc(context.Context, *UpsertNpcRequest) (*UpsertNpcResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertNpc not implemented")
}
func (UnimplementedNpcAdminServiceServer) SetNpcVisibility(context.Context, *SetNpcVisibilityRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNpcVisibility not implemented")
}
func (UnimplementedNpcAdminServiceServer) SetNpcShop(context.Context, *SetNpcShopRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNpcShop not implemented")
}
func (UnimplementedNpcAdminServiceServer) SetItemPrice(context.Context, *SetItemPriceRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetItemPrice not implemented")
}
func (UnimplementedNpcAdminServiceServer) DeleteNpc(context.Context, *DeleteNpcRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNpc not implemented")
}
func (UnimplementedNpcAdminServiceServer) ListMerchantTemplates(context.Context, *ListMerchantTemplatesRequest) (*ListMerchantTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMerchantTemplates not implemented")
}
func (UnimplementedNpcAdminServiceServer) ListItemCatalog(context.Context, *ListItemCatalogRequest) (*ListItemCatalogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItemCatalog not implemented")
}
func (UnimplementedNpcAdminServiceServer) ListItemPrices(context.Context, *ListItemPricesRequest) (*ListItemPricesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListItemPrices not implemented")
}
func (UnimplementedNpcAdminServiceServer) ListMapZones(context.Context, *ListMapZonesRequest) (*ListMapZonesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMapZones not implemented")
}
func (UnimplementedNpcAdminServiceServer) mustEmbedUnimplementedNpcAdminServiceServer() {}
func (UnimplementedNpcAdminServiceServer) testEmbeddedByValue()                         {}

// UnsafeNpcAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NpcAdminServiceServer will
// result in compilation errors.
type UnsafeNpcAdminServiceServer interface {
	mustEmbedUnimplementedNpcAdminServiceServer()
}

func RegisterNpcAdminServiceServer(s grpc.ServiceRegistrar, srv NpcAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedNpcAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NpcAdminService_ServiceDesc, srv)
}

func _NpcAdminService_ListNpcs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNpcsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).ListNpcs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_ListNpcs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).ListNpcs(ctx, req.(*ListNpcsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_GetNpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).GetNpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_GetNpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).GetNpc(ctx, req.(*GetNpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_UpsertNpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertNpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).UpsertNpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_UpsertNpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).UpsertNpc(ctx, req.(*UpsertNpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_SetNpcVisibility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNpcVisibilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).SetNpcVisibility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_SetNpcVisibility_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).SetNpcVisibility(ctx, req.(*SetNpcVisibilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_SetNpcShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNpcShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).SetNpcShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_SetNpcShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).SetNpcShop(ctx, req.(*SetNpcShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_SetItemPrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetItemPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).SetItemPrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_SetItemPrice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).SetItemPrice(ctx, req.(*SetItemPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_DeleteNpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).DeleteNpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_DeleteNpc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).DeleteNpc(ctx, req.(*DeleteNpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_ListMerchantTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMerchantTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).ListMerchantTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_ListMerchantTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).ListMerchantTemplates(ctx, req.(*ListMerchantTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_ListItemCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).ListItemCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_ListItemCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).ListItemCatalog(ctx, req.(*ListItemCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_ListItemPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemPricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).ListItemPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_ListItemPrices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).ListItemPrices(ctx, req.(*ListItemPricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcAdminService_ListMapZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMapZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcAdminServiceServer).ListMapZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcAdminService_ListMapZones_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcAdminServiceServer).ListMapZones(ctx, req.(*ListMapZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NpcAdminService_ServiceDesc is the grpc.ServiceDesc for NpcAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NpcAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.NpcAdminService",
	HandlerType: (*NpcAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNpcs",
			Handler:    _NpcAdminService_ListNpcs_Handler,
		},
		{
			MethodName: "GetNpc",
			Handler:    _NpcAdminService_GetNpc_Handler,
		},
		{
			MethodName: "UpsertNpc",
			Handler:    _NpcAdminService_UpsertNpc_Handler,
		},
		{
			MethodName: "SetNpcVisibility",
			Handler:    _NpcAdminService_SetNpcVisibility_Handler,
		},
		{
			MethodName: "SetNpcShop",
			Handler:    _NpcAdminService_SetNpcShop_Handler,
		},
		{
			MethodName: "SetItemPrice",
			Handler:    _NpcAdminService_SetItemPrice_Handler,
		},
		{
			MethodName: "DeleteNpc",
			Handler:    _NpcAdminService_DeleteNpc_Handler,
		},
		{
			MethodName: "ListMerchantTemplates",
			Handler:    _NpcAdminService_ListMerchantTemplates_Handler,
		},
		{
			MethodName: "ListItemCatalog",
			Handler:    _NpcAdminService_ListItemCatalog_Handler,
		},
		{
			MethodName: "ListItemPrices",
			Handler:    _NpcAdminService_ListItemPrices_Handler,
		},
		{
			MethodName: "ListMapZones",
			Handler:    _NpcAdminService_ListMapZones_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}

const (
	DonateAdminService_ListShopItems_FullMethodName       = "/web.v1.DonateAdminService/ListShopItems"
	DonateAdminService_UpsertShopItem_FullMethodName      = "/web.v1.DonateAdminService/UpsertShopItem"
	DonateAdminService_SetShopItemEnabled_FullMethodName  = "/web.v1.DonateAdminService/SetShopItemEnabled"
	DonateAdminService_DeleteShopItem_FullMethodName      = "/web.v1.DonateAdminService/DeleteShopItem"
	DonateAdminService_CreditDonateBalance_FullMethodName = "/web.v1.DonateAdminService/CreditDonateBalance"
)

// DonateAdminServiceClient is the client API for DonateAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DonateAdminService is the moderator-facing donate web-shop surface (issue #34):
// CRUD over the donate_shop_item catalog plus the manual "credit donate to an
// account" path (the seam the future payment webhook reuses). Like NpcAdminService
// every request carries the moderator's account_id, re-authorized server-side
// against account.role; all writes are cold config in Postgres, never live state.
type DonateAdminServiceClient interface {
	// ListShopItems returns every offer (enabled or not) — the moderation table.
	ListShopItems(ctx context.Context, in *ListShopItemsRequest, opts ...grpc.CallOption) (*ListShopItemsResponse, error)
	// UpsertShopItem creates (id==0) or updates an offer.
	UpsertShopItem(ctx context.Context, in *UpsertShopItemRequest, opts ...grpc.CallOption) (*UpsertShopItemResponse, error)
	// SetShopItemEnabled toggles whether an offer is on sale.
	SetShopItemEnabled(ctx context.Context, in *SetShopItemEnabledRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// DeleteShopItem removes an offer.
	DeleteShopItem(ctx context.Context, in *DeleteShopItemRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// CreditDonateBalance adds donate currency to an account's wallet. This is the
	// "adicionar donate na conta" function; the payment webhook will later call the
	// same underlying store method after settling a real-money donation.
	CreditDonateBalance(ctx context.Context, in *CreditDonateBalanceRequest, opts ...grpc.CallOption) (*CreditDonateBalanceResponse, error)
}

type donateAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDonateAdminServiceClient(cc grpc.ClientConnInterface) DonateAdminServiceClient {
	return &donateAdminServiceClient{cc}
}

func (c *donateAdminServiceClient) ListShopItems(ctx context.Context, in *ListShopItemsRequest, opts ...grpc.CallOption) (*ListShopItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListShopItemsResponse)
	err := c.cc.Invoke(ctx, DonateAdminService_ListShopItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateAdminServiceClient) UpsertShopItem(ctx context.Context, in *UpsertShopItemRequest, opts ...grpc.CallOption) (*UpsertShopItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertShopItemResponse)
	err := c.cc.Invoke(ctx, DonateAdminService_UpsertShopItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateAdminServiceClient) SetShopItemEnabled(ctx context.Context, in *SetShopItemEnabledRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, DonateAdminService_SetShopItemEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateAdminServiceClient) DeleteShopItem(ctx context.Context, in *DeleteShopItemRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, DonateAdminService_DeleteShopItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateAdminServiceClient) CreditDonateBalance(ctx context.Context, in *CreditDonateBalanceRequest, opts ...grpc.CallOption) (*CreditDonateBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreditDonateBalanceResponse)
	err := c.cc.Invoke(ctx, DonateAdminService_CreditDonateBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DonateAdminServiceServer is the server API for DonateAdminService service.
// All implementations must embed UnimplementedDonateAdminServiceServer
// for forward compatibility.
//
// DonateAdminService is the moderator-facing donate web-shop surface (issue #34):
// CRUD over the donate_shop_item catalog plus the manual "credit donate to an
// account" path (the seam the future payment webhook reuses). Like NpcAdminService
// every request carries the moderator's account_id, re-authorized server-side
// against account.role; all writes are cold config in Postgres, never live state.
type DonateAdminServiceServer interface {
	// ListShopItems returns every offer (enabled or not) — the moderation table.
	ListShopItems(context.Context, *ListShopItemsRequest) (*ListShopItemsResponse, error)
	// UpsertShopItem creates (id==0) or updates an offer.
	UpsertShopItem(context.Context, *UpsertShopItemRequest) (*UpsertShopItemResponse, error)
	// SetShopItemEnabled toggles whether an offer is on sale.
	SetShopItemEnabled(context.Context, *SetShopItemEnabledRequest) (*AdminAck, error)
	// DeleteShopItem removes an offer.
	DeleteShopItem(context.Context, *DeleteShopItemRequest) (*AdminAck, error)
	// CreditDonateBalance adds donate currency to an account's wallet. This is the
	// "adicionar donate na conta" function; the payment webhook will later call the
	// same underlying store method after settling a real-money donation.
	CreditDonateBalance(context.Context, *CreditDonateBalanceRequest) (*CreditDonateBalanceResponse, error)
	mustEmbedUnimplementedDonateAdminServiceServer()
}

// UnimplementedDonateAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDonateAdminServiceServer struct{}

func (UnimplementedDonateAdminServiceServer) ListShopItems(context.Context, *ListShopItemsRequest) (*ListShopItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShopItems not implemented")
}
func (UnimplementedDonateAdminServiceServer) UpsertShopItem(context.Context, *UpsertShopItemRequest) (*UpsertShopItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertShopItem not implemented")
}
func (UnimplementedDonateAdminServiceServer) SetShopItemEnabled(context.Context, *SetShopItemEnabledRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetShopItemEnabled not implemented")
}
func (UnimplementedDonateAdminServiceServer) DeleteShopItem(context.Context, *DeleteShopItemRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteShopItem not implemented")
}
func (UnimplementedDonateAdminServiceServer) CreditDonateBalance(context.Context, *CreditDonateBalanceRequest) (*CreditDonateBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreditDonateBalance not implemented")
}
func (UnimplementedDonateAdminServiceServer) mustEmbedUnimplementedDonateAdminServiceServer() {}
func (UnimplementedDonateAdminServiceServer) testEmbeddedByValue()                            {}

// UnsafeDonateAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DonateAdminServiceServer will
// result in compilation errors.
type UnsafeDonateAdminServiceServer interface {
	mustEmbedUnimplementedDonateAdminServiceServer()
}

func RegisterDonateAdminServiceServer(s grpc.ServiceRegistrar, srv DonateAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedDonateAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DonateAdminService_ServiceDesc, srv)
}

func _DonateAdminService_ListShopItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListShopItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateAdminServiceServer).ListShopItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateAdminService_ListShopItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateAdminServiceServer).ListShopItems(ctx, req.(*ListShopItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateAdminService_UpsertShopItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertShopItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateAdminServiceServer).UpsertShopItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateAdminService_UpsertShopItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateAdminServiceServer).UpsertShopItem(ctx, req.(*UpsertShopItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateAdminService_SetShopItemEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetShopItemEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateAdminServiceServer).SetShopItemEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateAdminService_SetShopItemEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateAdminServiceServer).SetShopItemEnabled(ctx, req.(*SetShopItemEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateAdminService_DeleteShopItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteShopItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateAdminServiceServer).DeleteShopItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateAdminService_DeleteShopItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateAdminServiceServer).DeleteShopItem(ctx, req.(*DeleteShopItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateAdminService_CreditDonateBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreditDonateBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateAdminServiceServer).CreditDonateBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateAdminService_CreditDonateBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateAdminServiceServer).CreditDonateBalance(ctx, req.(*CreditDonateBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DonateAdminService_ServiceDesc is the grpc.ServiceDesc for DonateAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DonateAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.DonateAdminService",
	HandlerType: (*DonateAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListShopItems",
			Handler:    _DonateAdminService_ListShopItems_Handler,
		},
		{
			MethodName: "UpsertShopItem",
			Handler:    _DonateAdminService_UpsertShopItem_Handler,
		},
		{
			MethodName: "SetShopItemEnabled",
			Handler:    _DonateAdminService_SetShopItemEnabled_Handler,
		},
		{
			MethodName: "DeleteShopItem",
			Handler:    _DonateAdminService_DeleteShopItem_Handler,
		},
		{
			MethodName: "CreditDonateBalance",
			Handler:    _DonateAdminService_CreditDonateBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}

const (
	DonateShopService_ListShopItems_FullMethodName = "/web.v1.DonateShopService/ListShopItems"
	DonateShopService_GetBalance_FullMethodName    = "/web.v1.DonateShopService/GetBalance"
	DonateShopService_Buy_FullMethodName           = "/web.v1.DonateShopService/Buy"
)

// DonateShopServiceClient is the client API for DonateShopService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DonateShopService is the player-facing donate shop the Next.js BFF calls with
// the logged account_id from its httpOnly session (never browser-supplied). It
// reads the enabled catalog and processes purchases: a purchase debits the
// account's donate balance and enqueues the item into delivery_queue, which the
// tmServer drains into the account cargo on the next login (web-platform-plan.md).
type DonateShopServiceClient interface {
	// ListShopItems returns the enabled offers (the vitrine).
	ListShopItems(ctx context.Context, in *ListStoreItemsRequest, opts ...grpc.CallOption) (*ListStoreItemsResponse, error)
	// GetBalance returns the account's current donate balance.
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	// Buy purchases an offer for the account.
	Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResponse, error)
}

type donateShopServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDonateShopServiceClient(cc grpc.ClientConnInterface) DonateShopServiceClient {
	return &donateShopServiceClient{cc}
}

func (c *donateShopServiceClient) ListShopItems(ctx context.Context, in *ListStoreItemsRequest, opts ...grpc.CallOption) (*ListStoreItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStoreItemsResponse)
	err := c.cc.Invoke(ctx, DonateShopService_ListShopItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateShopServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, DonateShopService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateShopServiceClient) Buy(ctx context.Context, in *BuyRequest, opts ...grpc.CallOption) (*BuyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyResponse)
	err := c.cc.Invoke(ctx, DonateShopService_Buy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DonateShopServiceServer is the server API for DonateShopService service.
// All implementations must embed UnimplementedDonateShopServiceServer
// for forward compatibility.
//
// DonateShopService is the player-facing donate shop the Next.js BFF calls with
// the logged account_id from its httpOnly session (never browser-supplied). It
// reads the enabled catalog and processes purchases: a purchase debits the
// account's donate balance and enqueues the item into delivery_queue, which the
// tmServer drains into the account cargo on the next login (web-platform-plan.md).
type DonateShopServiceServer interface {
	// ListShopItems returns the enabled offers (the vitrine).
	ListShopItems(context.Context, *ListStoreItemsRequest) (*ListStoreItemsResponse, error)
	// GetBalance returns the account's current donate balance.
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	// Buy purchases an offer for the account.
	Buy(context.Context, *BuyRequest) (*BuyResponse, error)
	mustEmbedUnimplementedDonateShopServiceServer()
}

// UnimplementedDonateShopServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDonateShopServiceServer struct{}

func (UnimplementedDonateShopServiceServer) ListShopItems(context.Context, *ListStoreItemsRequest) (*ListStoreItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListShopItems not implemented")
}
func (UnimplementedDonateShopServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedDonateShopServiceServer) Buy(context.Context, *BuyRequest) (*BuyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Buy not implemented")
}
func (UnimplementedDonateShopServiceServer) mustEmbedUnimplementedDonateShopServiceServer() {}
func (UnimplementedDonateShopServiceServer) testEmbeddedByValue()                           {}

// UnsafeDonateShopServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DonateShopServiceServer will
// result in compilation errors.
type UnsafeDonateShopServiceServer interface {
	mustEmbedUnimplementedDonateShopServiceServer()
}

func RegisterDonateShopServiceServer(s grpc.ServiceRegistrar, srv DonateShopServiceServer) {
	// If the following call panics, it indicates UnimplementedDonateShopServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DonateShopService_ServiceDesc, srv)
}

func _DonateShopService_ListShopItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoreItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateShopServiceServer).ListShopItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateShopService_ListShopItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateShopServiceServer).ListShopItems(ctx, req.(*ListStoreItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateShopService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateShopServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateShopService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateShopServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateShopService_Buy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateShopServiceServer).Buy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateShopService_Buy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateShopServiceServer).Buy(ctx, req.(*BuyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DonateShopService_ServiceDesc is the grpc.ServiceDesc for DonateShopService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DonateShopService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.DonateShopService",
	HandlerType: (*DonateShopServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListShopItems",
			Handler:    _DonateShopService_ListShopItems_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _DonateShopService_GetBalance_Handler,
		},
		{
			MethodName: "Buy",
			Handler:    _DonateShopService_Buy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}

const (
	DailyRewardAdminService_ListRewardItems_FullMethodName      = "/web.v1.DailyRewardAdminService/ListRewardItems"
	DailyRewardAdminService_UpsertRewardItem_FullMethodName     = "/web.v1.DailyRewardAdminService/UpsertRewardItem"
	DailyRewardAdminService_SetRewardItemEnabled_FullMethodName = "/web.v1.DailyRewardAdminService/SetRewardItemEnabled"
	DailyRewardAdminService_DeleteRewardItem_FullMethodName     = "/web.v1.DailyRewardAdminService/DeleteRewardItem"
)

// DailyRewardAdminServiceClient is the client API for DailyRewardAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DailyRewardAdminService is the moderator-facing daily-reward catalog surface
// (issue #35): CRUD over the daily_reward_item catalog. Like DonateAdminService
// every request carries the moderator's account_id, re-authorized server-side
// against account.role; all writes are cold config in Postgres, never live
// state. Unlike DonateAdminService there is no balance-credit RPC — daily
// rewards are free.
type DailyRewardAdminServiceClient interface {
	// ListRewardItems returns every offer (enabled or not) — the moderation table.
	ListRewardItems(ctx context.Context, in *ListRewardItemsRequest, opts ...grpc.CallOption) (*ListRewardItemsResponse, error)
	// UpsertRewardItem creates (id==0) or updates an offer.
	UpsertRewardItem(ctx context.Context, in *UpsertRewardItemRequest, opts ...grpc.CallOption) (*UpsertRewardItemResponse, error)
	// SetRewardItemEnabled toggles whether an offer is claimable.
	SetRewardItemEnabled(ctx context.Context, in *SetRewardItemEnabledRequest, opts ...grpc.CallOption) (*AdminAck, error)
	// DeleteRewardItem removes an offer.
	DeleteRewardItem(ctx context.Context, in *DeleteRewardItemRequest, opts ...grpc.CallOption) (*AdminAck, error)
}

type dailyRewardAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDailyRewardAdminServiceClient(cc grpc.ClientConnInterface) DailyRewardAdminServiceClient {
	return &dailyRewardAdminServiceClient{cc}
}

func (c *dailyRewardAdminServiceClient) ListRewardItems(ctx context.Context, in *ListRewardItemsRequest, opts ...grpc.CallOption) (*ListRewardItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRewardItemsResponse)
	err := c.cc.Invoke(ctx, DailyRewardAdminService_ListRewardItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dailyRewardAdminServiceClient) UpsertRewardItem(ctx context.Context, in *UpsertRewardItemRequest, opts ...grpc.CallOption) (*UpsertRewardItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRewardItemResponse)
	err := c.cc.Invoke(ctx, DailyRewardAdminService_UpsertRewardItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dailyRewardAdminServiceClient) SetRewardItemEnabled(ctx context.Context, in *SetRewardItemEnabledRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, DailyRewardAdminService_SetRewardItemEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dailyRewardAdminServiceClient) DeleteRewardItem(ctx context.Context, in *DeleteRewardItemRequest, opts ...grpc.CallOption) (*AdminAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminAck)
	err := c.cc.Invoke(ctx, DailyRewardAdminService_DeleteRewardItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DailyRewardAdminServiceServer is the server API for DailyRewardAdminService service.
// All implementations must embed UnimplementedDailyRewardAdminServiceServer
// for forward compatibility.
//
// DailyRewardAdminService is the moderator-facing daily-reward catalog surface
// (issue #35): CRUD over the daily_reward_item catalog. Like DonateAdminService
// every request carries the moderator's account_id, re-authorized server-side
// against account.role; all writes are cold config in Postgres, never live
// state. Unlike DonateAdminService there is no balance-credit RPC — daily
// rewards are free.
type DailyRewardAdminServiceServer interface {
	// ListRewardItems returns every offer (enabled or not) — the moderation table.
	ListRewardItems(context.Context, *ListRewardItemsRequest) (*ListRewardItemsResponse, error)
	// UpsertRewardItem creates (id==0) or updates an offer.
	UpsertRewardItem(context.Context, *UpsertRewardItemRequest) (*UpsertRewardItemResponse, error)
	// SetRewardItemEnabled toggles whether an offer is claimable.
	SetRewardItemEnabled(context.Context, *SetRewardItemEnabledRequest) (*AdminAck, error)
	// DeleteRewardItem removes an offer.
	DeleteRewardItem(context.Context, *DeleteRewardItemRequest) (*AdminAck, error)
	mustEmbedUnimplementedDailyRewardAdminServiceServer()
}

// UnimplementedDailyRewardAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDailyRewardAdminServiceServer struct{}

func (UnimplementedDailyRewardAdminServiceServer) ListRewardItems(context.Context, *ListRewardItemsRequest) (*ListRewardItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRewardItems not implemented")
}
func (UnimplementedDailyRewardAdminServiceServer) UpsertRewardItem(context.Context, *UpsertRewardItemRequest) (*UpsertRewardItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRewardItem not implemented")
}
func (UnimplementedDailyRewardAdminServiceServer) SetRewardItemEnabled(context.Context, *SetRewardItemEnabledRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRewardItemEnabled not implemented")
}
func (UnimplementedDailyRewardAdminServiceServer) DeleteRewardItem(context.Context, *DeleteRewardItemRequest) (*AdminAck, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRewardItem not implemented")
}
func (UnimplementedDailyRewardAdminServiceServer) mustEmbedUnimplementedDailyRewardAdminServiceServer() {
}
func (UnimplementedDailyRewardAdminServiceServer) testEmbeddedByValue() {}

// UnsafeDailyRewardAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DailyRewardAdminServiceServer will
// result in compilation errors.
type UnsafeDailyRewardAdminServiceServer interface {
	mustEmbedUnimplementedDailyRewardAdminServiceServer()
}

func RegisterDailyRewardAdminServiceServer(s grpc.ServiceRegistrar, srv DailyRewardAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedDailyRewardAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DailyRewardAdminService_ServiceDesc, srv)
}

func _DailyRewardAdminService_ListRewardItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRewardItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DailyRewardAdminServiceServer).ListRewardItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DailyRewardAdminService_ListRewardItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DailyRewardAdminServiceServer).ListRewardItems(ctx, req.(*ListRewardItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DailyRewardAdminService_UpsertRewardItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRewardItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DailyRewardAdminServiceServer).UpsertRewardItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DailyRewardAdminService_UpsertRewardItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DailyRewardAdminServiceServer).UpsertRewardItem(ctx, req.(*UpsertRewardItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DailyRewardAdminService_SetRewardItemEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRewardItemEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DailyRewardAdminServiceServer).SetRewardItemEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DailyRewardAdminService_SetRewardItemEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DailyRewardAdminServiceServer).SetRewardItemEnabled(ctx, req.(*SetRewardItemEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DailyRewardAdminService_DeleteRewardItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRewardItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DailyRewardAdminServiceServer).DeleteRewardItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DailyRewardAdminService_DeleteRewardItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DailyRewardAdminServiceServer).DeleteRewardItem(ctx, req.(*DeleteRewardItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DailyRewardAdminService_ServiceDesc is the grpc.ServiceDesc for DailyRewardAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DailyRewardAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.DailyRewardAdminService",
	HandlerType: (*DailyRewardAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRewardItems",
			Handler:    _DailyRewardAdminService_ListRewardItems_Handler,
		},
		{
			MethodName: "UpsertRewardItem",
			Handler:    _DailyRewardAdminService_UpsertRewardItem_Handler,
		},
		{
			MethodName: "SetRewardItemEnabled",
			Handler:    _DailyRewardAdminService_SetRewardItemEnabled_Handler,
		},
		{
			MethodName: "DeleteRewardItem",
			Handler:    _DailyRewardAdminService_DeleteRewardItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}

const (
	DailyRewardService_ListRewards_FullMethodName    = "/web.v1.DailyRewardService/ListRewards"
	DailyRewardService_GetClaimStatus_FullMethodName = "/web.v1.DailyRewardService/GetClaimStatus"
	DailyRewardService_Claim_FullMethodName          = "/web.v1.DailyRewardService/Claim"
)

// DailyRewardServiceClient is the client API for DailyRewardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DailyRewardService is the player-facing daily reward surface the Next.js BFF
// calls with the logged account_id from its httpOnly session (never
// browser-supplied). A claim inserts a daily_reward_claim row for today's UTC
// calendar day and enqueues the item into delivery_queue, which the tmServer
// drains into the account cargo on the next login (web-platform-plan.md), the
// same pipe DonateShopService purchases use.
type DailyRewardServiceClient interface {
	// ListRewards returns the enabled offers (the vitrine).
	ListRewards(ctx context.Context, in *ListRewardsRequest, opts ...grpc.CallOption) (*ListRewardsResponse, error)
	// GetClaimStatus reports whether the account already claimed today.
	GetClaimStatus(ctx context.Context, in *GetClaimStatusRequest, opts ...grpc.CallOption) (*GetClaimStatusResponse, error)
	// Claim redeems one reward offer for the account for today.
	Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error)
}

type dailyRewardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDailyRewardServiceClient(cc grpc.ClientConnInterface) DailyRewardServiceClient {
	return &dailyRewardServiceClient{cc}
}

func (c *dailyRewardServiceClient) ListRewards(ctx context.Context, in *ListRewardsRequest, opts ...grpc.CallOption) (*ListRewardsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRewardsResponse)
	err := c.cc.Invoke(ctx, DailyRewardService_ListRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dailyRewardServiceClient) GetClaimStatus(ctx context.Context, in *GetClaimStatusRequest, opts ...grpc.CallOption) (*GetClaimStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClaimStatusResponse)
	err := c.cc.Invoke(ctx, DailyRewardService_GetClaimStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dailyRewardServiceClient) Claim(ctx context.Context, in *ClaimRequest, opts ...grpc.CallOption) (*ClaimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimResponse)
	err := c.cc.Invoke(ctx, DailyRewardService_Claim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DailyRewardServiceServer is the server API for DailyRewardService service.
// All implementations must embed UnimplementedDailyRewardServiceServer
// for forward compatibility.
//
// DailyRewardService is the player-facing daily reward surface the Next.js BFF
// calls with the logged account_id from its httpOnly session (never
// browser-supplied). A claim inserts a daily_reward_claim row for today's UTC
// calendar day and enqueues the item into delivery_queue, which the tmServer
// drains into the account cargo on the next login (web-platform-plan.md), the
// same pipe DonateShopService purchases use.
type DailyRewardServiceServer interface {
	// ListRewards returns the enabled offers (the vitrine).
	ListRewards(context.Context, *ListRewardsRequest) (*ListRewardsResponse, error)
	// GetClaimStatus reports whether the account already claimed today.
	GetClaimStatus(context.Context, *GetClaimStatusRequest) (*GetClaimStatusResponse, error)
	// Claim redeems one reward offer for the account for today.
	Claim(context.Context, *ClaimRequest) (*ClaimResponse, error)
	mustEmbedUnimplementedDailyRewardServiceServer()
}

// UnimplementedDailyRewardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDailyRewardServiceServer struct{}

func (UnimplementedDailyRewardServiceServer) ListRewards(context.Context, *ListRewardsRequest) (*ListRewardsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRewards not implemented")
}
func (UnimplementedDailyRewardServiceServer) GetClaimStatus(context.Context, *GetClaimStatusRequest) (*GetClaimStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClaimStatus not implemented")
}
func (UnimplementedDailyRewardServiceServer) Claim(context.Context, *ClaimRequest) (*ClaimResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Claim not implemented")
}
func (UnimplementedDailyRewardServiceServer) mustEmbedUnimplementedDailyRewardServiceServer() {}
func (UnimplementedDailyRewardServiceServer) testEmbeddedByValue()                            {}

// UnsafeDailyRewardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DailyRewardServiceServer will
// result in compilation errors.
type UnsafeDailyRewardServiceServer interface {
	mustEmbedUnimplementedDailyRewardServiceServer()
}

func RegisterDailyRewardServiceServer(s grpc.ServiceRegistrar, srv DailyRewardServiceServer) {
	// If the following call panics, it indicates UnimplementedDailyRewardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DailyRewardService_ServiceDesc, srv)
}

func _DailyRewardService_ListRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DailyRewardServiceServer).ListRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DailyRewardService_ListRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DailyRewardServiceServer).ListRewards(ctx, req.(*ListRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DailyRewardService_GetClaimStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClaimStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DailyRewardServiceServer).GetClaimStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DailyRewardService_GetClaimStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DailyRewardServiceServer).GetClaimStatus(ctx, req.(*GetClaimStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DailyRewardService_Claim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DailyRewardServiceServer).Claim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DailyRewardService_Claim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DailyRewardServiceServer).Claim(ctx, req.(*ClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DailyRewardService_ServiceDesc is the grpc.ServiceDesc for DailyRewardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DailyRewardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.DailyRewardService",
	HandlerType: (*DailyRewardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRewards",
			Handler:    _DailyRewardService_ListRewards_Handler,
		},
		{
			MethodName: "GetClaimStatus",
			Handler:    _DailyRewardService_GetClaimStatus_Handler,
		},
		{
			MethodName: "Claim",
			Handler:    _DailyRewardService_Claim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}

const (
	DonateTopupService_GetPayerProfile_FullMethodName   = "/web.v1.DonateTopupService/GetPayerProfile"
	DonateTopupService_SavePayerProfile_FullMethodName  = "/web.v1.DonateTopupService/SavePayerProfile"
	DonateTopupService_CreateTopupOrder_FullMethodName  = "/web.v1.DonateTopupService/CreateTopupOrder"
	DonateTopupService_ConfirmTopupOrder_FullMethodName = "/web.v1.DonateTopupService/ConfirmTopupOrder"
	DonateTopupService_GetTopupOrder_FullMethodName     = "/web.v1.DonateTopupService/GetTopupOrder"
)

// DonateTopupServiceClient is the client API for DonateTopupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DonateTopupService is the payment-method-agnostic donate top-up surface the
// Next.js BFF calls server-side (never the browser). The portal owns no
// database: every durable order and the idempotency of the credit live here.
// PIX is the only method wired today, but the method is a FIELD of the order
// (payment_method), never part of an RPC or table name — credit card reuses the
// same RPCs and table later. The top-up credit happens INSIDE ConfirmTopupOrder,
// in the same transaction that flips the order to PAID and WITHOUT a moderator_id
// (unlike DonateAdminService.CreditDonateBalance), so a replayed webhook credits
// exactly once.
type DonateTopupServiceClient interface {
	// Payer profile (name + CPF), reused across a payer's top-ups.
	GetPayerProfile(ctx context.Context, in *GetPayerProfileRequest, opts ...grpc.CallOption) (*GetPayerProfileResponse, error)
	SavePayerProfile(ctx context.Context, in *SavePayerProfileRequest, opts ...grpc.CallOption) (*SavePayerProfileResponse, error)
	// CreateTopupOrder persists a PENDING order before the portal calls the
	// gateway (persist-before-provider). ConfirmTopupOrder credits the account
	// exactly once (idempotent on external_reference). GetTopupOrder is the poll.
	CreateTopupOrder(ctx context.Context, in *CreateTopupOrderRequest, opts ...grpc.CallOption) (*CreateTopupOrderResponse, error)
	ConfirmTopupOrder(ctx context.Context, in *ConfirmTopupOrderRequest, opts ...grpc.CallOption) (*ConfirmTopupOrderResponse, error)
	GetTopupOrder(ctx context.Context, in *GetTopupOrderRequest, opts ...grpc.CallOption) (*GetTopupOrderResponse, error)
}

type donateTopupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDonateTopupServiceClient(cc grpc.ClientConnInterface) DonateTopupServiceClient {
	return &donateTopupServiceClient{cc}
}

func (c *donateTopupServiceClient) GetPayerProfile(ctx context.Context, in *GetPayerProfileRequest, opts ...grpc.CallOption) (*GetPayerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayerProfileResponse)
	err := c.cc.Invoke(ctx, DonateTopupService_GetPayerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateTopupServiceClient) SavePayerProfile(ctx context.Context, in *SavePayerProfileRequest, opts ...grpc.CallOption) (*SavePayerProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SavePayerProfileResponse)
	err := c.cc.Invoke(ctx, DonateTopupService_SavePayerProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateTopupServiceClient) CreateTopupOrder(ctx context.Context, in *CreateTopupOrderRequest, opts ...grpc.CallOption) (*CreateTopupOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTopupOrderResponse)
	err := c.cc.Invoke(ctx, DonateTopupService_CreateTopupOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateTopupServiceClient) ConfirmTopupOrder(ctx context.Context, in *ConfirmTopupOrderRequest, opts ...grpc.CallOption) (*ConfirmTopupOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmTopupOrderResponse)
	err := c.cc.Invoke(ctx, DonateTopupService_ConfirmTopupOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *donateTopupServiceClient) GetTopupOrder(ctx context.Context, in *GetTopupOrderRequest, opts ...grpc.CallOption) (*GetTopupOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopupOrderResponse)
	err := c.cc.Invoke(ctx, DonateTopupService_GetTopupOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DonateTopupServiceServer is the server API for DonateTopupService service.
// All implementations must embed UnimplementedDonateTopupServiceServer
// for forward compatibility.
//
// DonateTopupService is the payment-method-agnostic donate top-up surface the
// Next.js BFF calls server-side (never the browser). The portal owns no
// database: every durable order and the idempotency of the credit live here.
// PIX is the only method wired today, but the method is a FIELD of the order
// (payment_method), never part of an RPC or table name — credit card reuses the
// same RPCs and table later. The top-up credit happens INSIDE ConfirmTopupOrder,
// in the same transaction that flips the order to PAID and WITHOUT a moderator_id
// (unlike DonateAdminService.CreditDonateBalance), so a replayed webhook credits
// exactly once.
type DonateTopupServiceServer interface {
	// Payer profile (name + CPF), reused across a payer's top-ups.
	GetPayerProfile(context.Context, *GetPayerProfileRequest) (*GetPayerProfileResponse, error)
	SavePayerProfile(context.Context, *SavePayerProfileRequest) (*SavePayerProfileResponse, error)
	// CreateTopupOrder persists a PENDING order before the portal calls the
	// gateway (persist-before-provider). ConfirmTopupOrder credits the account
	// exactly once (idempotent on external_reference). GetTopupOrder is the poll.
	CreateTopupOrder(context.Context, *CreateTopupOrderRequest) (*CreateTopupOrderResponse, error)
	ConfirmTopupOrder(context.Context, *ConfirmTopupOrderRequest) (*ConfirmTopupOrderResponse, error)
	GetTopupOrder(context.Context, *GetTopupOrderRequest) (*GetTopupOrderResponse, error)
	mustEmbedUnimplementedDonateTopupServiceServer()
}

// UnimplementedDonateTopupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDonateTopupServiceServer struct{}

func (UnimplementedDonateTopupServiceServer) GetPayerProfile(context.Context, *GetPayerProfileRequest) (*GetPayerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayerProfile not implemented")
}
func (UnimplementedDonateTopupServiceServer) SavePayerProfile(context.Context, *SavePayerProfileRequest) (*SavePayerProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SavePayerProfile not implemented")
}
func (UnimplementedDonateTopupServiceServer) CreateTopupOrder(context.Context, *CreateTopupOrderRequest) (*CreateTopupOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTopupOrder not implemented")
}
func (UnimplementedDonateTopupServiceServer) ConfirmTopupOrder(context.Context, *ConfirmTopupOrderRequest) (*ConfirmTopupOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmTopupOrder not implemented")
}
func (UnimplementedDonateTopupServiceServer) GetTopupOrder(context.Context, *GetTopupOrderRequest) (*GetTopupOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopupOrder not implemented")
}
func (UnimplementedDonateTopupServiceServer) mustEmbedUnimplementedDonateTopupServiceServer() {}
func (UnimplementedDonateTopupServiceServer) testEmbeddedByValue()                            {}

// UnsafeDonateTopupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DonateTopupServiceServer will
// result in compilation errors.
type UnsafeDonateTopupServiceServer interface {
	mustEmbedUnimplementedDonateTopupServiceServer()
}

func RegisterDonateTopupServiceServer(s grpc.ServiceRegistrar, srv DonateTopupServiceServer) {
	// If the following call panics, it indicates UnimplementedDonateTopupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DonateTopupService_ServiceDesc, srv)
}

func _DonateTopupService_GetPayerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateTopupServiceServer).GetPayerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateTopupService_GetPayerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateTopupServiceServer).GetPayerProfile(ctx, req.(*GetPayerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateTopupService_SavePayerProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePayerProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateTopupServiceServer).SavePayerProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateTopupService_SavePayerProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateTopupServiceServer).SavePayerProfile(ctx, req.(*SavePayerProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateTopupService_CreateTopupOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTopupOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateTopupServiceServer).CreateTopupOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateTopupService_CreateTopupOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateTopupServiceServer).CreateTopupOrder(ctx, req.(*CreateTopupOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateTopupService_ConfirmTopupOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmTopupOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateTopupServiceServer).ConfirmTopupOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateTopupService_ConfirmTopupOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateTopupServiceServer).ConfirmTopupOrder(ctx, req.(*ConfirmTopupOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DonateTopupService_GetTopupOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopupOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DonateTopupServiceServer).GetTopupOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DonateTopupService_GetTopupOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DonateTopupServiceServer).GetTopupOrder(ctx, req.(*GetTopupOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DonateTopupService_ServiceDesc is the grpc.ServiceDesc for DonateTopupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DonateTopupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "web.v1.DonateTopupService",
	HandlerType: (*DonateTopupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPayerProfile",
			Handler:    _DonateTopupService_GetPayerProfile_Handler,
		},
		{
			MethodName: "SavePayerProfile",
			Handler:    _DonateTopupService_SavePayerProfile_Handler,
		},
		{
			MethodName: "CreateTopupOrder",
			Handler:    _DonateTopupService_CreateTopupOrder_Handler,
		},
		{
			MethodName: "ConfirmTopupOrder",
			Handler:    _DonateTopupService_ConfirmTopupOrder_Handler,
		},
		{
			MethodName: "GetTopupOrder",
			Handler:    _DonateTopupService_GetTopupOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/web/v1/web.proto",
}
