// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/db/v1/db.proto

// Internal contract between tmServer and dbServer (migration-plan.md §3.5).
// This link is modern (gRPC + mTLS), NOT the legacy CPSock — only the client
// edge is bound to the old protocol. The RPCs mirror the legacy G↔DB messages
// in protocol-spec.md §3.3 (DBAccountLogin, DBCharacterLogin, DBSaveMob, …).
//
// Code generation and the server implementation land in Phase 3, when tmServer
// becomes the consumer. Generate with `make proto`.

package dbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginResult int32

const (
	LoginResult_LOGIN_RESULT_UNSPECIFIED     LoginResult = 0
	LoginResult_LOGIN_RESULT_OK              LoginResult = 1
	LoginResult_LOGIN_RESULT_NO_ACCOUNT      LoginResult = 2 // _MSG_DBAccountLoginFail_Account
	LoginResult_LOGIN_RESULT_BAD_PASSWORD    LoginResult = 3 // _MSG_DBAccountLoginFail_Pass
	LoginResult_LOGIN_RESULT_BLOCKED         LoginResult = 4 // _MSG_DBAccountLoginFail_Block
	LoginResult_LOGIN_RESULT_ALREADY_PLAYING LoginResult = 5
)

// Enum value maps for LoginResult.
var (
	LoginResult_name = map[int32]string{
		0: "LOGIN_RESULT_UNSPECIFIED",
		1: "LOGIN_RESULT_OK",
		2: "LOGIN_RESULT_NO_ACCOUNT",
		3: "LOGIN_RESULT_BAD_PASSWORD",
		4: "LOGIN_RESULT_BLOCKED",
		5: "LOGIN_RESULT_ALREADY_PLAYING",
	}
	LoginResult_value = map[string]int32{
		"LOGIN_RESULT_UNSPECIFIED":     0,
		"LOGIN_RESULT_OK":              1,
		"LOGIN_RESULT_NO_ACCOUNT":      2,
		"LOGIN_RESULT_BAD_PASSWORD":    3,
		"LOGIN_RESULT_BLOCKED":         4,
		"LOGIN_RESULT_ALREADY_PLAYING": 5,
	}
)

func (x LoginResult) Enum() *LoginResult {
	p := new(LoginResult)
	*p = x
	return p
}

func (x LoginResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginResult) Descriptor() protoreflect.EnumDescriptor {
	return file_api_db_v1_db_proto_enumTypes[0].Descriptor()
}

func (LoginResult) Type() protoreflect.EnumType {
	return &file_api_db_v1_db_proto_enumTypes[0]
}

func (x LoginResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginResult.Descriptor instead.
func (LoginResult) EnumDescriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{0}
}

type AccountLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"` // canonical lowercase
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`                          // verified against the stored argon2id hash
	ClientVersion int32                  `protobuf:"varint,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountLoginRequest) Reset() {
	*x = AccountLoginRequest{}
	mi := &file_api_db_v1_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginRequest) ProtoMessage() {}

func (x *AccountLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginRequest.ProtoReflect.Descriptor instead.
func (*AccountLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{0}
}

func (x *AccountLoginRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AccountLoginRequest) GetClientVersion() int32 {
	if x != nil {
		return x.ClientVersion
	}
	return 0
}

type AccountLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        LoginResult            `protobuf:"varint,1,opt,name=result,proto3,enum=db.v1.LoginResult" json:"result,omitempty"`
	AccountId     int64                  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountLoginResponse) Reset() {
	*x = AccountLoginResponse{}
	mi := &file_api_db_v1_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLoginResponse) ProtoMessage() {}

func (x *AccountLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLoginResponse.ProtoReflect.Descriptor instead.
func (*AccountLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{1}
}

func (x *AccountLoginResponse) GetResult() LoginResult {
	if x != nil {
		return x.Result
	}
	return LoginResult_LOGIN_RESULT_UNSPECIFIED
}

func (x *AccountLoginResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type ListCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersRequest) Reset() {
	*x = ListCharactersRequest{}
	mi := &file_api_db_v1_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersRequest) ProtoMessage() {}

func (x *ListCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersRequest.ProtoReflect.Descriptor instead.
func (*ListCharactersRequest) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{2}
}

func (x *ListCharactersRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type CharacterSummary struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Slot    int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Class   int32                  `protobuf:"varint,3,opt,name=class,proto3" json:"class,omitempty"`
	Level   int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp     int64                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	GuildId uint32                 `protobuf:"varint,6,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	// Score preview shown on the character-selection screen (STRUCT_SELCHAR).
	Coin          int32 `protobuf:"varint,7,opt,name=coin,proto3" json:"coin,omitempty"`
	MaxHp         int32 `protobuf:"varint,8,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	Hp            int32 `protobuf:"varint,9,opt,name=hp,proto3" json:"hp,omitempty"`
	MaxMp         int32 `protobuf:"varint,10,opt,name=max_mp,json=maxMp,proto3" json:"max_mp,omitempty"`
	Mp            int32 `protobuf:"varint,11,opt,name=mp,proto3" json:"mp,omitempty"`
	Str           int32 `protobuf:"varint,12,opt,name=str,proto3" json:"str,omitempty"`
	Int           int32 `protobuf:"varint,13,opt,name=int,proto3" json:"int,omitempty"`
	Dex           int32 `protobuf:"varint,14,opt,name=dex,proto3" json:"dex,omitempty"`
	Con           int32 `protobuf:"varint,15,opt,name=con,proto3" json:"con,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterSummary) Reset() {
	*x = CharacterSummary{}
	mi := &file_api_db_v1_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterSummary) ProtoMessage() {}

func (x *CharacterSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterSummary.ProtoReflect.Descriptor instead.
func (*CharacterSummary) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{3}
}

func (x *CharacterSummary) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CharacterSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterSummary) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *CharacterSummary) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CharacterSummary) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *CharacterSummary) GetGuildId() uint32 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *CharacterSummary) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *CharacterSummary) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *CharacterSummary) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *CharacterSummary) GetMaxMp() int32 {
	if x != nil {
		return x.MaxMp
	}
	return 0
}

func (x *CharacterSummary) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *CharacterSummary) GetStr() int32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *CharacterSummary) GetInt() int32 {
	if x != nil {
		return x.Int
	}
	return 0
}

func (x *CharacterSummary) GetDex() int32 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *CharacterSummary) GetCon() int32 {
	if x != nil {
		return x.Con
	}
	return 0
}

type ListCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*CharacterSummary    `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCharactersResponse) Reset() {
	*x = ListCharactersResponse{}
	mi := &file_api_db_v1_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCharactersResponse) ProtoMessage() {}

func (x *ListCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCharactersResponse.ProtoReflect.Descriptor instead.
func (*ListCharactersResponse) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{4}
}

func (x *ListCharactersResponse) GetCharacters() []*CharacterSummary {
	if x != nil {
		return x.Characters
	}
	return nil
}

type LoadCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCharacterRequest) Reset() {
	*x = LoadCharacterRequest{}
	mi := &file_api_db_v1_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCharacterRequest) ProtoMessage() {}

func (x *LoadCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCharacterRequest.ProtoReflect.Descriptor instead.
func (*LoadCharacterRequest) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{5}
}

func (x *LoadCharacterRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *LoadCharacterRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

// Character carries the relational character state (domain.Character). Equip,
// carry and affects are normalized lists; empty item slots are omitted.
type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Class         int32                  `protobuf:"varint,3,opt,name=class,proto3" json:"class,omitempty"`
	Clan          int32                  `protobuf:"varint,4,opt,name=clan,proto3" json:"clan,omitempty"`
	GuildId       uint32                 `protobuf:"varint,5,opt,name=guild_id,json=guildId,proto3" json:"guild_id,omitempty"`
	Level         int32                  `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int64                  `protobuf:"varint,7,opt,name=exp,proto3" json:"exp,omitempty"`
	Coin          int32                  `protobuf:"varint,8,opt,name=coin,proto3" json:"coin,omitempty"`
	Str           int32                  `protobuf:"varint,9,opt,name=str,proto3" json:"str,omitempty"`
	Int           int32                  `protobuf:"varint,10,opt,name=int,proto3" json:"int,omitempty"`
	Dex           int32                  `protobuf:"varint,11,opt,name=dex,proto3" json:"dex,omitempty"`
	Con           int32                  `protobuf:"varint,12,opt,name=con,proto3" json:"con,omitempty"`
	MaxHp         int32                  `protobuf:"varint,13,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	MaxMp         int32                  `protobuf:"varint,14,opt,name=max_mp,json=maxMp,proto3" json:"max_mp,omitempty"`
	Hp            int32                  `protobuf:"varint,15,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp            int32                  `protobuf:"varint,16,opt,name=mp,proto3" json:"mp,omitempty"`
	Equip         []*Item                `protobuf:"bytes,17,rep,name=equip,proto3" json:"equip,omitempty"`
	Carry         []*Item                `protobuf:"bytes,18,rep,name=carry,proto3" json:"carry,omitempty"`
	Affects       []*Affect              `protobuf:"bytes,19,rep,name=affects,proto3" json:"affects,omitempty"`
	LastCity      int32                  `protobuf:"varint,20,opt,name=last_city,json=lastCity,proto3" json:"last_city,omitempty"` // last city visited (0..3); spawn = that city's default area
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_api_db_v1_db_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{6}
}

func (x *Character) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

func (x *Character) GetClan() int32 {
	if x != nil {
		return x.Clan
	}
	return 0
}

func (x *Character) GetGuildId() uint32 {
	if x != nil {
		return x.GuildId
	}
	return 0
}

func (x *Character) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Character) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *Character) GetStr() int32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *Character) GetInt() int32 {
	if x != nil {
		return x.Int
	}
	return 0
}

func (x *Character) GetDex() int32 {
	if x != nil {
		return x.Dex
	}
	return 0
}

func (x *Character) GetCon() int32 {
	if x != nil {
		return x.Con
	}
	return 0
}

func (x *Character) GetMaxHp() int32 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *Character) GetMaxMp() int32 {
	if x != nil {
		return x.MaxMp
	}
	return 0
}

func (x *Character) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Character) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *Character) GetEquip() []*Item {
	if x != nil {
		return x.Equip
	}
	return nil
}

func (x *Character) GetCarry() []*Item {
	if x != nil {
		return x.Carry
	}
	return nil
}

func (x *Character) GetAffects() []*Affect {
	if x != nil {
		return x.Affects
	}
	return nil
}

func (x *Character) GetLastCity() int32 {
	if x != nil {
		return x.LastCity
	}
	return 0
}

type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Slot  int32                  `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Index int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Eff1  int32                  `protobuf:"varint,3,opt,name=eff1,proto3" json:"eff1,omitempty"`
	Effv1 int32                  `protobuf:"varint,4,opt,name=effv1,proto3" json:"effv1,omitempty"`
	Eff2  int32                  `protobuf:"varint,5,opt,name=eff2,proto3" json:"eff2,omitempty"`
	Effv2 int32                  `protobuf:"varint,6,opt,name=effv2,proto3" json:"effv2,omitempty"`
	Eff3  int32                  `protobuf:"varint,7,opt,name=eff3,proto3" json:"eff3,omitempty"`
	Effv3 int32                  `protobuf:"varint,8,opt,name=effv3,proto3" json:"effv3,omitempty"`
	// Unix-seconds expiry for timed items (0 = permanent). Set on grant (e.g. the
	// 30-day Perzen mount); the world drops the item once it passes.
	ExpiresAt     int64 `protobuf:"varint,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_db_v1_db_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{7}
}

func (x *Item) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *Item) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Item) GetEff1() int32 {
	if x != nil {
		return x.Eff1
	}
	return 0
}

func (x *Item) GetEffv1() int32 {
	if x != nil {
		return x.Effv1
	}
	return 0
}

func (x *Item) GetEff2() int32 {
	if x != nil {
		return x.Eff2
	}
	return 0
}

func (x *Item) GetEffv2() int32 {
	if x != nil {
		return x.Effv2
	}
	return 0
}

func (x *Item) GetEff3() int32 {
	if x != nil {
		return x.Eff3
	}
	return 0
}

func (x *Item) GetEffv3() int32 {
	if x != nil {
		return x.Effv3
	}
	return 0
}

func (x *Item) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type Affect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Time          uint32                 `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Affect) Reset() {
	*x = Affect{}
	mi := &file_api_db_v1_db_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Affect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Affect) ProtoMessage() {}

func (x *Affect) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Affect.ProtoReflect.Descriptor instead.
func (*Affect) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{8}
}

func (x *Affect) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Affect) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Affect) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Affect) GetTime() uint32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type LoadCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCharacterResponse) Reset() {
	*x = LoadCharacterResponse{}
	mi := &file_api_db_v1_db_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCharacterResponse) ProtoMessage() {}

func (x *LoadCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCharacterResponse.ProtoReflect.Descriptor instead.
func (*LoadCharacterResponse) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{9}
}

func (x *LoadCharacterResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type SaveCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Character     *Character             `protobuf:"bytes,2,opt,name=character,proto3" json:"character,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCharacterRequest) Reset() {
	*x = SaveCharacterRequest{}
	mi := &file_api_db_v1_db_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCharacterRequest) ProtoMessage() {}

func (x *SaveCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCharacterRequest.ProtoReflect.Descriptor instead.
func (*SaveCharacterRequest) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{10}
}

func (x *SaveCharacterRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SaveCharacterRequest) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

type SaveCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCharacterResponse) Reset() {
	*x = SaveCharacterResponse{}
	mi := &file_api_db_v1_db_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCharacterResponse) ProtoMessage() {}

func (x *SaveCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCharacterResponse.ProtoReflect.Descriptor instead.
func (*SaveCharacterResponse) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{11}
}

func (x *SaveCharacterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Class         int32                  `protobuf:"varint,4,opt,name=class,proto3" json:"class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_api_db_v1_db_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{12}
}

func (x *CreateCharacterRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateCharacterRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCharacterRequest) GetClass() int32 {
	if x != nil {
		return x.Class
	}
	return 0
}

type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	CharacterId   int64                  `protobuf:"varint,2,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_api_db_v1_db_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{13}
}

func (x *CreateCharacterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateCharacterResponse) GetCharacterId() int64 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type DeleteCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Slot          int32                  `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterRequest) Reset() {
	*x = DeleteCharacterRequest{}
	mi := &file_api_db_v1_db_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterRequest) ProtoMessage() {}

func (x *DeleteCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterRequest.ProtoReflect.Descriptor instead.
func (*DeleteCharacterRequest) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteCharacterRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *DeleteCharacterRequest) GetSlot() int32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *DeleteCharacterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCharacterResponse) Reset() {
	*x = DeleteCharacterResponse{}
	mi := &file_api_db_v1_db_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCharacterResponse) ProtoMessage() {}

func (x *DeleteCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCharacterResponse.ProtoReflect.Descriptor instead.
func (*DeleteCharacterResponse) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteCharacterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

// Cargo is the account-shared warehouse (domain.Account.CargoCoin + Cargo). It is
// keyed by account_id (NOT character) because all of an account's characters
// deposit into and withdraw from the same vault. Empty item slots are omitted.
type LoadCargoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCargoRequest) Reset() {
	*x = LoadCargoRequest{}
	mi := &file_api_db_v1_db_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCargoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCargoRequest) ProtoMessage() {}

func (x *LoadCargoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCargoRequest.ProtoReflect.Descriptor instead.
func (*LoadCargoRequest) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{16}
}

func (x *LoadCargoRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type LoadCargoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CargoCoin     int32                  `protobuf:"varint,1,opt,name=cargo_coin,json=cargoCoin,proto3" json:"cargo_coin,omitempty"`
	Items         []*Item                `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCargoResponse) Reset() {
	*x = LoadCargoResponse{}
	mi := &file_api_db_v1_db_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCargoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCargoResponse) ProtoMessage() {}

func (x *LoadCargoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCargoResponse.ProtoReflect.Descriptor instead.
func (*LoadCargoResponse) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{17}
}

func (x *LoadCargoResponse) GetCargoCoin() int32 {
	if x != nil {
		return x.CargoCoin
	}
	return 0
}

func (x *LoadCargoResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type SaveCargoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CargoCoin     int32                  `protobuf:"varint,2,opt,name=cargo_coin,json=cargoCoin,proto3" json:"cargo_coin,omitempty"`
	Items         []*Item                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCargoRequest) Reset() {
	*x = SaveCargoRequest{}
	mi := &file_api_db_v1_db_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCargoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCargoRequest) ProtoMessage() {}

func (x *SaveCargoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCargoRequest.ProtoReflect.Descriptor instead.
func (*SaveCargoRequest) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{18}
}

func (x *SaveCargoRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SaveCargoRequest) GetCargoCoin() int32 {
	if x != nil {
		return x.CargoCoin
	}
	return 0
}

func (x *SaveCargoRequest) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type SaveCargoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveCargoResponse) Reset() {
	*x = SaveCargoResponse{}
	mi := &file_api_db_v1_db_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveCargoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveCargoResponse) ProtoMessage() {}

func (x *SaveCargoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_v1_db_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveCargoResponse.ProtoReflect.Descriptor instead.
func (*SaveCargoResponse) Descriptor() ([]byte, []int) {
	return file_api_db_v1_db_proto_rawDescGZIP(), []int{19}
}

func (x *SaveCargoResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_db_v1_db_proto protoreflect.FileDescriptor

const file_api_db_v1_db_proto_rawDesc = "" +
	"\n" +
	"\x12api/db/v1/db.proto\x12\x05db.v1\"{\n" +
	"\x13AccountLoginRequest\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\x05R\rclientVersion\"a\n" +
	"\x14AccountLoginResponse\x12*\n" +
	"\x06result\x18\x01 \x01(\x0e2\x12.db.v1.LoginResultR\x06result\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\x03R\taccountId\"6\n" +
	"\x15ListCharactersRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\"\xbd\x02\n" +
	"\x10CharacterSummary\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05class\x18\x03 \x01(\x05R\x05class\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x03R\x03exp\x12\x19\n" +
	"\bguild_id\x18\x06 \x01(\rR\aguildId\x12\x12\n" +
	"\x04coin\x18\a \x01(\x05R\x04coin\x12\x15\n" +
	"\x06max_hp\x18\b \x01(\x05R\x05maxHp\x12\x0e\n" +
	"\x02hp\x18\t \x01(\x05R\x02hp\x12\x15\n" +
	"\x06max_mp\x18\n" +
	" \x01(\x05R\x05maxMp\x12\x0e\n" +
	"\x02mp\x18\v \x01(\x05R\x02mp\x12\x10\n" +
	"\x03str\x18\f \x01(\x05R\x03str\x12\x10\n" +
	"\x03int\x18\r \x01(\x05R\x03int\x12\x10\n" +
	"\x03dex\x18\x0e \x01(\x05R\x03dex\x12\x10\n" +
	"\x03con\x18\x0f \x01(\x05R\x03con\"Q\n" +
	"\x16ListCharactersResponse\x127\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x17.db.v1.CharacterSummaryR\n" +
	"characters\"I\n" +
	"\x14LoadCharacterRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\"\xd6\x03\n" +
	"\tCharacter\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05class\x18\x03 \x01(\x05R\x05class\x12\x12\n" +
	"\x04clan\x18\x04 \x01(\x05R\x04clan\x12\x19\n" +
	"\bguild_id\x18\x05 \x01(\rR\aguildId\x12\x14\n" +
	"\x05level\x18\x06 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\a \x01(\x03R\x03exp\x12\x12\n" +
	"\x04coin\x18\b \x01(\x05R\x04coin\x12\x10\n" +
	"\x03str\x18\t \x01(\x05R\x03str\x12\x10\n" +
	"\x03int\x18\n" +
	" \x01(\x05R\x03int\x12\x10\n" +
	"\x03dex\x18\v \x01(\x05R\x03dex\x12\x10\n" +
	"\x03con\x18\f \x01(\x05R\x03con\x12\x15\n" +
	"\x06max_hp\x18\r \x01(\x05R\x05maxHp\x12\x15\n" +
	"\x06max_mp\x18\x0e \x01(\x05R\x05maxMp\x12\x0e\n" +
	"\x02hp\x18\x0f \x01(\x05R\x02hp\x12\x0e\n" +
	"\x02mp\x18\x10 \x01(\x05R\x02mp\x12!\n" +
	"\x05equip\x18\x11 \x03(\v2\v.db.v1.ItemR\x05equip\x12!\n" +
	"\x05carry\x18\x12 \x03(\v2\v.db.v1.ItemR\x05carry\x12'\n" +
	"\aaffects\x18\x13 \x03(\v2\r.db.v1.AffectR\aaffects\x12\x1b\n" +
	"\tlast_city\x18\x14 \x01(\x05R\blastCity\"\xcd\x01\n" +
	"\x04Item\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x05R\x04slot\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x12\n" +
	"\x04eff1\x18\x03 \x01(\x05R\x04eff1\x12\x14\n" +
	"\x05effv1\x18\x04 \x01(\x05R\x05effv1\x12\x12\n" +
	"\x04eff2\x18\x05 \x01(\x05R\x04eff2\x12\x14\n" +
	"\x05effv2\x18\x06 \x01(\x05R\x05effv2\x12\x12\n" +
	"\x04eff3\x18\a \x01(\x05R\x04eff3\x12\x14\n" +
	"\x05effv3\x18\b \x01(\x05R\x05effv3\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\x03R\texpiresAt\"\\\n" +
	"\x06Affect\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04time\x18\x04 \x01(\rR\x04time\"G\n" +
	"\x15LoadCharacterResponse\x12.\n" +
	"\tcharacter\x18\x01 \x01(\v2\x10.db.v1.CharacterR\tcharacter\"e\n" +
	"\x14SaveCharacterRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12.\n" +
	"\tcharacter\x18\x02 \x01(\v2\x10.db.v1.CharacterR\tcharacter\"'\n" +
	"\x15SaveCharacterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"u\n" +
	"\x16CreateCharacterRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05class\x18\x04 \x01(\x05R\x05class\"L\n" +
	"\x17CreateCharacterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12!\n" +
	"\fcharacter_id\x18\x02 \x01(\x03R\vcharacterId\"g\n" +
	"\x16DeleteCharacterRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x05R\x04slot\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\")\n" +
	"\x17DeleteCharacterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"1\n" +
	"\x10LoadCargoRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\"U\n" +
	"\x11LoadCargoResponse\x12\x1d\n" +
	"\n" +
	"cargo_coin\x18\x01 \x01(\x05R\tcargoCoin\x12!\n" +
	"\x05items\x18\x02 \x03(\v2\v.db.v1.ItemR\x05items\"s\n" +
	"\x10SaveCargoRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1d\n" +
	"\n" +
	"cargo_coin\x18\x02 \x01(\x05R\tcargoCoin\x12!\n" +
	"\x05items\x18\x03 \x03(\v2\v.db.v1.ItemR\x05items\"#\n" +
	"\x11SaveCargoResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*\xb8\x01\n" +
	"\vLoginResult\x12\x1c\n" +
	"\x18LOGIN_RESULT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fLOGIN_RESULT_OK\x10\x01\x12\x1b\n" +
	"\x17LOGIN_RESULT_NO_ACCOUNT\x10\x02\x12\x1d\n" +
	"\x19LOGIN_RESULT_BAD_PASSWORD\x10\x03\x12\x18\n" +
	"\x14LOGIN_RESULT_BLOCKED\x10\x04\x12 \n" +
	"\x1cLOGIN_RESULT_ALREADY_PLAYING\x10\x052\xe4\x04\n" +
	"\x0eAccountService\x12G\n" +
	"\fAccountLogin\x12\x1a.db.v1.AccountLoginRequest\x1a\x1b.db.v1.AccountLoginResponse\x12M\n" +
	"\x0eListCharacters\x12\x1c.db.v1.ListCharactersRequest\x1a\x1d.db.v1.ListCharactersResponse\x12J\n" +
	"\rLoadCharacter\x12\x1b.db.v1.LoadCharacterRequest\x1a\x1c.db.v1.LoadCharacterResponse\x12J\n" +
	"\rSaveCharacter\x12\x1b.db.v1.SaveCharacterRequest\x1a\x1c.db.v1.SaveCharacterResponse\x12P\n" +
	"\x0fCreateCharacter\x12\x1d.db.v1.CreateCharacterRequest\x1a\x1e.db.v1.CreateCharacterResponse\x12P\n" +
	"\x0fDeleteCharacter\x12\x1d.db.v1.DeleteCharacterRequest\x1a\x1e.db.v1.DeleteCharacterResponse\x12>\n" +
	"\tLoadCargo\x12\x17.db.v1.LoadCargoRequest\x1a\x18.db.v1.LoadCargoResponse\x12>\n" +
	"\tSaveCargo\x12\x17.db.v1.SaveCargoRequest\x1a\x18.db.v1.SaveCargoResponseB1Z/github.com/jeanluca/w2pp-openwyd/api/db/v1;dbv1b\x06proto3"

var (
	file_api_db_v1_db_proto_rawDescOnce sync.Once
	file_api_db_v1_db_proto_rawDescData []byte
)

func file_api_db_v1_db_proto_rawDescGZIP() []byte {
	file_api_db_v1_db_proto_rawDescOnce.Do(func() {
		file_api_db_v1_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_db_v1_db_proto_rawDesc), len(file_api_db_v1_db_proto_rawDesc)))
	})
	return file_api_db_v1_db_proto_rawDescData
}

var file_api_db_v1_db_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_db_v1_db_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_api_db_v1_db_proto_goTypes = []any{
	(LoginResult)(0),                // 0: db.v1.LoginResult
	(*AccountLoginRequest)(nil),     // 1: db.v1.AccountLoginRequest
	(*AccountLoginResponse)(nil),    // 2: db.v1.AccountLoginResponse
	(*ListCharactersRequest)(nil),   // 3: db.v1.ListCharactersRequest
	(*CharacterSummary)(nil),        // 4: db.v1.CharacterSummary
	(*ListCharactersResponse)(nil),  // 5: db.v1.ListCharactersResponse
	(*LoadCharacterRequest)(nil),    // 6: db.v1.LoadCharacterRequest
	(*Character)(nil),               // 7: db.v1.Character
	(*Item)(nil),                    // 8: db.v1.Item
	(*Affect)(nil),                  // 9: db.v1.Affect
	(*LoadCharacterResponse)(nil),   // 10: db.v1.LoadCharacterResponse
	(*SaveCharacterRequest)(nil),    // 11: db.v1.SaveCharacterRequest
	(*SaveCharacterResponse)(nil),   // 12: db.v1.SaveCharacterResponse
	(*CreateCharacterRequest)(nil),  // 13: db.v1.CreateCharacterRequest
	(*CreateCharacterResponse)(nil), // 14: db.v1.CreateCharacterResponse
	(*DeleteCharacterRequest)(nil),  // 15: db.v1.DeleteCharacterRequest
	(*DeleteCharacterResponse)(nil), // 16: db.v1.DeleteCharacterResponse
	(*LoadCargoRequest)(nil),        // 17: db.v1.LoadCargoRequest
	(*LoadCargoResponse)(nil),       // 18: db.v1.LoadCargoResponse
	(*SaveCargoRequest)(nil),        // 19: db.v1.SaveCargoRequest
	(*SaveCargoResponse)(nil),       // 20: db.v1.SaveCargoResponse
}
var file_api_db_v1_db_proto_depIdxs = []int32{
	0,  // 0: db.v1.AccountLoginResponse.result:type_name -> db.v1.LoginResult
	4,  // 1: db.v1.ListCharactersResponse.characters:type_name -> db.v1.CharacterSummary
	8,  // 2: db.v1.Character.equip:type_name -> db.v1.Item
	8,  // 3: db.v1.Character.carry:type_name -> db.v1.Item
	9,  // 4: db.v1.Character.affects:type_name -> db.v1.Affect
	7,  // 5: db.v1.LoadCharacterResponse.character:type_name -> db.v1.Character
	7,  // 6: db.v1.SaveCharacterRequest.character:type_name -> db.v1.Character
	8,  // 7: db.v1.LoadCargoResponse.items:type_name -> db.v1.Item
	8,  // 8: db.v1.SaveCargoRequest.items:type_name -> db.v1.Item
	1,  // 9: db.v1.AccountService.AccountLogin:input_type -> db.v1.AccountLoginRequest
	3,  // 10: db.v1.AccountService.ListCharacters:input_type -> db.v1.ListCharactersRequest
	6,  // 11: db.v1.AccountService.LoadCharacter:input_type -> db.v1.LoadCharacterRequest
	11, // 12: db.v1.AccountService.SaveCharacter:input_type -> db.v1.SaveCharacterRequest
	13, // 13: db.v1.AccountService.CreateCharacter:input_type -> db.v1.CreateCharacterRequest
	15, // 14: db.v1.AccountService.DeleteCharacter:input_type -> db.v1.DeleteCharacterRequest
	17, // 15: db.v1.AccountService.LoadCargo:input_type -> db.v1.LoadCargoRequest
	19, // 16: db.v1.AccountService.SaveCargo:input_type -> db.v1.SaveCargoRequest
	2,  // 17: db.v1.AccountService.AccountLogin:output_type -> db.v1.AccountLoginResponse
	5,  // 18: db.v1.AccountService.ListCharacters:output_type -> db.v1.ListCharactersResponse
	10, // 19: db.v1.AccountService.LoadCharacter:output_type -> db.v1.LoadCharacterResponse
	12, // 20: db.v1.AccountService.SaveCharacter:output_type -> db.v1.SaveCharacterResponse
	14, // 21: db.v1.AccountService.CreateCharacter:output_type -> db.v1.CreateCharacterResponse
	16, // 22: db.v1.AccountService.DeleteCharacter:output_type -> db.v1.DeleteCharacterResponse
	18, // 23: db.v1.AccountService.LoadCargo:output_type -> db.v1.LoadCargoResponse
	20, // 24: db.v1.AccountService.SaveCargo:output_type -> db.v1.SaveCargoResponse
	17, // [17:25] is the sub-list for method output_type
	9,  // [9:17] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_db_v1_db_proto_init() }
func file_api_db_v1_db_proto_init() {
	if File_api_db_v1_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_db_v1_db_proto_rawDesc), len(file_api_db_v1_db_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_db_v1_db_proto_goTypes,
		DependencyIndexes: file_api_db_v1_db_proto_depIdxs,
		EnumInfos:         file_api_db_v1_db_proto_enumTypes,
		MessageInfos:      file_api_db_v1_db_proto_msgTypes,
	}.Build()
	File_api_db_v1_db_proto = out.File
	file_api_db_v1_db_proto_goTypes = nil
	file_api_db_v1_db_proto_depIdxs = nil
}
