// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/db/v1/db.proto

// Internal contract between tmServer and dbServer (migration-plan.md §3.5).
// This link is modern (gRPC + mTLS), NOT the legacy CPSock — only the client
// edge is bound to the old protocol. The RPCs mirror the legacy G↔DB messages
// in protocol-spec.md §3.3 (DBAccountLogin, DBCharacterLogin, DBSaveMob, …).
//
// Code generation and the server implementation land in Phase 3, when tmServer
// becomes the consumer. Generate with `make proto`.

package dbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_AccountLogin_FullMethodName    = "/db.v1.AccountService/AccountLogin"
	AccountService_ListCharacters_FullMethodName  = "/db.v1.AccountService/ListCharacters"
	AccountService_LoadCharacter_FullMethodName   = "/db.v1.AccountService/LoadCharacter"
	AccountService_SaveCharacter_FullMethodName   = "/db.v1.AccountService/SaveCharacter"
	AccountService_CreateCharacter_FullMethodName = "/db.v1.AccountService/CreateCharacter"
	AccountService_DeleteCharacter_FullMethodName = "/db.v1.AccountService/DeleteCharacter"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountService owns accounts, characters and persistence (PostgreSQL).
type AccountServiceClient interface {
	// AccountLogin validates an account name + password (legacy _MSG_DBAccountLogin).
	AccountLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error)
	// ListCharacters returns the character-selection projection for an account.
	ListCharacters(ctx context.Context, in *ListCharactersRequest, opts ...grpc.CallOption) (*ListCharactersResponse, error)
	// LoadCharacter loads one character's full state by slot (_MSG_DBCharacterLogin).
	LoadCharacter(ctx context.Context, in *LoadCharacterRequest, opts ...grpc.CallOption) (*LoadCharacterResponse, error)
	// SaveCharacter persists one character's state (_MSG_DBSaveMob / SavingQuit).
	SaveCharacter(ctx context.Context, in *SaveCharacterRequest, opts ...grpc.CallOption) (*SaveCharacterResponse, error)
	// CreateCharacter creates a character in a free slot (_MSG_DBCreateCharacter).
	CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error)
	// DeleteCharacter deletes a character after password confirmation.
	DeleteCharacter(ctx context.Context, in *DeleteCharacterRequest, opts ...grpc.CallOption) (*DeleteCharacterResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) AccountLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountLoginResponse)
	err := c.cc.Invoke(ctx, AccountService_AccountLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListCharacters(ctx context.Context, in *ListCharactersRequest, opts ...grpc.CallOption) (*ListCharactersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCharactersResponse)
	err := c.cc.Invoke(ctx, AccountService_ListCharacters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) LoadCharacter(ctx context.Context, in *LoadCharacterRequest, opts ...grpc.CallOption) (*LoadCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadCharacterResponse)
	err := c.cc.Invoke(ctx, AccountService_LoadCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SaveCharacter(ctx context.Context, in *SaveCharacterRequest, opts ...grpc.CallOption) (*SaveCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCharacterResponse)
	err := c.cc.Invoke(ctx, AccountService_SaveCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCharacterResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteCharacter(ctx context.Context, in *DeleteCharacterRequest, opts ...grpc.CallOption) (*DeleteCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCharacterResponse)
	err := c.cc.Invoke(ctx, AccountService_DeleteCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// AccountService owns accounts, characters and persistence (PostgreSQL).
type AccountServiceServer interface {
	// AccountLogin validates an account name + password (legacy _MSG_DBAccountLogin).
	AccountLogin(context.Context, *AccountLoginRequest) (*AccountLoginResponse, error)
	// ListCharacters returns the character-selection projection for an account.
	ListCharacters(context.Context, *ListCharactersRequest) (*ListCharactersResponse, error)
	// LoadCharacter loads one character's full state by slot (_MSG_DBCharacterLogin).
	LoadCharacter(context.Context, *LoadCharacterRequest) (*LoadCharacterResponse, error)
	// SaveCharacter persists one character's state (_MSG_DBSaveMob / SavingQuit).
	SaveCharacter(context.Context, *SaveCharacterRequest) (*SaveCharacterResponse, error)
	// CreateCharacter creates a character in a free slot (_MSG_DBCreateCharacter).
	CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error)
	// DeleteCharacter deletes a character after password confirmation.
	DeleteCharacter(context.Context, *DeleteCharacterRequest) (*DeleteCharacterResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) AccountLogin(context.Context, *AccountLoginRequest) (*AccountLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AccountLogin not implemented")
}
func (UnimplementedAccountServiceServer) ListCharacters(context.Context, *ListCharactersRequest) (*ListCharactersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCharacters not implemented")
}
func (UnimplementedAccountServiceServer) LoadCharacter(context.Context, *LoadCharacterRequest) (*LoadCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadCharacter not implemented")
}
func (UnimplementedAccountServiceServer) SaveCharacter(context.Context, *SaveCharacterRequest) (*SaveCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCharacter not implemented")
}
func (UnimplementedAccountServiceServer) CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCharacter not implemented")
}
func (UnimplementedAccountServiceServer) DeleteCharacter(context.Context, *DeleteCharacterRequest) (*DeleteCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCharacter not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_AccountLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AccountLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountLogin(ctx, req.(*AccountLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCharactersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListCharacters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListCharacters(ctx, req.(*ListCharactersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_LoadCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).LoadCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_LoadCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).LoadCharacter(ctx, req.(*LoadCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SaveCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SaveCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SaveCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SaveCharacter(ctx, req.(*SaveCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateCharacter(ctx, req.(*CreateCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_DeleteCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteCharacter(ctx, req.(*DeleteCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "db.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountLogin",
			Handler:    _AccountService_AccountLogin_Handler,
		},
		{
			MethodName: "ListCharacters",
			Handler:    _AccountService_ListCharacters_Handler,
		},
		{
			MethodName: "LoadCharacter",
			Handler:    _AccountService_LoadCharacter_Handler,
		},
		{
			MethodName: "SaveCharacter",
			Handler:    _AccountService_SaveCharacter_Handler,
		},
		{
			MethodName: "CreateCharacter",
			Handler:    _AccountService_CreateCharacter_Handler,
		},
		{
			MethodName: "DeleteCharacter",
			Handler:    _AccountService_DeleteCharacter_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/db/v1/db.proto",
}
