// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/db/v1/db.proto

// Internal contract between tmServer and dbServer (migration-plan.md §3.5).
// This link is modern (gRPC + mTLS), NOT the legacy CPSock — only the client
// edge is bound to the old protocol. The RPCs mirror the legacy G↔DB messages
// in protocol-spec.md §3.3 (DBAccountLogin, DBCharacterLogin, DBSaveMob, …).
//
// Code generation and the server implementation land in Phase 3, when tmServer
// becomes the consumer. Generate with `make proto`.

package dbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_AccountLogin_FullMethodName            = "/db.v1.AccountService/AccountLogin"
	AccountService_ListCharacters_FullMethodName          = "/db.v1.AccountService/ListCharacters"
	AccountService_LoadCharacter_FullMethodName           = "/db.v1.AccountService/LoadCharacter"
	AccountService_SaveCharacter_FullMethodName           = "/db.v1.AccountService/SaveCharacter"
	AccountService_CreateCharacter_FullMethodName         = "/db.v1.AccountService/CreateCharacter"
	AccountService_CreateArchCharacter_FullMethodName     = "/db.v1.AccountService/CreateArchCharacter"
	AccountService_DeleteCharacter_FullMethodName         = "/db.v1.AccountService/DeleteCharacter"
	AccountService_SetPin_FullMethodName                  = "/db.v1.AccountService/SetPin"
	AccountService_VerifyPin_FullMethodName               = "/db.v1.AccountService/VerifyPin"
	AccountService_LoadCargo_FullMethodName               = "/db.v1.AccountService/LoadCargo"
	AccountService_SaveCargo_FullMethodName               = "/db.v1.AccountService/SaveCargo"
	AccountService_ListPendingDeliveries_FullMethodName   = "/db.v1.AccountService/ListPendingDeliveries"
	AccountService_SaveCargoWithDeliveries_FullMethodName = "/db.v1.AccountService/SaveCargoWithDeliveries"
	AccountService_SetAccountBlocked_FullMethodName       = "/db.v1.AccountService/SetAccountBlocked"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountService owns accounts, characters and persistence (PostgreSQL).
type AccountServiceClient interface {
	// AccountLogin validates an account name + password (legacy _MSG_DBAccountLogin).
	AccountLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error)
	// ListCharacters returns the character-selection projection for an account.
	ListCharacters(ctx context.Context, in *ListCharactersRequest, opts ...grpc.CallOption) (*ListCharactersResponse, error)
	// LoadCharacter loads one character's full state by slot (_MSG_DBCharacterLogin).
	LoadCharacter(ctx context.Context, in *LoadCharacterRequest, opts ...grpc.CallOption) (*LoadCharacterResponse, error)
	// SaveCharacter persists one character's state (_MSG_DBSaveMob / SavingQuit).
	SaveCharacter(ctx context.Context, in *SaveCharacterRequest, opts ...grpc.CallOption) (*SaveCharacterResponse, error)
	// CreateCharacter creates a character in a free slot (_MSG_DBCreateCharacter).
	CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error)
	// CreateArchCharacter creates the ARCH twin in the first free account slot
	// (_MSG_DBCreateArchCharacter).
	CreateArchCharacter(ctx context.Context, in *CreateArchCharacterRequest, opts ...grpc.CallOption) (*CreateArchCharacterResponse, error)
	// DeleteCharacter deletes a character after password confirmation.
	DeleteCharacter(ctx context.Context, in *DeleteCharacterRequest, opts ...grpc.CallOption) (*DeleteCharacterResponse, error)
	// SetPin sets (or changes) the account's numeric PIN, stored as an argon2id
	// hash — never plaintext (legacy _MSG_AccountSecure change path).
	SetPin(ctx context.Context, in *SetPinRequest, opts ...grpc.CallOption) (*SetPinResponse, error)
	// VerifyPin checks a numeric PIN against the stored hash (legacy
	// _MSG_AccountSecure verify path); NOT_SET means the account has no PIN yet.
	VerifyPin(ctx context.Context, in *VerifyPinRequest, opts ...grpc.CallOption) (*VerifyPinResponse, error)
	// LoadCargo loads the account-shared cargo (warehouse) gold + items. The cargo
	// is owned by the account, not a single character (all 4 chars share it).
	LoadCargo(ctx context.Context, in *LoadCargoRequest, opts ...grpc.CallOption) (*LoadCargoResponse, error)
	// SaveCargo persists the account-shared cargo gold + items (replace-all).
	SaveCargo(ctx context.Context, in *SaveCargoRequest, opts ...grpc.CallOption) (*SaveCargoResponse, error)
	// ListPendingDeliveries returns the account's pending item grants from the
	// delivery_queue mailbox (donate web shop, issue #34). tmServer drains them
	// into the account cargo inside its loop at login, then acks the outcome via
	// SaveCargoWithDeliveries.
	ListPendingDeliveries(ctx context.Context, in *ListPendingDeliveriesRequest, opts ...grpc.CallOption) (*ListPendingDeliveriesResponse, error)
	// SaveCargoWithDeliveries persists the cargo (replace-all, like SaveCargo) and
	// marks the drained mailbox rows delivered/lost in the SAME transaction — the
	// anti-dup boundary for the drain (web-platform-plan.md §mailbox).
	SaveCargoWithDeliveries(ctx context.Context, in *SaveCargoWithDeliveriesRequest, opts ...grpc.CallOption) (*SaveCargoResponse, error)
	// SetAccountBlocked flips account.is_blocked by account name — the write side of
	// the in-game GM ban/unban command (issue #122). Login already rejects blocked
	// accounts (LOGIN_RESULT_BLOCKED), so a ban denies re-login immediately and an
	// unban restores it. Administrative-ban ownership may later move to binServer
	// entitlement (web-platform-plan.md §binServer); until then this is the gate.
	SetAccountBlocked(ctx context.Context, in *SetAccountBlockedRequest, opts ...grpc.CallOption) (*SetAccountBlockedResponse, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) AccountLogin(ctx context.Context, in *AccountLoginRequest, opts ...grpc.CallOption) (*AccountLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountLoginResponse)
	err := c.cc.Invoke(ctx, AccountService_AccountLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListCharacters(ctx context.Context, in *ListCharactersRequest, opts ...grpc.CallOption) (*ListCharactersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCharactersResponse)
	err := c.cc.Invoke(ctx, AccountService_ListCharacters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) LoadCharacter(ctx context.Context, in *LoadCharacterRequest, opts ...grpc.CallOption) (*LoadCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadCharacterResponse)
	err := c.cc.Invoke(ctx, AccountService_LoadCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SaveCharacter(ctx context.Context, in *SaveCharacterRequest, opts ...grpc.CallOption) (*SaveCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCharacterResponse)
	err := c.cc.Invoke(ctx, AccountService_SaveCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCharacterResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateArchCharacter(ctx context.Context, in *CreateArchCharacterRequest, opts ...grpc.CallOption) (*CreateArchCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateArchCharacterResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateArchCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteCharacter(ctx context.Context, in *DeleteCharacterRequest, opts ...grpc.CallOption) (*DeleteCharacterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCharacterResponse)
	err := c.cc.Invoke(ctx, AccountService_DeleteCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SetPin(ctx context.Context, in *SetPinRequest, opts ...grpc.CallOption) (*SetPinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPinResponse)
	err := c.cc.Invoke(ctx, AccountService_SetPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) VerifyPin(ctx context.Context, in *VerifyPinRequest, opts ...grpc.CallOption) (*VerifyPinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPinResponse)
	err := c.cc.Invoke(ctx, AccountService_VerifyPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) LoadCargo(ctx context.Context, in *LoadCargoRequest, opts ...grpc.CallOption) (*LoadCargoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadCargoResponse)
	err := c.cc.Invoke(ctx, AccountService_LoadCargo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SaveCargo(ctx context.Context, in *SaveCargoRequest, opts ...grpc.CallOption) (*SaveCargoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCargoResponse)
	err := c.cc.Invoke(ctx, AccountService_SaveCargo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ListPendingDeliveries(ctx context.Context, in *ListPendingDeliveriesRequest, opts ...grpc.CallOption) (*ListPendingDeliveriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPendingDeliveriesResponse)
	err := c.cc.Invoke(ctx, AccountService_ListPendingDeliveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SaveCargoWithDeliveries(ctx context.Context, in *SaveCargoWithDeliveriesRequest, opts ...grpc.CallOption) (*SaveCargoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCargoResponse)
	err := c.cc.Invoke(ctx, AccountService_SaveCargoWithDeliveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) SetAccountBlocked(ctx context.Context, in *SetAccountBlockedRequest, opts ...grpc.CallOption) (*SetAccountBlockedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAccountBlockedResponse)
	err := c.cc.Invoke(ctx, AccountService_SetAccountBlocked_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
//
// AccountService owns accounts, characters and persistence (PostgreSQL).
type AccountServiceServer interface {
	// AccountLogin validates an account name + password (legacy _MSG_DBAccountLogin).
	AccountLogin(context.Context, *AccountLoginRequest) (*AccountLoginResponse, error)
	// ListCharacters returns the character-selection projection for an account.
	ListCharacters(context.Context, *ListCharactersRequest) (*ListCharactersResponse, error)
	// LoadCharacter loads one character's full state by slot (_MSG_DBCharacterLogin).
	LoadCharacter(context.Context, *LoadCharacterRequest) (*LoadCharacterResponse, error)
	// SaveCharacter persists one character's state (_MSG_DBSaveMob / SavingQuit).
	SaveCharacter(context.Context, *SaveCharacterRequest) (*SaveCharacterResponse, error)
	// CreateCharacter creates a character in a free slot (_MSG_DBCreateCharacter).
	CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error)
	// CreateArchCharacter creates the ARCH twin in the first free account slot
	// (_MSG_DBCreateArchCharacter).
	CreateArchCharacter(context.Context, *CreateArchCharacterRequest) (*CreateArchCharacterResponse, error)
	// DeleteCharacter deletes a character after password confirmation.
	DeleteCharacter(context.Context, *DeleteCharacterRequest) (*DeleteCharacterResponse, error)
	// SetPin sets (or changes) the account's numeric PIN, stored as an argon2id
	// hash — never plaintext (legacy _MSG_AccountSecure change path).
	SetPin(context.Context, *SetPinRequest) (*SetPinResponse, error)
	// VerifyPin checks a numeric PIN against the stored hash (legacy
	// _MSG_AccountSecure verify path); NOT_SET means the account has no PIN yet.
	VerifyPin(context.Context, *VerifyPinRequest) (*VerifyPinResponse, error)
	// LoadCargo loads the account-shared cargo (warehouse) gold + items. The cargo
	// is owned by the account, not a single character (all 4 chars share it).
	LoadCargo(context.Context, *LoadCargoRequest) (*LoadCargoResponse, error)
	// SaveCargo persists the account-shared cargo gold + items (replace-all).
	SaveCargo(context.Context, *SaveCargoRequest) (*SaveCargoResponse, error)
	// ListPendingDeliveries returns the account's pending item grants from the
	// delivery_queue mailbox (donate web shop, issue #34). tmServer drains them
	// into the account cargo inside its loop at login, then acks the outcome via
	// SaveCargoWithDeliveries.
	ListPendingDeliveries(context.Context, *ListPendingDeliveriesRequest) (*ListPendingDeliveriesResponse, error)
	// SaveCargoWithDeliveries persists the cargo (replace-all, like SaveCargo) and
	// marks the drained mailbox rows delivered/lost in the SAME transaction — the
	// anti-dup boundary for the drain (web-platform-plan.md §mailbox).
	SaveCargoWithDeliveries(context.Context, *SaveCargoWithDeliveriesRequest) (*SaveCargoResponse, error)
	// SetAccountBlocked flips account.is_blocked by account name — the write side of
	// the in-game GM ban/unban command (issue #122). Login already rejects blocked
	// accounts (LOGIN_RESULT_BLOCKED), so a ban denies re-login immediately and an
	// unban restores it. Administrative-ban ownership may later move to binServer
	// entitlement (web-platform-plan.md §binServer); until then this is the gate.
	SetAccountBlocked(context.Context, *SetAccountBlockedRequest) (*SetAccountBlockedResponse, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) AccountLogin(context.Context, *AccountLoginRequest) (*AccountLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AccountLogin not implemented")
}
func (UnimplementedAccountServiceServer) ListCharacters(context.Context, *ListCharactersRequest) (*ListCharactersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCharacters not implemented")
}
func (UnimplementedAccountServiceServer) LoadCharacter(context.Context, *LoadCharacterRequest) (*LoadCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadCharacter not implemented")
}
func (UnimplementedAccountServiceServer) SaveCharacter(context.Context, *SaveCharacterRequest) (*SaveCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCharacter not implemented")
}
func (UnimplementedAccountServiceServer) CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCharacter not implemented")
}
func (UnimplementedAccountServiceServer) CreateArchCharacter(context.Context, *CreateArchCharacterRequest) (*CreateArchCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateArchCharacter not implemented")
}
func (UnimplementedAccountServiceServer) DeleteCharacter(context.Context, *DeleteCharacterRequest) (*DeleteCharacterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCharacter not implemented")
}
func (UnimplementedAccountServiceServer) SetPin(context.Context, *SetPinRequest) (*SetPinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPin not implemented")
}
func (UnimplementedAccountServiceServer) VerifyPin(context.Context, *VerifyPinRequest) (*VerifyPinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPin not implemented")
}
func (UnimplementedAccountServiceServer) LoadCargo(context.Context, *LoadCargoRequest) (*LoadCargoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadCargo not implemented")
}
func (UnimplementedAccountServiceServer) SaveCargo(context.Context, *SaveCargoRequest) (*SaveCargoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCargo not implemented")
}
func (UnimplementedAccountServiceServer) ListPendingDeliveries(context.Context, *ListPendingDeliveriesRequest) (*ListPendingDeliveriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPendingDeliveries not implemented")
}
func (UnimplementedAccountServiceServer) SaveCargoWithDeliveries(context.Context, *SaveCargoWithDeliveriesRequest) (*SaveCargoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCargoWithDeliveries not implemented")
}
func (UnimplementedAccountServiceServer) SetAccountBlocked(context.Context, *SetAccountBlockedRequest) (*SetAccountBlockedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAccountBlocked not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call panics, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_AccountLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AccountLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AccountLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AccountLogin(ctx, req.(*AccountLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCharactersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListCharacters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListCharacters(ctx, req.(*ListCharactersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_LoadCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).LoadCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_LoadCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).LoadCharacter(ctx, req.(*LoadCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SaveCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SaveCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SaveCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SaveCharacter(ctx, req.(*SaveCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateCharacter(ctx, req.(*CreateCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateArchCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArchCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateArchCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateArchCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateArchCharacter(ctx, req.(*CreateArchCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_DeleteCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteCharacter(ctx, req.(*DeleteCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SetPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SetPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SetPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SetPin(ctx, req.(*SetPinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_VerifyPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).VerifyPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_VerifyPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).VerifyPin(ctx, req.(*VerifyPinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_LoadCargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCargoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).LoadCargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_LoadCargo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).LoadCargo(ctx, req.(*LoadCargoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SaveCargo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCargoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SaveCargo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SaveCargo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SaveCargo(ctx, req.(*SaveCargoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ListPendingDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingDeliveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ListPendingDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_ListPendingDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ListPendingDeliveries(ctx, req.(*ListPendingDeliveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SaveCargoWithDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCargoWithDeliveriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SaveCargoWithDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SaveCargoWithDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SaveCargoWithDeliveries(ctx, req.(*SaveCargoWithDeliveriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_SetAccountBlocked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAccountBlockedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).SetAccountBlocked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_SetAccountBlocked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).SetAccountBlocked(ctx, req.(*SetAccountBlockedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "db.v1.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AccountLogin",
			Handler:    _AccountService_AccountLogin_Handler,
		},
		{
			MethodName: "ListCharacters",
			Handler:    _AccountService_ListCharacters_Handler,
		},
		{
			MethodName: "LoadCharacter",
			Handler:    _AccountService_LoadCharacter_Handler,
		},
		{
			MethodName: "SaveCharacter",
			Handler:    _AccountService_SaveCharacter_Handler,
		},
		{
			MethodName: "CreateCharacter",
			Handler:    _AccountService_CreateCharacter_Handler,
		},
		{
			MethodName: "CreateArchCharacter",
			Handler:    _AccountService_CreateArchCharacter_Handler,
		},
		{
			MethodName: "DeleteCharacter",
			Handler:    _AccountService_DeleteCharacter_Handler,
		},
		{
			MethodName: "SetPin",
			Handler:    _AccountService_SetPin_Handler,
		},
		{
			MethodName: "VerifyPin",
			Handler:    _AccountService_VerifyPin_Handler,
		},
		{
			MethodName: "LoadCargo",
			Handler:    _AccountService_LoadCargo_Handler,
		},
		{
			MethodName: "SaveCargo",
			Handler:    _AccountService_SaveCargo_Handler,
		},
		{
			MethodName: "ListPendingDeliveries",
			Handler:    _AccountService_ListPendingDeliveries_Handler,
		},
		{
			MethodName: "SaveCargoWithDeliveries",
			Handler:    _AccountService_SaveCargoWithDeliveries_Handler,
		},
		{
			MethodName: "SetAccountBlocked",
			Handler:    _AccountService_SetAccountBlocked_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/db/v1/db.proto",
}

const (
	NpcConfigService_NpcConfigVersion_FullMethodName   = "/db.v1.NpcConfigService/NpcConfigVersion"
	NpcConfigService_ListNpcDefinitions_FullMethodName = "/db.v1.NpcConfigService/ListNpcDefinitions"
)

// NpcConfigServiceClient is the client API for NpcConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NpcConfigService serves the moderator-editable NPC configuration to tmServer
// (npc-editing-plan.md). It is READ-ONLY from tmServer's side: the web-api writes
// the definitions to Postgres; tmServer polls the version and reloads the full
// snapshot when it changes, then materializes the live entities inside its
// single-owner loop. Separate from AccountService, which mirrors legacy G↔DB.
type NpcConfigServiceClient interface {
	// NpcConfigVersion returns the monotonic config version (cheap poll).
	NpcConfigVersion(ctx context.Context, in *NpcConfigVersionRequest, opts ...grpc.CallOption) (*NpcConfigVersionResponse, error)
	// ListNpcDefinitions returns the full definition snapshot + global price overrides.
	ListNpcDefinitions(ctx context.Context, in *ListNpcDefinitionsRequest, opts ...grpc.CallOption) (*ListNpcDefinitionsResponse, error)
}

type npcConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNpcConfigServiceClient(cc grpc.ClientConnInterface) NpcConfigServiceClient {
	return &npcConfigServiceClient{cc}
}

func (c *npcConfigServiceClient) NpcConfigVersion(ctx context.Context, in *NpcConfigVersionRequest, opts ...grpc.CallOption) (*NpcConfigVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NpcConfigVersionResponse)
	err := c.cc.Invoke(ctx, NpcConfigService_NpcConfigVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *npcConfigServiceClient) ListNpcDefinitions(ctx context.Context, in *ListNpcDefinitionsRequest, opts ...grpc.CallOption) (*ListNpcDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNpcDefinitionsResponse)
	err := c.cc.Invoke(ctx, NpcConfigService_ListNpcDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NpcConfigServiceServer is the server API for NpcConfigService service.
// All implementations must embed UnimplementedNpcConfigServiceServer
// for forward compatibility.
//
// NpcConfigService serves the moderator-editable NPC configuration to tmServer
// (npc-editing-plan.md). It is READ-ONLY from tmServer's side: the web-api writes
// the definitions to Postgres; tmServer polls the version and reloads the full
// snapshot when it changes, then materializes the live entities inside its
// single-owner loop. Separate from AccountService, which mirrors legacy G↔DB.
type NpcConfigServiceServer interface {
	// NpcConfigVersion returns the monotonic config version (cheap poll).
	NpcConfigVersion(context.Context, *NpcConfigVersionRequest) (*NpcConfigVersionResponse, error)
	// ListNpcDefinitions returns the full definition snapshot + global price overrides.
	ListNpcDefinitions(context.Context, *ListNpcDefinitionsRequest) (*ListNpcDefinitionsResponse, error)
	mustEmbedUnimplementedNpcConfigServiceServer()
}

// UnimplementedNpcConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNpcConfigServiceServer struct{}

func (UnimplementedNpcConfigServiceServer) NpcConfigVersion(context.Context, *NpcConfigVersionRequest) (*NpcConfigVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NpcConfigVersion not implemented")
}
func (UnimplementedNpcConfigServiceServer) ListNpcDefinitions(context.Context, *ListNpcDefinitionsRequest) (*ListNpcDefinitionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNpcDefinitions not implemented")
}
func (UnimplementedNpcConfigServiceServer) mustEmbedUnimplementedNpcConfigServiceServer() {}
func (UnimplementedNpcConfigServiceServer) testEmbeddedByValue()                          {}

// UnsafeNpcConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NpcConfigServiceServer will
// result in compilation errors.
type UnsafeNpcConfigServiceServer interface {
	mustEmbedUnimplementedNpcConfigServiceServer()
}

func RegisterNpcConfigServiceServer(s grpc.ServiceRegistrar, srv NpcConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedNpcConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NpcConfigService_ServiceDesc, srv)
}

func _NpcConfigService_NpcConfigVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NpcConfigVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcConfigServiceServer).NpcConfigVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcConfigService_NpcConfigVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcConfigServiceServer).NpcConfigVersion(ctx, req.(*NpcConfigVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NpcConfigService_ListNpcDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNpcDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NpcConfigServiceServer).ListNpcDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NpcConfigService_ListNpcDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NpcConfigServiceServer).ListNpcDefinitions(ctx, req.(*ListNpcDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NpcConfigService_ServiceDesc is the grpc.ServiceDesc for NpcConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NpcConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "db.v1.NpcConfigService",
	HandlerType: (*NpcConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NpcConfigVersion",
			Handler:    _NpcConfigService_NpcConfigVersion_Handler,
		},
		{
			MethodName: "ListNpcDefinitions",
			Handler:    _NpcConfigService_ListNpcDefinitions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/db/v1/db.proto",
}
