// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/game/v1/game.proto

package gamev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBlocksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absent = any block. A plain int32 could not say "any": 0 is a real block.
	Index         *int32 `protobuf:"varint,1,opt,name=index,proto3,oneof" json:"index,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // substring of the leader template name, any case
	X             int32  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`      // with radius > 0: only blocks starting near (x, y)
	Y             int32  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Radius        int32  `protobuf:"varint,5,opt,name=radius,proto3" json:"radius,omitempty"`
	Limit         int32  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"` // 0 = the server's cap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksRequest) Reset() {
	*x = ListBlocksRequest{}
	mi := &file_api_game_v1_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksRequest) ProtoMessage() {}

func (x *ListBlocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksRequest.ProtoReflect.Descriptor instead.
func (*ListBlocksRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{0}
}

func (x *ListBlocksRequest) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *ListBlocksRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListBlocksRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ListBlocksRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ListBlocksRequest) GetRadius() int32 {
	if x != nil {
		return x.Radius
	}
	return 0
}

func (x *ListBlocksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBlocksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*Block               `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // how many matched before the limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlocksResponse) Reset() {
	*x = ListBlocksResponse{}
	mi := &file_api_game_v1_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlocksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlocksResponse) ProtoMessage() {}

func (x *ListBlocksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlocksResponse.ProtoReflect.Descriptor instead.
func (*ListBlocksResponse) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{1}
}

func (x *ListBlocksResponse) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *ListBlocksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Block is one NPCGener block as the game holds it right now.
type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // position in NPCGener.txt (Entity.GenIndex)
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`    // leader template
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`         // start waypoint
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Alive         int32                  `protobuf:"varint,5,opt,name=alive,proto3" json:"alive,omitempty"`
	Max           int32                  `protobuf:"varint,6,opt,name=max,proto3" json:"max,omitempty"`
	Minute        int32                  `protobuf:"varint,7,opt,name=minute,proto3" json:"minute,omitempty"`                        // MinuteGenerate; <= 0 means only events raise it in the legacy
	Off           bool                   `protobuf:"varint,8,opt,name=off,proto3" json:"off,omitempty"`                              // switched off by staff
	DbManaged     bool                   `protobuf:"varint,9,opt,name=db_managed,json=dbManaged,proto3" json:"db_managed,omitempty"` // a merchant of the NPC panel
	EventOwned    bool                   `protobuf:"varint,10,opt,name=event_owned,json=eventOwned,proto3" json:"event_owned,omitempty"`
	HasTemplates  bool                   `protobuf:"varint,11,opt,name=has_templates,json=hasTemplates,proto3" json:"has_templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_api_game_v1_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{2}
}

func (x *Block) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Block) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Block) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Block) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Block) GetAlive() int32 {
	if x != nil {
		return x.Alive
	}
	return 0
}

func (x *Block) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *Block) GetMinute() int32 {
	if x != nil {
		return x.Minute
	}
	return 0
}

func (x *Block) GetOff() bool {
	if x != nil {
		return x.Off
	}
	return false
}

func (x *Block) GetDbManaged() bool {
	if x != nil {
		return x.DbManaged
	}
	return false
}

func (x *Block) GetEventOwned() bool {
	if x != nil {
		return x.EventOwned
	}
	return false
}

func (x *Block) GetHasTemplates() bool {
	if x != nil {
		return x.HasTemplates
	}
	return false
}

type BlockCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"` // e.g. "npc off 23", "gerar 396 aqui", "matar bloco 396"
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`      // where "around you" is
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	By            string                 `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"` // the staff account, for the game's log and the switch row
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCommandRequest) Reset() {
	*x = BlockCommandRequest{}
	mi := &file_api_game_v1_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCommandRequest) ProtoMessage() {}

func (x *BlockCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCommandRequest.ProtoReflect.Descriptor instead.
func (*BlockCommandRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{3}
}

func (x *BlockCommandRequest) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *BlockCommandRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BlockCommandRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BlockCommandRequest) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

type BlockCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []string               `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockCommandResponse) Reset() {
	*x = BlockCommandResponse{}
	mi := &file_api_game_v1_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockCommandResponse) ProtoMessage() {}

func (x *BlockCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockCommandResponse.ProtoReflect.Descriptor instead.
func (*BlockCommandResponse) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{4}
}

func (x *BlockCommandResponse) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ListOnlineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOnlineRequest) Reset() {
	*x = ListOnlineRequest{}
	mi := &file_api_game_v1_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOnlineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOnlineRequest) ProtoMessage() {}

func (x *ListOnlineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOnlineRequest.ProtoReflect.Descriptor instead.
func (*ListOnlineRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{5}
}

type ListOnlineResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Players []*OnlinePlayer        `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	// in_play counts sessions with a character in the world; connected counts
	// every session the server holds, including the ones still on the character
	// screen. They are different numbers and both have been called "online".
	InPlay        int32 `protobuf:"varint,2,opt,name=in_play,json=inPlay,proto3" json:"in_play,omitempty"`
	Connected     int32 `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOnlineResponse) Reset() {
	*x = ListOnlineResponse{}
	mi := &file_api_game_v1_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOnlineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOnlineResponse) ProtoMessage() {}

func (x *ListOnlineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOnlineResponse.ProtoReflect.Descriptor instead.
func (*ListOnlineResponse) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{6}
}

func (x *ListOnlineResponse) GetPlayers() []*OnlinePlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *ListOnlineResponse) GetInPlay() int32 {
	if x != nil {
		return x.InPlay
	}
	return 0
}

func (x *ListOnlineResponse) GetConnected() int32 {
	if x != nil {
		return x.Connected
	}
	return 0
}

type OnlinePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	CharacterName string                 `protobuf:"bytes,2,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"` // empty while the account is still choosing
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	MapX          int32                  `protobuf:"varint,4,opt,name=map_x,json=mapX,proto3" json:"map_x,omitempty"`
	MapY          int32                  `protobuf:"varint,5,opt,name=map_y,json=mapY,proto3" json:"map_y,omitempty"`
	InPlay        bool                   `protobuf:"varint,6,opt,name=in_play,json=inPlay,proto3" json:"in_play,omitempty"` // false = connected but not in the world yet
	Ip            string                 `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePlayer) Reset() {
	*x = OnlinePlayer{}
	mi := &file_api_game_v1_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePlayer) ProtoMessage() {}

func (x *OnlinePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePlayer.ProtoReflect.Descriptor instead.
func (*OnlinePlayer) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{7}
}

func (x *OnlinePlayer) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *OnlinePlayer) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *OnlinePlayer) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *OnlinePlayer) GetMapX() int32 {
	if x != nil {
		return x.MapX
	}
	return 0
}

func (x *OnlinePlayer) GetMapY() int32 {
	if x != nil {
		return x.MapY
	}
	return 0
}

func (x *OnlinePlayer) GetInPlay() bool {
	if x != nil {
		return x.InPlay
	}
	return false
}

func (x *OnlinePlayer) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type KickRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// account_name, not character: the panel works in accounts, and a player on
	// the character screen has no character name to match on. Matching by
	// character is how the in-game /gm ban misses anyone who has not entered the
	// world yet.
	AccountName   string `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickRequest) Reset() {
	*x = KickRequest{}
	mi := &file_api_game_v1_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickRequest) ProtoMessage() {}

func (x *KickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickRequest.ProtoReflect.Descriptor instead.
func (*KickRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{8}
}

func (x *KickRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type KickResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sessions is how many were ended. Zero means the account was not connected,
	// which is not an error — it is the answer.
	Sessions      int32 `protobuf:"varint,1,opt,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickResponse) Reset() {
	*x = KickResponse{}
	mi := &file_api_game_v1_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickResponse) ProtoMessage() {}

func (x *KickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickResponse.ProtoReflect.Descriptor instead.
func (*KickResponse) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{9}
}

func (x *KickResponse) GetSessions() int32 {
	if x != nil {
		return x.Sessions
	}
	return 0
}

type UnstuckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// account_name, not character, for the reason KickRequest gives: the panel
	// works in accounts.
	AccountName string `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	// to_x/to_y send the character to an EXACT tile instead of the nearest city.
	// Both zero (the default) keeps the rescue behaviour.
	//
	// It exists because the panel had no way to put somebody anywhere: rescuing a
	// stuck player and reaching a place to look at it are the same operation with
	// a different destination, and without this the only way into an area with no
	// entry implemented is to have no way in at all.
	ToX           int32 `protobuf:"varint,2,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY           int32 `protobuf:"varint,3,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnstuckRequest) Reset() {
	*x = UnstuckRequest{}
	mi := &file_api_game_v1_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnstuckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnstuckRequest) ProtoMessage() {}

func (x *UnstuckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnstuckRequest.ProtoReflect.Descriptor instead.
func (*UnstuckRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{10}
}

func (x *UnstuckRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *UnstuckRequest) GetToX() int32 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *UnstuckRequest) GetToY() int32 {
	if x != nil {
		return x.ToY
	}
	return 0
}

type UnstuckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// found is false when the account is not in the world. That is an answer, not
	// an error: the player may have logged off between the report and the click.
	Found         bool   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	CharacterName string `protobuf:"bytes,2,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	FromX         int32  `protobuf:"varint,3,opt,name=from_x,json=fromX,proto3" json:"from_x,omitempty"`
	FromY         int32  `protobuf:"varint,4,opt,name=from_y,json=fromY,proto3" json:"from_y,omitempty"`
	ToX           int32  `protobuf:"varint,5,opt,name=to_x,json=toX,proto3" json:"to_x,omitempty"`
	ToY           int32  `protobuf:"varint,6,opt,name=to_y,json=toY,proto3" json:"to_y,omitempty"`
	// city is the name of where they landed, so the moderator can tell them.
	City          string `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnstuckResponse) Reset() {
	*x = UnstuckResponse{}
	mi := &file_api_game_v1_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnstuckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnstuckResponse) ProtoMessage() {}

func (x *UnstuckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnstuckResponse.ProtoReflect.Descriptor instead.
func (*UnstuckResponse) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{11}
}

func (x *UnstuckResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *UnstuckResponse) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

func (x *UnstuckResponse) GetFromX() int32 {
	if x != nil {
		return x.FromX
	}
	return 0
}

func (x *UnstuckResponse) GetFromY() int32 {
	if x != nil {
		return x.FromY
	}
	return 0
}

func (x *UnstuckResponse) GetToX() int32 {
	if x != nil {
		return x.ToX
	}
	return 0
}

func (x *UnstuckResponse) GetToY() int32 {
	if x != nil {
		return x.ToY
	}
	return 0
}

func (x *UnstuckResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type DeliverNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountName   string                 `protobuf:"bytes,1,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverNowRequest) Reset() {
	*x = DeliverNowRequest{}
	mi := &file_api_game_v1_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverNowRequest) ProtoMessage() {}

func (x *DeliverNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverNowRequest.ProtoReflect.Descriptor instead.
func (*DeliverNowRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{12}
}

func (x *DeliverNowRequest) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

type DeliverNowResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// found is false when the account is not connected. Its mailbox keeps the
	// items and the next login drains them, so this is not a failure.
	Found bool `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	// delivered and lost split what the mailbox held. A warehouse with no free
	// slot loses the item exactly as the login drain does — the panel has to be
	// able to say so instead of reporting a delivery that did not happen.
	Delivered     int32  `protobuf:"varint,2,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Lost          int32  `protobuf:"varint,3,opt,name=lost,proto3" json:"lost,omitempty"`
	CharacterName string `protobuf:"bytes,4,opt,name=character_name,json=characterName,proto3" json:"character_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverNowResponse) Reset() {
	*x = DeliverNowResponse{}
	mi := &file_api_game_v1_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverNowResponse) ProtoMessage() {}

func (x *DeliverNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverNowResponse.ProtoReflect.Descriptor instead.
func (*DeliverNowResponse) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{13}
}

func (x *DeliverNowResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *DeliverNowResponse) GetDelivered() int32 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *DeliverNowResponse) GetLost() int32 {
	if x != nil {
		return x.Lost
	}
	return 0
}

func (x *DeliverNowResponse) GetCharacterName() string {
	if x != nil {
		return x.CharacterName
	}
	return ""
}

type OverlaysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverlaysRequest) Reset() {
	*x = OverlaysRequest{}
	mi := &file_api_game_v1_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverlaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverlaysRequest) ProtoMessage() {}

func (x *OverlaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverlaysRequest.ProtoReflect.Descriptor instead.
func (*OverlaysRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{14}
}

type OverlaysResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Each field is one boot flag. The names match the editors they feed rather
	// than the environment variables, because the panel speaks in screens.
	ItemStats bool `protobuf:"varint,1,opt,name=item_stats,json=itemStats,proto3" json:"item_stats,omitempty"` // W2PP_ITEM_STAT_EDITING — atributos de item
	MobStats  bool `protobuf:"varint,2,opt,name=mob_stats,json=mobStats,proto3" json:"mob_stats,omitempty"`    // W2PP_MOB_STAT_EDITING  — atributos de monstro
	Npcs      bool `protobuf:"varint,3,opt,name=npcs,proto3" json:"npcs,omitempty"`                            // W2PP_NPC_EDITING       — NPCs e suas lojas
	// xp_config_version is the Mesa de XP version this process actually loaded,
	// read once at boot. The Mesa needs no flag — an unedited table IS the legacy
	// behaviour — so the three booleans above cannot answer the only question
	// that matters about it: is what the panel shows what the game is paying?
	//
	// Compared against the version in the database, it separates "saved and live"
	// from "saved, waiting for a restart" — which look identical on the screen
	// and differ by a week of wrong levelling.
	//
	// Zero means the server booted with no Mesa at all: either it has no dbServer
	// or the read failed, and it is running the legacy tables.
	XpConfigVersion int64 `protobuf:"varint,4,opt,name=xp_config_version,json=xpConfigVersion,proto3" json:"xp_config_version,omitempty"`
	// mount_config_version is when the mount overlay (curves + absorption) last
	// changed, as unix seconds, as this process read it at boot. The panel
	// compares it with the database to tell a saved-and-live screen from one whose
	// save is still waiting for a restart. Zero means it booted without the
	// overlay — no dbServer, or the read failed — and every lineage is on the
	// compiled default.
	MountConfigVersion int64 `protobuf:"varint,5,opt,name=mount_config_version,json=mountConfigVersion,proto3" json:"mount_config_version,omitempty"`
	// quest_content is what Common/Settings/QuestsRate.txt gave THIS process,
	// captured before the panel's own rows were applied over it.
	//
	// It exists because the panel was showing the wrong baseline. Its "no arquivo"
	// line read domain.QuestRewardDefaults — the numbers compiled into the binary
	// from CReadFiles.cpp — while the content file says something else entirely
	// (30.000 of experience on the Cemitério, not 1.000). Two things went wrong
	// because of it: an edit that looked like quadrupling a reward was really
	// cutting it to a seventh, and "voltar ao valor do conteúdo" would have left
	// the screen showing a number the game does not pay.
	//
	// The panel cannot read the file itself: adminServer is deliberately
	// standalone and mounts no content tree. Asking the running process is also
	// the stronger answer — it reports what is actually loaded, not what a file on
	// some disk happens to say.
	//
	// Empty means the server booted with no content tree (-content unset), so it
	// is running the compiled defaults and the panel should say exactly that.
	QuestContent  []*QuestContentRate `protobuf:"bytes,6,rep,name=quest_content,json=questContent,proto3" json:"quest_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverlaysResponse) Reset() {
	*x = OverlaysResponse{}
	mi := &file_api_game_v1_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverlaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverlaysResponse) ProtoMessage() {}

func (x *OverlaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverlaysResponse.ProtoReflect.Descriptor instead.
func (*OverlaysResponse) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{15}
}

func (x *OverlaysResponse) GetItemStats() bool {
	if x != nil {
		return x.ItemStats
	}
	return false
}

func (x *OverlaysResponse) GetMobStats() bool {
	if x != nil {
		return x.MobStats
	}
	return false
}

func (x *OverlaysResponse) GetNpcs() bool {
	if x != nil {
		return x.Npcs
	}
	return false
}

func (x *OverlaysResponse) GetXpConfigVersion() int64 {
	if x != nil {
		return x.XpConfigVersion
	}
	return 0
}

func (x *OverlaysResponse) GetMountConfigVersion() int64 {
	if x != nil {
		return x.MountConfigVersion
	}
	return 0
}

func (x *OverlaysResponse) GetQuestContent() []*QuestContentRate {
	if x != nil {
		return x.QuestContent
	}
	return nil
}

// QuestContentRate is one quest trophy as the content file defines it. Arch is
// absent on purpose: these quests are Mortal's alone on this server, so an Arch
// column would be a number nobody can reach.
type QuestContentRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          int32                  `protobuf:"varint,1,opt,name=tier,proto3" json:"tier,omitempty"`
	MortalExp     int64                  `protobuf:"varint,2,opt,name=mortal_exp,json=mortalExp,proto3" json:"mortal_exp,omitempty"`
	Coin          int32                  `protobuf:"varint,3,opt,name=coin,proto3" json:"coin,omitempty"`
	MortalMin     int32                  `protobuf:"varint,4,opt,name=mortal_min,json=mortalMin,proto3" json:"mortal_min,omitempty"`
	MortalMax     int32                  `protobuf:"varint,5,opt,name=mortal_max,json=mortalMax,proto3" json:"mortal_max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestContentRate) Reset() {
	*x = QuestContentRate{}
	mi := &file_api_game_v1_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestContentRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestContentRate) ProtoMessage() {}

func (x *QuestContentRate) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestContentRate.ProtoReflect.Descriptor instead.
func (*QuestContentRate) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{16}
}

func (x *QuestContentRate) GetTier() int32 {
	if x != nil {
		return x.Tier
	}
	return 0
}

func (x *QuestContentRate) GetMortalExp() int64 {
	if x != nil {
		return x.MortalExp
	}
	return 0
}

func (x *QuestContentRate) GetCoin() int32 {
	if x != nil {
		return x.Coin
	}
	return 0
}

func (x *QuestContentRate) GetMortalMin() int32 {
	if x != nil {
		return x.MortalMin
	}
	return 0
}

func (x *QuestContentRate) GetMortalMax() int32 {
	if x != nil {
		return x.MortalMax
	}
	return 0
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_api_game_v1_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{17}
}

func (x *BroadcastRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BroadcastResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// recipients is how many players in play received it.
	Recipients    int32 `protobuf:"varint,1,opt,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_api_game_v1_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{18}
}

func (x *BroadcastResponse) GetRecipients() int32 {
	if x != nil {
		return x.Recipients
	}
	return 0
}

type DrainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message is announced to everyone before the sessions end. Empty sends
	// nothing, which is right for an emergency and wrong for a planned restart.
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainRequest) Reset() {
	*x = DrainRequest{}
	mi := &file_api_game_v1_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainRequest) ProtoMessage() {}

func (x *DrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainRequest.ProtoReflect.Descriptor instead.
func (*DrainRequest) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{19}
}

func (x *DrainRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notified      int32                  `protobuf:"varint,1,opt,name=notified,proto3" json:"notified,omitempty"` // players who received the notice
	Kicked        int32                  `protobuf:"varint,2,opt,name=kicked,proto3" json:"kicked,omitempty"`     // sessions ended
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainResponse) Reset() {
	*x = DrainResponse{}
	mi := &file_api_game_v1_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainResponse) ProtoMessage() {}

func (x *DrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_game_v1_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainResponse.ProtoReflect.Descriptor instead.
func (*DrainResponse) Descriptor() ([]byte, []int) {
	return file_api_game_v1_game_proto_rawDescGZIP(), []int{20}
}

func (x *DrainResponse) GetNotified() int32 {
	if x != nil {
		return x.Notified
	}
	return 0
}

func (x *DrainResponse) GetKicked() int32 {
	if x != nil {
		return x.Kicked
	}
	return 0
}

var File_api_game_v1_game_proto protoreflect.FileDescriptor

const file_api_game_v1_game_proto_rawDesc = "" +
	"\n" +
	"\x16api/game/v1/game.proto\x12\agame.v1\"\x96\x01\n" +
	"\x11ListBlocksRequest\x12\x19\n" +
	"\x05index\x18\x01 \x01(\x05H\x00R\x05index\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x16\n" +
	"\x06radius\x18\x05 \x01(\x05R\x06radius\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limitB\b\n" +
	"\x06_index\"R\n" +
	"\x12ListBlocksResponse\x12&\n" +
	"\x06blocks\x18\x01 \x03(\v2\x0e.game.v1.BlockR\x06blocks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x84\x02\n" +
	"\x05Block\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x14\n" +
	"\x05alive\x18\x05 \x01(\x05R\x05alive\x12\x10\n" +
	"\x03max\x18\x06 \x01(\x05R\x03max\x12\x16\n" +
	"\x06minute\x18\a \x01(\x05R\x06minute\x12\x10\n" +
	"\x03off\x18\b \x01(\bR\x03off\x12\x1d\n" +
	"\n" +
	"db_managed\x18\t \x01(\bR\tdbManaged\x12\x1f\n" +
	"\vevent_owned\x18\n" +
	" \x01(\bR\n" +
	"eventOwned\x12#\n" +
	"\rhas_templates\x18\v \x01(\bR\fhasTemplates\"U\n" +
	"\x13BlockCommandRequest\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x0e\n" +
	"\x02by\x18\x04 \x01(\tR\x02by\",\n" +
	"\x14BlockCommandResponse\x12\x14\n" +
	"\x05lines\x18\x01 \x03(\tR\x05lines\"\x13\n" +
	"\x11ListOnlineRequest\"|\n" +
	"\x12ListOnlineResponse\x12/\n" +
	"\aplayers\x18\x01 \x03(\v2\x15.game.v1.OnlinePlayerR\aplayers\x12\x17\n" +
	"\ain_play\x18\x02 \x01(\x05R\x06inPlay\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\x05R\tconnected\"\xc1\x01\n" +
	"\fOnlinePlayer\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\x12%\n" +
	"\x0echaracter_name\x18\x02 \x01(\tR\rcharacterName\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x13\n" +
	"\x05map_x\x18\x04 \x01(\x05R\x04mapX\x12\x13\n" +
	"\x05map_y\x18\x05 \x01(\x05R\x04mapY\x12\x17\n" +
	"\ain_play\x18\x06 \x01(\bR\x06inPlay\x12\x0e\n" +
	"\x02ip\x18\a \x01(\tR\x02ip\"0\n" +
	"\vKickRequest\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\"*\n" +
	"\fKickResponse\x12\x1a\n" +
	"\bsessions\x18\x01 \x01(\x05R\bsessions\"Y\n" +
	"\x0eUnstuckRequest\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\x12\x11\n" +
	"\x04to_x\x18\x02 \x01(\x05R\x03toX\x12\x11\n" +
	"\x04to_y\x18\x03 \x01(\x05R\x03toY\"\xb6\x01\n" +
	"\x0fUnstuckResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12%\n" +
	"\x0echaracter_name\x18\x02 \x01(\tR\rcharacterName\x12\x15\n" +
	"\x06from_x\x18\x03 \x01(\x05R\x05fromX\x12\x15\n" +
	"\x06from_y\x18\x04 \x01(\x05R\x05fromY\x12\x11\n" +
	"\x04to_x\x18\x05 \x01(\x05R\x03toX\x12\x11\n" +
	"\x04to_y\x18\x06 \x01(\x05R\x03toY\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\"6\n" +
	"\x11DeliverNowRequest\x12!\n" +
	"\faccount_name\x18\x01 \x01(\tR\vaccountName\"\x83\x01\n" +
	"\x12DeliverNowResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1c\n" +
	"\tdelivered\x18\x02 \x01(\x05R\tdelivered\x12\x12\n" +
	"\x04lost\x18\x03 \x01(\x05R\x04lost\x12%\n" +
	"\x0echaracter_name\x18\x04 \x01(\tR\rcharacterName\"\x11\n" +
	"\x0fOverlaysRequest\"\x80\x02\n" +
	"\x10OverlaysResponse\x12\x1d\n" +
	"\n" +
	"item_stats\x18\x01 \x01(\bR\titemStats\x12\x1b\n" +
	"\tmob_stats\x18\x02 \x01(\bR\bmobStats\x12\x12\n" +
	"\x04npcs\x18\x03 \x01(\bR\x04npcs\x12*\n" +
	"\x11xp_config_version\x18\x04 \x01(\x03R\x0fxpConfigVersion\x120\n" +
	"\x14mount_config_version\x18\x05 \x01(\x03R\x12mountConfigVersion\x12>\n" +
	"\rquest_content\x18\x06 \x03(\v2\x19.game.v1.QuestContentRateR\fquestContent\"\x97\x01\n" +
	"\x10QuestContentRate\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\x05R\x04tier\x12\x1d\n" +
	"\n" +
	"mortal_exp\x18\x02 \x01(\x03R\tmortalExp\x12\x12\n" +
	"\x04coin\x18\x03 \x01(\x05R\x04coin\x12\x1d\n" +
	"\n" +
	"mortal_min\x18\x04 \x01(\x05R\tmortalMin\x12\x1d\n" +
	"\n" +
	"mortal_max\x18\x05 \x01(\x05R\tmortalMax\",\n" +
	"\x10BroadcastRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\x11BroadcastResponse\x12\x1e\n" +
	"\n" +
	"recipients\x18\x01 \x01(\x05R\n" +
	"recipients\"(\n" +
	"\fDrainRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"C\n" +
	"\rDrainResponse\x12\x1a\n" +
	"\bnotified\x18\x01 \x01(\x05R\bnotified\x12\x16\n" +
	"\x06kicked\x18\x02 \x01(\x05R\x06kicked2\xe6\x04\n" +
	"\x12GameControlService\x12E\n" +
	"\n" +
	"ListOnline\x12\x1a.game.v1.ListOnlineRequest\x1a\x1b.game.v1.ListOnlineResponse\x123\n" +
	"\x04Kick\x12\x14.game.v1.KickRequest\x1a\x15.game.v1.KickResponse\x12B\n" +
	"\tBroadcast\x12\x19.game.v1.BroadcastRequest\x1a\x1a.game.v1.BroadcastResponse\x12<\n" +
	"\aUnstuck\x12\x17.game.v1.UnstuckRequest\x1a\x18.game.v1.UnstuckResponse\x12E\n" +
	"\n" +
	"DeliverNow\x12\x1a.game.v1.DeliverNowRequest\x1a\x1b.game.v1.DeliverNowResponse\x12?\n" +
	"\bOverlays\x12\x18.game.v1.OverlaysRequest\x1a\x19.game.v1.OverlaysResponse\x126\n" +
	"\x05Drain\x12\x15.game.v1.DrainRequest\x1a\x16.game.v1.DrainResponse\x12E\n" +
	"\n" +
	"ListBlocks\x12\x1a.game.v1.ListBlocksRequest\x1a\x1b.game.v1.ListBlocksResponse\x12K\n" +
	"\fBlockCommand\x12\x1c.game.v1.BlockCommandRequest\x1a\x1d.game.v1.BlockCommandResponseB5Z3github.com/jeanluca/w2pp-openwyd/api/game/v1;gamev1b\x06proto3"

var (
	file_api_game_v1_game_proto_rawDescOnce sync.Once
	file_api_game_v1_game_proto_rawDescData []byte
)

func file_api_game_v1_game_proto_rawDescGZIP() []byte {
	file_api_game_v1_game_proto_rawDescOnce.Do(func() {
		file_api_game_v1_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_game_v1_game_proto_rawDesc), len(file_api_game_v1_game_proto_rawDesc)))
	})
	return file_api_game_v1_game_proto_rawDescData
}

var file_api_game_v1_game_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_game_v1_game_proto_goTypes = []any{
	(*ListBlocksRequest)(nil),    // 0: game.v1.ListBlocksRequest
	(*ListBlocksResponse)(nil),   // 1: game.v1.ListBlocksResponse
	(*Block)(nil),                // 2: game.v1.Block
	(*BlockCommandRequest)(nil),  // 3: game.v1.BlockCommandRequest
	(*BlockCommandResponse)(nil), // 4: game.v1.BlockCommandResponse
	(*ListOnlineRequest)(nil),    // 5: game.v1.ListOnlineRequest
	(*ListOnlineResponse)(nil),   // 6: game.v1.ListOnlineResponse
	(*OnlinePlayer)(nil),         // 7: game.v1.OnlinePlayer
	(*KickRequest)(nil),          // 8: game.v1.KickRequest
	(*KickResponse)(nil),         // 9: game.v1.KickResponse
	(*UnstuckRequest)(nil),       // 10: game.v1.UnstuckRequest
	(*UnstuckResponse)(nil),      // 11: game.v1.UnstuckResponse
	(*DeliverNowRequest)(nil),    // 12: game.v1.DeliverNowRequest
	(*DeliverNowResponse)(nil),   // 13: game.v1.DeliverNowResponse
	(*OverlaysRequest)(nil),      // 14: game.v1.OverlaysRequest
	(*OverlaysResponse)(nil),     // 15: game.v1.OverlaysResponse
	(*QuestContentRate)(nil),     // 16: game.v1.QuestContentRate
	(*BroadcastRequest)(nil),     // 17: game.v1.BroadcastRequest
	(*BroadcastResponse)(nil),    // 18: game.v1.BroadcastResponse
	(*DrainRequest)(nil),         // 19: game.v1.DrainRequest
	(*DrainResponse)(nil),        // 20: game.v1.DrainResponse
}
var file_api_game_v1_game_proto_depIdxs = []int32{
	2,  // 0: game.v1.ListBlocksResponse.blocks:type_name -> game.v1.Block
	7,  // 1: game.v1.ListOnlineResponse.players:type_name -> game.v1.OnlinePlayer
	16, // 2: game.v1.OverlaysResponse.quest_content:type_name -> game.v1.QuestContentRate
	5,  // 3: game.v1.GameControlService.ListOnline:input_type -> game.v1.ListOnlineRequest
	8,  // 4: game.v1.GameControlService.Kick:input_type -> game.v1.KickRequest
	17, // 5: game.v1.GameControlService.Broadcast:input_type -> game.v1.BroadcastRequest
	10, // 6: game.v1.GameControlService.Unstuck:input_type -> game.v1.UnstuckRequest
	12, // 7: game.v1.GameControlService.DeliverNow:input_type -> game.v1.DeliverNowRequest
	14, // 8: game.v1.GameControlService.Overlays:input_type -> game.v1.OverlaysRequest
	19, // 9: game.v1.GameControlService.Drain:input_type -> game.v1.DrainRequest
	0,  // 10: game.v1.GameControlService.ListBlocks:input_type -> game.v1.ListBlocksRequest
	3,  // 11: game.v1.GameControlService.BlockCommand:input_type -> game.v1.BlockCommandRequest
	6,  // 12: game.v1.GameControlService.ListOnline:output_type -> game.v1.ListOnlineResponse
	9,  // 13: game.v1.GameControlService.Kick:output_type -> game.v1.KickResponse
	18, // 14: game.v1.GameControlService.Broadcast:output_type -> game.v1.BroadcastResponse
	11, // 15: game.v1.GameControlService.Unstuck:output_type -> game.v1.UnstuckResponse
	13, // 16: game.v1.GameControlService.DeliverNow:output_type -> game.v1.DeliverNowResponse
	15, // 17: game.v1.GameControlService.Overlays:output_type -> game.v1.OverlaysResponse
	20, // 18: game.v1.GameControlService.Drain:output_type -> game.v1.DrainResponse
	1,  // 19: game.v1.GameControlService.ListBlocks:output_type -> game.v1.ListBlocksResponse
	4,  // 20: game.v1.GameControlService.BlockCommand:output_type -> game.v1.BlockCommandResponse
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_game_v1_game_proto_init() }
func file_api_game_v1_game_proto_init() {
	if File_api_game_v1_game_proto != nil {
		return
	}
	file_api_game_v1_game_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_game_v1_game_proto_rawDesc), len(file_api_game_v1_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_game_v1_game_proto_goTypes,
		DependencyIndexes: file_api_game_v1_game_proto_depIdxs,
		MessageInfos:      file_api_game_v1_game_proto_msgTypes,
	}.Build()
	File_api_game_v1_game_proto = out.File
	file_api_game_v1_game_proto_goTypes = nil
	file_api_game_v1_game_proto_depIdxs = nil
}
