// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/game/v1/game.proto

package gamev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameControlService_ListOnline_FullMethodName   = "/game.v1.GameControlService/ListOnline"
	GameControlService_Kick_FullMethodName         = "/game.v1.GameControlService/Kick"
	GameControlService_Broadcast_FullMethodName    = "/game.v1.GameControlService/Broadcast"
	GameControlService_Unstuck_FullMethodName      = "/game.v1.GameControlService/Unstuck"
	GameControlService_DeliverNow_FullMethodName   = "/game.v1.GameControlService/DeliverNow"
	GameControlService_Overlays_FullMethodName     = "/game.v1.GameControlService/Overlays"
	GameControlService_Drain_FullMethodName        = "/game.v1.GameControlService/Drain"
	GameControlService_ListBlocks_FullMethodName   = "/game.v1.GameControlService/ListBlocks"
	GameControlService_BlockCommand_FullMethodName = "/game.v1.GameControlService/BlockCommand"
)

// GameControlServiceClient is the client API for GameControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GameControlService is the tmServer's inbound control surface: the first one it
// has ever had. Until now the game server only listened on the client port, so
// nothing could ask it who was playing or tell it to do anything.
//
// It exists for the admin panel. Every call is a moderator action the panel has
// already authorized against account.role and recorded in its audit log — the
// tmServer has no database of its own and cannot re-check either, which is why
// the listener refuses to start without a shared token and treats whoever
// presents it as the panel.
//
// Every RPC crosses into the single-owner game loop through World.GoDetached and
// waits for the loop to answer. That queue is drained ahead of player input, so
// these calls must stay one-shot: a screen that polled this on a timer would
// front-run gameplay.
type GameControlServiceClient interface {
	// ListOnline returns the sessions the server currently holds.
	ListOnline(ctx context.Context, in *ListOnlineRequest, opts ...grpc.CallOption) (*ListOnlineResponse, error)
	// Kick ends every session of one account, whatever screen it is on.
	Kick(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*KickResponse, error)
	// Broadcast sends a notice to everyone in play.
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error)
	// Unstuck moves a character out of somewhere it cannot walk out of.
	//
	// The world has spots that let a player in and not back out — a gap in the
	// collision map, a warp that lands inside scenery. Reconnecting does not help:
	// the position is saved, so the player comes back exactly where they were
	// stuck. Until now the only remedy was editing the database by hand, which
	// needs the character offline and somebody willing to do it.
	Unstuck(ctx context.Context, in *UnstuckRequest, opts ...grpc.CallOption) (*UnstuckResponse, error)
	// DeliverNow empties an account mailbox without waiting for its next login.
	//
	// delivery_queue is drained once, at account login, straight into the
	// warehouse. That is right for the donate shop and wrong for support: a
	// player who reports a problem and gets an item handed to them is told to log
	// out and back in, which is the moment they find out the panel cannot
	// actually give them anything while they are standing there.
	//
	// Nothing new is granted here. It is the same mailbox and the same placement
	// the login path runs — only sooner.
	DeliverNow(ctx context.Context, in *DeliverNowRequest, opts ...grpc.CallOption) (*DeliverNowResponse, error)
	// Overlays reports which moderator-editing overlays this server booted with.
	//
	// Each is a boot flag that defaults to OFF. While one is off, the panel's
	// matching editor still writes to the database and the game never reads it —
	// the edit sits there inert forever with nothing on any screen to say so, and
	// the moderator concludes the feature is broken or that they did it wrong.
	//
	// The panel cannot work this out on its own: the flags live in the game
	// server's environment, and the database looks identical either way. So the
	// game says.
	Overlays(ctx context.Context, in *OverlaysRequest, opts ...grpc.CallOption) (*OverlaysResponse, error)
	// Drain empties the server and waits for every save to land.
	//
	// It exists because a restart is only safe if the saves finish, and on
	// shutdown they compete with the platform's SIGTERM-to-SIGKILL window: the
	// server announces, then saves every player one at a time, and whatever has
	// not finished when the kill lands is lost — items, experience, gold since
	// login. Ending the sessions first does the same saving with no deadline
	// attached, and the shutdown that follows finds an empty world.
	Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error)
	// ListBlocks finds NPCGener blocks — by number, by leader template name, or
	// near a tile — with how many of their mobs are alive right now and whether
	// the block is switched off. The panel's "Blocos" page.
	ListBlocks(ctx context.Context, in *ListBlocksRequest, opts ...grpc.CallOption) (*ListBlocksResponse, error)
	// BlockCommand runs one of the in-game block commands (npc off|on, gerar,
	// criar, matar, recarregar) as a GM standing at (x, y) would, and returns
	// the lines the GM would have read. Same code as "/gm", so the two cannot
	// drift apart.
	BlockCommand(ctx context.Context, in *BlockCommandRequest, opts ...grpc.CallOption) (*BlockCommandResponse, error)
}

type gameControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameControlServiceClient(cc grpc.ClientConnInterface) GameControlServiceClient {
	return &gameControlServiceClient{cc}
}

func (c *gameControlServiceClient) ListOnline(ctx context.Context, in *ListOnlineRequest, opts ...grpc.CallOption) (*ListOnlineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOnlineResponse)
	err := c.cc.Invoke(ctx, GameControlService_ListOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameControlServiceClient) Kick(ctx context.Context, in *KickRequest, opts ...grpc.CallOption) (*KickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickResponse)
	err := c.cc.Invoke(ctx, GameControlService_Kick_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameControlServiceClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BroadcastResponse)
	err := c.cc.Invoke(ctx, GameControlService_Broadcast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameControlServiceClient) Unstuck(ctx context.Context, in *UnstuckRequest, opts ...grpc.CallOption) (*UnstuckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnstuckResponse)
	err := c.cc.Invoke(ctx, GameControlService_Unstuck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameControlServiceClient) DeliverNow(ctx context.Context, in *DeliverNowRequest, opts ...grpc.CallOption) (*DeliverNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverNowResponse)
	err := c.cc.Invoke(ctx, GameControlService_DeliverNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameControlServiceClient) Overlays(ctx context.Context, in *OverlaysRequest, opts ...grpc.CallOption) (*OverlaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OverlaysResponse)
	err := c.cc.Invoke(ctx, GameControlService_Overlays_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameControlServiceClient) Drain(ctx context.Context, in *DrainRequest, opts ...grpc.CallOption) (*DrainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainResponse)
	err := c.cc.Invoke(ctx, GameControlService_Drain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameControlServiceClient) ListBlocks(ctx context.Context, in *ListBlocksRequest, opts ...grpc.CallOption) (*ListBlocksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlocksResponse)
	err := c.cc.Invoke(ctx, GameControlService_ListBlocks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameControlServiceClient) BlockCommand(ctx context.Context, in *BlockCommandRequest, opts ...grpc.CallOption) (*BlockCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BlockCommandResponse)
	err := c.cc.Invoke(ctx, GameControlService_BlockCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameControlServiceServer is the server API for GameControlService service.
// All implementations must embed UnimplementedGameControlServiceServer
// for forward compatibility.
//
// GameControlService is the tmServer's inbound control surface: the first one it
// has ever had. Until now the game server only listened on the client port, so
// nothing could ask it who was playing or tell it to do anything.
//
// It exists for the admin panel. Every call is a moderator action the panel has
// already authorized against account.role and recorded in its audit log — the
// tmServer has no database of its own and cannot re-check either, which is why
// the listener refuses to start without a shared token and treats whoever
// presents it as the panel.
//
// Every RPC crosses into the single-owner game loop through World.GoDetached and
// waits for the loop to answer. That queue is drained ahead of player input, so
// these calls must stay one-shot: a screen that polled this on a timer would
// front-run gameplay.
type GameControlServiceServer interface {
	// ListOnline returns the sessions the server currently holds.
	ListOnline(context.Context, *ListOnlineRequest) (*ListOnlineResponse, error)
	// Kick ends every session of one account, whatever screen it is on.
	Kick(context.Context, *KickRequest) (*KickResponse, error)
	// Broadcast sends a notice to everyone in play.
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error)
	// Unstuck moves a character out of somewhere it cannot walk out of.
	//
	// The world has spots that let a player in and not back out — a gap in the
	// collision map, a warp that lands inside scenery. Reconnecting does not help:
	// the position is saved, so the player comes back exactly where they were
	// stuck. Until now the only remedy was editing the database by hand, which
	// needs the character offline and somebody willing to do it.
	Unstuck(context.Context, *UnstuckRequest) (*UnstuckResponse, error)
	// DeliverNow empties an account mailbox without waiting for its next login.
	//
	// delivery_queue is drained once, at account login, straight into the
	// warehouse. That is right for the donate shop and wrong for support: a
	// player who reports a problem and gets an item handed to them is told to log
	// out and back in, which is the moment they find out the panel cannot
	// actually give them anything while they are standing there.
	//
	// Nothing new is granted here. It is the same mailbox and the same placement
	// the login path runs — only sooner.
	DeliverNow(context.Context, *DeliverNowRequest) (*DeliverNowResponse, error)
	// Overlays reports which moderator-editing overlays this server booted with.
	//
	// Each is a boot flag that defaults to OFF. While one is off, the panel's
	// matching editor still writes to the database and the game never reads it —
	// the edit sits there inert forever with nothing on any screen to say so, and
	// the moderator concludes the feature is broken or that they did it wrong.
	//
	// The panel cannot work this out on its own: the flags live in the game
	// server's environment, and the database looks identical either way. So the
	// game says.
	Overlays(context.Context, *OverlaysRequest) (*OverlaysResponse, error)
	// Drain empties the server and waits for every save to land.
	//
	// It exists because a restart is only safe if the saves finish, and on
	// shutdown they compete with the platform's SIGTERM-to-SIGKILL window: the
	// server announces, then saves every player one at a time, and whatever has
	// not finished when the kill lands is lost — items, experience, gold since
	// login. Ending the sessions first does the same saving with no deadline
	// attached, and the shutdown that follows finds an empty world.
	Drain(context.Context, *DrainRequest) (*DrainResponse, error)
	// ListBlocks finds NPCGener blocks — by number, by leader template name, or
	// near a tile — with how many of their mobs are alive right now and whether
	// the block is switched off. The panel's "Blocos" page.
	ListBlocks(context.Context, *ListBlocksRequest) (*ListBlocksResponse, error)
	// BlockCommand runs one of the in-game block commands (npc off|on, gerar,
	// criar, matar, recarregar) as a GM standing at (x, y) would, and returns
	// the lines the GM would have read. Same code as "/gm", so the two cannot
	// drift apart.
	BlockCommand(context.Context, *BlockCommandRequest) (*BlockCommandResponse, error)
	mustEmbedUnimplementedGameControlServiceServer()
}

// UnimplementedGameControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameControlServiceServer struct{}

func (UnimplementedGameControlServiceServer) ListOnline(context.Context, *ListOnlineRequest) (*ListOnlineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOnline not implemented")
}
func (UnimplementedGameControlServiceServer) Kick(context.Context, *KickRequest) (*KickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Kick not implemented")
}
func (UnimplementedGameControlServiceServer) Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Broadcast not implemented")
}
func (UnimplementedGameControlServiceServer) Unstuck(context.Context, *UnstuckRequest) (*UnstuckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unstuck not implemented")
}
func (UnimplementedGameControlServiceServer) DeliverNow(context.Context, *DeliverNowRequest) (*DeliverNowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverNow not implemented")
}
func (UnimplementedGameControlServiceServer) Overlays(context.Context, *OverlaysRequest) (*OverlaysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Overlays not implemented")
}
func (UnimplementedGameControlServiceServer) Drain(context.Context, *DrainRequest) (*DrainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Drain not implemented")
}
func (UnimplementedGameControlServiceServer) ListBlocks(context.Context, *ListBlocksRequest) (*ListBlocksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlocks not implemented")
}
func (UnimplementedGameControlServiceServer) BlockCommand(context.Context, *BlockCommandRequest) (*BlockCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BlockCommand not implemented")
}
func (UnimplementedGameControlServiceServer) mustEmbedUnimplementedGameControlServiceServer() {}
func (UnimplementedGameControlServiceServer) testEmbeddedByValue()                            {}

// UnsafeGameControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameControlServiceServer will
// result in compilation errors.
type UnsafeGameControlServiceServer interface {
	mustEmbedUnimplementedGameControlServiceServer()
}

func RegisterGameControlServiceServer(s grpc.ServiceRegistrar, srv GameControlServiceServer) {
	// If the following call panics, it indicates UnimplementedGameControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameControlService_ServiceDesc, srv)
}

func _GameControlService_ListOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOnlineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameControlServiceServer).ListOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameControlService_ListOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameControlServiceServer).ListOnline(ctx, req.(*ListOnlineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameControlService_Kick_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameControlServiceServer).Kick(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameControlService_Kick_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameControlServiceServer).Kick(ctx, req.(*KickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameControlService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameControlServiceServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameControlService_Broadcast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameControlServiceServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameControlService_Unstuck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnstuckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameControlServiceServer).Unstuck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameControlService_Unstuck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameControlServiceServer).Unstuck(ctx, req.(*UnstuckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameControlService_DeliverNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameControlServiceServer).DeliverNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameControlService_DeliverNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameControlServiceServer).DeliverNow(ctx, req.(*DeliverNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameControlService_Overlays_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OverlaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameControlServiceServer).Overlays(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameControlService_Overlays_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameControlServiceServer).Overlays(ctx, req.(*OverlaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameControlService_Drain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameControlServiceServer).Drain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameControlService_Drain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameControlServiceServer).Drain(ctx, req.(*DrainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameControlService_ListBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameControlServiceServer).ListBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameControlService_ListBlocks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameControlServiceServer).ListBlocks(ctx, req.(*ListBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameControlService_BlockCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BlockCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameControlServiceServer).BlockCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameControlService_BlockCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameControlServiceServer).BlockCommand(ctx, req.(*BlockCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameControlService_ServiceDesc is the grpc.ServiceDesc for GameControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "game.v1.GameControlService",
	HandlerType: (*GameControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListOnline",
			Handler:    _GameControlService_ListOnline_Handler,
		},
		{
			MethodName: "Kick",
			Handler:    _GameControlService_Kick_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _GameControlService_Broadcast_Handler,
		},
		{
			MethodName: "Unstuck",
			Handler:    _GameControlService_Unstuck_Handler,
		},
		{
			MethodName: "DeliverNow",
			Handler:    _GameControlService_DeliverNow_Handler,
		},
		{
			MethodName: "Overlays",
			Handler:    _GameControlService_Overlays_Handler,
		},
		{
			MethodName: "Drain",
			Handler:    _GameControlService_Drain_Handler,
		},
		{
			MethodName: "ListBlocks",
			Handler:    _GameControlService_ListBlocks_Handler,
		},
		{
			MethodName: "BlockCommand",
			Handler:    _GameControlService_BlockCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/game/v1/game.proto",
}
